### ISSUE TITLE
ROS 2 Trajectory topic vulnerable to DoS

### ISSUE THREAD

**Issue by aliasbot** [aliasrobotics/RVD#100]
```yaml
{
    "id": 100,
    "title": "ROS 2 Trajectory topic vulnerable to DoS",
    "type": "vulnerability",
    "description": "Trajectory messages sent to the /trajectory topic of the H-ROS SoM cause an unrecoverable failure on the ROS node that can only be fixed by a system restart.",
    "cwe": "CWE-Denial of Service (CWE-400)",
    "cve": "None",
    "keywords": [
        "malformed",
        "robot",
        "robot: MARA",
        "severity: medium",
        "vendor: Acutronic Robotics",
        "vulnerability"
    ],
    "system": "MARA",
    "vendor": "Acutronic Robotics",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "RVSS:1.0/AV:IN/AC:L/PR:N/UI:N/Y:Z/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/100"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2019-02-10",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-02-10",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/100",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
