### ISSUE TITLE
RVD#1215: CWE-120 (buffer), Does not check for buffer overflows when copying to destination (CWE-1... @ comm/package_serializer.h:75

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#1215]
```yaml
{
    "title": "RVD#1215: CWE-120 (buffer), Does not check for buffer overflows when copying to destination (CWE-1... @ comm/package_serializer.h:75",
    "system": "/opt/ros_ur_ws/src/Universal_Robots_ROS_Driver/ur_robot_driver/include/ur_robot_driver/comm/package_serializer.h:75:10",
    "cve": "None",
    "mitigation": {
        "date-mitigation": "",
        "pull-request": "",
        "description": "Make sure destination can always hold the source data"
    },
    "description": "Does not check for buffer overflows when copying to destination (CWE-120). Make sure destination can always hold the source data. . Happening @ ...comm/package_serializer.h:75",
    "id": 1215,
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/1215"
    ],
    "severity": {
        "rvss-vector": "",
        "cvss-vector": "",
        "severity-description": "",
        "rvss-score": 0,
        "cvss-score": 0
    },
    "vendor": null,
    "exploitation": {
        "exploitation-image": "",
        "exploitation-vector": "",
        "description": ""
    },
    "keywords": [
        "flawfinder",
        "flawfinder_level_2",
        "static analysis",
        "testing",
        "triage",
        "CWE-120",
        "bug"
    ],
    "type": "bug",
    "cwe": [
        "CWE-120"
    ],
    "flaw": {
        "specificity": "subject-specific",
        "subsystem": "N/A",
        "reproducibility": "always",
        "phase": "testing",
        "languages": "None",
        "package": "N/A",
        "reported-by": "Alias Robotics",
        "application": "N/A",
        "architectural-location": "application-specific",
        "detected-by-method": "testing static",
        "date-detected": "2020-01-21 (12:05)",
        "issue": "https://github.com/aliasrobotics/RVD/issues/1215",
        "reproduction-image": "",
        "trace": "(context) std::memcpy(&inner, &val, size);",
        "reproduction": "See artifacts below (if available)",
        "detected-by": "Alias Robotics",
        "date-reported": "2020-01-21 (12:05)",
        "reported-by-relationship": "automatic"
    }
}
```
