### ISSUE TITLE
RVD#1219: CWE-362 (misc), Check when opening files - can an attacker redirect it (via symlinks),... @ obot_driver/comm/server.h:48

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#1219]
```yaml
{
    "title": "RVD#1219: CWE-362 (misc), Check when opening files - can an attacker redirect it (via symlinks),... @ obot_driver/comm/server.h:48",
    "system": "/opt/ros_ur_ws/src/Universal_Robots_ROS_Driver/ur_robot_driver/include/ur_robot_driver/comm/server.h:48:16",
    "cve": "None",
    "mitigation": {
        "date-mitigation": "",
        "pull-request": "",
        "description": ""
    },
    "description": "Check when opening files - can an attacker redirect it (via symlinks), force the opening of special file type (e.g., device files), move things around to create a race condition, control its ancestors, or change its contents? (CWE-362). . . Happening @ ...obot_driver/comm/server.h:48",
    "id": 1219,
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/1219"
    ],
    "severity": {
        "rvss-vector": "",
        "cvss-vector": "",
        "severity-description": "",
        "rvss-score": 0,
        "cvss-score": 0
    },
    "vendor": null,
    "exploitation": {
        "exploitation-image": "",
        "exploitation-vector": "",
        "description": ""
    },
    "keywords": [
        "flawfinder",
        "flawfinder_level_2",
        "static analysis",
        "testing",
        "triage",
        "CWE-362",
        "bug"
    ],
    "type": "bug",
    "cwe": [
        "CWE-362"
    ],
    "flaw": {
        "specificity": "subject-specific",
        "subsystem": "N/A",
        "reproducibility": "always",
        "phase": "testing",
        "languages": "None",
        "package": "N/A",
        "reported-by": "Alias Robotics",
        "application": "N/A",
        "architectural-location": "application-specific",
        "detected-by-method": "testing static",
        "date-detected": "2020-01-21 (12:09)",
        "issue": "https://github.com/aliasrobotics/RVD/issues/1219",
        "reproduction-image": "",
        "trace": "(context) virtual bool open(int socket_fd, struct sockaddr* address, size_t address_len);",
        "reproduction": "See artifacts below (if available)",
        "detected-by": "Alias Robotics",
        "date-reported": "2020-01-21 (12:09)",
        "reported-by-relationship": "automatic"
    }
}
```
