### ISSUE TITLE
RVD#1223: CWE-119/CWE-120 (buffer), Statically-sized arrays can be improperly restricted, leading to poten... @ queue/readerwriterqueue.h:678

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#1223]
```yaml
{
    "title": "RVD#1223: CWE-119/CWE-120 (buffer), Statically-sized arrays can be improperly restricted, leading to poten... @ queue/readerwriterqueue.h:678",
    "system": "/opt/ros_ur_ws/src/Universal_Robots_ROS_Driver/ur_robot_driver/include/ur_robot_driver/queue/readerwriterqueue.h:678:3",
    "cve": "None",
    "mitigation": {
        "date-mitigation": "",
        "pull-request": "",
        "description": "Perform bounds checking, use functions that limit length, or ensure that the size is larger than the maximum possible length"
    },
    "description": "Statically-sized arrays can be improperly restricted, leading to potential overflows or other issues (CWE-119!/CWE-120). Perform bounds checking, use functions that limit length, or ensure that the size is larger than the maximum possible length. . Happening @ ...queue/readerwriterqueue.h:678",
    "id": 1223,
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/1223"
    ],
    "severity": {
        "rvss-vector": "",
        "cvss-vector": "",
        "severity-description": "",
        "rvss-score": 0,
        "cvss-score": 0
    },
    "vendor": null,
    "exploitation": {
        "exploitation-image": "",
        "exploitation-vector": "",
        "description": ""
    },
    "keywords": [
        "flawfinder",
        "flawfinder_level_2",
        "static analysis",
        "testing",
        "triage",
        "CWE-119",
        "CWE-120",
        "bug"
    ],
    "type": "bug",
    "cwe": [
        "CWE-119",
        "CWE-120"
    ],
    "flaw": {
        "specificity": "subject-specific",
        "subsystem": "N/A",
        "reproducibility": "always",
        "phase": "testing",
        "languages": "None",
        "package": "N/A",
        "reported-by": "Alias Robotics",
        "application": "N/A",
        "architectural-location": "application-specific",
        "detected-by-method": "testing static",
        "date-detected": "2020-01-21 (12:12)",
        "issue": "https://github.com/aliasrobotics/RVD/issues/1223",
        "reproduction-image": "",
        "trace": "(context) char cachelineFiller_[MOODYCAMEL_CACHE_LINE_SIZE - sizeof(WeakAtomic<Block*>)];",
        "reproduction": "See artifacts below (if available)",
        "detected-by": "Alias Robotics",
        "date-reported": "2020-01-21 (12:12)",
        "reported-by-relationship": "automatic"
    }
}
```
