### ISSUE TITLE
geometric_shapes: detected memory leaks, shapes::createMeshF...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#133]
```yaml
{
    "id": 133,
    "title": "geometric_shapes: detected memory leaks, shapes::createMeshF...",
    "type": "weakness",
    "description": "Issue detected while running Address Sanitizer (ASan).\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "package: geometric_shapes",
        "robot component: ROS2",
        "robot component: moveit2",
        "weakness"
    ],
    "system": "moveit2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/133"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "Sat, 27 Jul 2019 08:08:26 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Sat, 27 Jul 2019 08:08:26 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/133",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
