### ISSUE TITLE
RVD#137: octomap-distribution: detected memory leaks, octomap::MapCol...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#137]
```yaml
{
    "id": 137,
    "title": "RVD#137: octomap-distribution: detected memory leaks, octomap::MapCol...",
    "type": "weakness",
    "description": "Issue detected while running Address Sanitizer (ASan).\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "package: octomap-distribution",
        "robot component: ROS2",
        "robot component: moveit2",
        "weakness"
    ],
    "system": "moveit2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/137"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "Sat, 27 Jul 2019 08:08:30 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Sat, 27 Jul 2019 08:08:30 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/137",
        "reproducibility": "",
        "trace": " #0 0x7f388770b458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458) #1 0x56475b8f6425 in octomap::MapCollection<octomap::MapNode<octomap::OcTree> >::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /opt/ros2_moveit2_asan/src/octomap/octomap/include/octomap/MapCollection.hxx:107 #2 0x56475b8f2b1f in octomap::MapCollection<octomap::MapNode<octomap::OcTree> >::MapCollection(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /opt/ros2_moveit2_asan/src/octomap/octomap/include/octomap/MapCollection.hxx:46 #3 0x56475b8eee31 in main /opt/ros2_moveit2_asan/src/octomap/octomap/src/testing/test_mapcollection.cpp:53 #4 0x7f38863d2b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
