### ISSUE TITLE
Bash scripts (magic UR files) get launched automatically with root privileges and without validation or sanitizing

### ISSUE THREAD

**Issue by LanderU** [aliasrobotics/RVD#1408]
```yaml
{
    "id": 0,
    "title": "Bash scripts (magic UR files) get launched automatically with root privileges and without validation or sanitizing",
    "type": "vulnerability",
    "description": "We found that the Universal Robots Controllers will automatically launch and execute certain magic files (bash scripts). The corresponding daemon is configured to run on every boot and presents apparently no filter except certain restrictions on the file name (so called magic UR files). Exemplary files can be found at https://www.universal-robots.com/download/?option=16449#section16447",
    "cwe": "CWE-20 (Improper Input Validation)",
    "cve": "CVE-2019-19626",
    "keywords": [
        "Universal Robots",
        "manipulation",
        "cobot",
        "CB 3.1",
        "CB 3.4.5"
    ],
    "system": "Universal Robots Robot Controllers CB 3.1 3.4.5-100",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 10.0,
        "rvss-vector": "RVSS:1.0/AV:PP/AC:L/PR:N/UI:N/Y:Z/S:U/C:H/I:H/A:H/H:H",
        "severity-description": "critical",
        "cvss-score": 6.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://www.universal-robots.com/download/?option=16449#section16447"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "subject-specific",
        "architectural-location": "application-specific code",
        "application": "manipulator, control box",
        "subsystem": "cognition:manipulation",
        "package": "N/A",
        "languages": "shell",
        "date-detected": null,
        "detected-by": "Rub\u00e9n Campo Medina, Xabier Saez de C\u00e1mara, Lander Usategui San Juan, Unai Ayucar Carbajo (Alias Robotics)",
        "detected-by-method": "testing violation",
        "date-reported": "2020-03-30",
        "reported-by": "V\u00edctor Mayoral Vilches, Endika Gil Uriarte, Rub\u00e9n Campo Medina, Xabier Saez de C\u00e1mara, Lander Usategui San Juan, Unai Ayucar Carbajo (Alias Robotics)",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "All magic files below that match /media/usb/ur-magic*.sh get executed automatically. Exploitation requires one to place these \"magic files\" in the corresponding path. This vulnerability can get  exploited individually in a physical way, via an external flash drive or remotely in combination with other vulnerabilities such as RVD#672 (https://github.com/aliasrobotics/RVD/issues/672 also classified as CVE-2018-10633).",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "Validate and sanitize magic files as well as implement Discretionary Access Control (DAC) model by providing Mandatory Access Control (MAC). This will limit the programs' capabilities with per-program profiles (e.g. via AppArmor)",
        "pull-request": "N/A",
        "date-mitigation": null
    }
}
```
