### ISSUE TITLE
In X.Org Server (aka xserver and xorg-server) before 1.19.4, an a

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#1409]
```yaml
{
    "id": 0,
    "title": "In X.Org Server (aka xserver and xorg-server) before 1.19.4, an a",
    "type": "vulnerabitity",
    "description": "In X.Org Server (aka xserver and xorg-server) before 1.19.4, an attacker authenticated to an X server with the X shared memory extension enabled can cause aborts of the X server or replace shared memory segments of other X clients in the same session.",
    "cwe": "CWE-269",
    "cve": "CVE-2017-13721",
    "keywords": [
        "X.Org"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 10.0,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:M/S:C/C:H/I:L/A:L/H:U",
        "severity-description": null,
        "cvss-score": 4.7,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-13721",
        "http://www.openwall.com/lists/oss-security/2017/10/04/10",
        "http://www.securityfocus.com/bid/101238",
        "https://cgit.freedesktop.org/xorg/xserver/commit/?id=b95f25af141d33a65f6f821ea9c003f66a01e1f1",
        "https://lists.x.org/archives/xorg-announce/2017-October/002808.html",
        "https://security.gentoo.org/glsa/201710-30"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "subject-specific",
        "architectural-location": "Operating system",
        "application": "Control box, operating system",
        "subsystem": "N/A",
        "package": "xserver-xorg-core 2:1.16.0.901-1 i386",
        "languages": "shell",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-03-30",
        "reported-by": "Unai Ayucar Carbajo <uayucar@aliasrobotics.com>",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "Any time X server is launched",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "attacker authenticated to an X server with the X shared memory extension enabled can cause aborts of the X server or replace shared memory segments of other X clients in the same session",
        "exploitation-image": "https://dl.packetstormsecurity.net/1811-exploits/xorg_x11_suid_server.rb.txt",
        "exploitation-vector": null
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade xserver-xorg-core",
        "pull-request": "N/A",
        "date-mitigation": null
    }
}
```
