### ISSUE TITLE
OpenSSH remote DoS in CB

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#1410]
```yaml
{
    "id": 0,
    "title": "OpenSSH remote DoS in CB",
    "type": "vulnerability",
    "description": "We found that the Universal Robots Controllers' file system based in Debian is subject to CVE-2016-6210 which allows attackers with networking connection to the robot to cause a Denial of Service (DoS). The auth_password function in auth-passwd.c in sshd in OpenSSH before 7.3 does not limit password lengths for password authentication, which allows remote attackers to cause a denial of service (crypt CPU consumption) via a long string.",
    "cwe": "CWE-20 (Improper Input Validation)",
    "cve": "CVE-2016-6515",
    "keywords": [
        "Universal Robots",
        "manipulation",
        "cobot",
        "CB 3.x"
    ],
    "system": "Universal Robots Robot Controllers CB 3.x",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 7.6,
        "rvss-vector": "RVSS:1.0/AV:AN/AC:L/PR:N/UI:N/Y:Z/S:U/C:N/I:N/A:H/H:E",
        "severity-description": "high",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-6515",
        "https://nvd.nist.gov/vuln/detail/CVE-2016-6515",
        "https://github.com/opsxcq/exploit-CVE-2016-6515",
        "https://www.cvedetails.com/cve/CVE-2016-6515/"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "general issue",
        "architectural-location": "third-party",
        "application": "manipulator, control box",
        "subsystem": "communication",
        "package": "openssh-server",
        "languages": "C",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches, Lander Usategui San Juan (Alias Robotics), Bernhard Dieber (Joanneum Research)",
        "detected-by-method": "testing violation",
        "date-reported": "2020-03-30",
        "reported-by": "Victor Mayoral Vilches (Alias Robotics)",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "always",
        "trace": "N/A",
        "reproduction": "See exploitation",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "OpenSSH version prior to 7.3 does not limit the password length for authentication. Hence, to exploit this vulnerability' we will send a crafted data which is of 90000 characters in length to the 'password' field while attempting to log in to a remote machine via ssh with username as 'root'. Based on CVE-2016-6515's exploit.",
        "exploitation-image": "Not available",
        "exploitation-vector": "robosploit/modules/3_exploitation/ur/ssh-remote-dos.py"
    },
    "mitigation": {
        "description": "Update OpenSSH to a more updated version that includes a fix for this vulnerability",
        "pull-request": "N/A",
        "date-mitigation": null
    }
}
```

**Comment by vmayoral** [comment]
Exploit demonstrated at https://asciinema.org/a/315015. Validated it for:
- Universal Robots CB3.1, firmware version 3.12.1 (latest at the time of writing)
- Universal Robots CB3.1, firmware version 3.12
- Universal Robots CB3.1, firmware version 3.11
- Universal Robots CB3.1, firmware version 3.10

Probably applies to older versions as well.

**Comment by vmayoral** [comment]
Sharing the `alurity.yml` file that can be used to reproduce this ticket below:

<details><summary>alurity.yml file</summary>

```yaml
##################
# alurity.yml example file
##################
networks:
  - network:
    - driver: overlay
    - name: urnetwork
    - encryption: false

containers:
  - container:
    - name: ur_310
    - modules:
         - base: registry.gitlab.com/aliasrobotics/offensive/alurity/robo_ur_cb3_1:3.10
         - network: urnetwork
  # - container:
  #   - name: ur_311
  #   - modules:
  #        - base: registry.gitlab.com/aliasrobotics/offensive/alurity/robo_ur_cb3_1:3.11
  #        - network: urnetwork
  # - container:
  #   - name: ur_312
  #   - modules:
  #        - base: registry.gitlab.com/aliasrobotics/offensive/alurity/robo_ur_cb3_1:3.12
  #        - network: urnetwork
  - container:
    - name: ur_3121
    - modules:
         - base: registry.gitlab.com/aliasrobotics/offensive/alurity/robo_ur_cb3_1:3.12.1
         - network: urnetwork
  - container:
    - name: attacker
    - modules:
         - base: registry.gitlab.com/aliasrobotics/offensive/alurity/alurity:latest
         - volume: registry.gitlab.com/aliasrobotics/offensive/alurity/expl_robosploit/expl_robosploit:latest
         - volume: registry.gitlab.com/aliasrobotics/offensive/alurity/deve_atom:latest
         - volume: registry.gitlab.com/aliasrobotics/offensive/alurity/reco_nmap:latest
         - network: urnetwork

##################
# flow for testing and development
##################

flow:
  - container:
    - name: attacker
    - window:
        - name: attacker
        - commands:
          - command: "sleep 3"
          - command: "nmap -sV -T5 ur_3121"
  - container:
    - name: ur_3121
    - window:
        - name: ur_3121
        - commands:
          - command: "mkdir /var/run/sshd"
          - command: "/usr/sbin/sshd"
          - split: horizontal
          - command: "htop"
          # - command: "glances"
    # - select: ur_3121
  - attach: attacker
```
</details>
