### ISSUE TITLE
rbash in Bash before 4.4-beta2 did not prevent the shell user from modifying BASH_CMDS, thus allowing the user to execute any command with the permissions of the shell.

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1422]
```yaml
{
    "id": 0,
    "title": "rbash in Bash before 4.4-beta2 did not prevent the shell user from modifying BASH_CMDS, thus allowing the user to execute any command with the permissions of the shell.",
    "type": "vulnerabitity",
    "description": "rbash in Bash before 4.4-beta2 did not prevent the shell user from modifying BASH_CMDS, thus allowing the user to execute any command with the permissions of the shell.",
    "cwe": "CWE-20",
    "cve": "CVE-2019-9924",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 7.8,
        "rvss-vector": "RVSS:1.0/AV:L/AC:L/PR:L/UI:N/Y:U/S:U/C:H/I:H/A:H/H:N",
        "severity-description": "HIGH",
        "cvss-score": 7.8,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9924"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "bash 4.2+dfsg-0.1+deb7u3 i386",
        "languages": "Bash",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-03-31",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not Available",
        "reproduction-image": "Not Available"
    },
    "exploitation": {
        "description": "Arbitrary command execution by altering a variable",
        "exploitation-image": "Not Available",
        "exploitation-vector": "Not Available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade bash",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
