### ISSUE TITLE
The dump_callback function in SQLite 3.20.0 allows remote attackers to cause a denial of service

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1423]
```yaml
{
    "id": 271,
    "title": "The dump_callback function in SQLite 3.20.0 allows remote attackers to cause a denial of service",
    "type": "vulnerabitity",
    "description": "The dump_callback function in SQLite 3.20.0 allows remote attackers to cause a denial of service (EXC_BAD_ACCESS and application crash) via a crafted file.",
    "cwe": "CWE-20",
    "cve": "CVE-2017-13685",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 4.6,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/H:U/Y:U/UI:R/S:U/PR:L/C:N/I:L/A:L",
        "severity-description": "Medium",
        "cvss-score": 4.6,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/UI:R/S:U/PR:L/C:N/I:L/A:L"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-13685 https://sqlite.org/src/info/02f0f4c54f2819b3 https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg105314.html"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libsqlite3-0 3.7.13-1+deb7u1 i386",
        "languages": "sql",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-03-31",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security Researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not Available",
        "reproduction-image": "Not Available"
    },
    "exploitation": {
        "description": "Executing a Command related to the dump_callback function will cause application to crash.",
        "exploitation-image": "Not Available",
        "exploitation-vector": "Not Available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libsqlite3-0",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
