### ISSUE TITLE
It was discovered the fix for CVE-2018-19758 (libsndfile) was not complete

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1425]
```yaml
{
    "id": 0,
    "title": "It was discovered the fix for CVE-2018-19758 (libsndfile) was not complete",
    "type": "vulnerabitity",
    "description": "It was discovered the fix for CVE-2018-19758 (libsndfile) was not complete and still allows a read beyond the limits of a buffer in wav_write_header() function in wav.c. A local attacker may use this flaw to make the application crash.",
    "cwe": "CWE-125",
    "cve": "CVE-2019-3832",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 5.0,
        "rvss-vector": "RVSS:1.0/AV:L/AC:L/PR:L/UI:R/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "Medium",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:R/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-3832"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libsndfile1 1.0.25-5 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "The fix for a previous vulnerability CVE-2018-19758 was not completed properly still can be triggered by performing an OOB read",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libsndfile1",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
