### ISSUE TITLE
The malloc function in the GNU C Library 2.2 Could lead to a heap overflow

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1427]
```yaml
{
    "id": 0,
    "title": "The malloc function in the GNU C Library 2.2 Could lead to a heap overflow",
    "type": "vulnerabitity",
    "description": "The malloc function in the GNU C Library (aka glibc or libc6) 2.26 could return a memory block that is too small if an attempt is made to allocate an object whose size is close to SIZE_MAX, potentially leading to a subsequent heap overflow. This occurs because the per-thread cache (aka tcache) feature enables a code path that lacks an integer overflow check.",
    "cwe": "CWE-190",
    "cve": "CVE-2017-17426",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 7.0,
        "rvss-vector": "RVSS:1.0/AV:IN/AC:H/PR:N/UI:N/Y:U/S:U/C:H/I:H/A:H/H:N",
        "severity-description": "HIGH",
        "cvss-score": 8.1,
        "cvss-vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-17426"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libc6 2.19-11 i386",
        "languages": "C",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not Available",
        "reproduction-image": "Not Available"
    },
    "exploitation": {
        "description": "A heap overflow can be triggered after allocating a larger object than the size of the memory on glibc",
        "exploitation-image": "Not Available",
        "exploitation-vector": "Not Available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libc6",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
