### ISSUE TITLE
The FTP wildcard function in curl and libcurl before 7.57.0 allows DoS

### ISSUE THREAD

**Issue by unaithetutamatumatu** [aliasrobotics/RVD#1428]
```yaml
{
    "id": 0,
    "title": "The FTP wildcard function in curl and libcurl before 7.57.0 allows DoS",
    "type": "vulnerabitity",
    "description": "The FTP wildcard function in curl and libcurl before 7.57.0 allows remote attackers to cause a denial of service (out-of-bounds read and application crash) or possibly have unspecified other impact via a string that ends with an '[' character.",
    "cwe": "CWE-125",
    "cve": "CVE-2017-8817",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 10.0,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:M/S:U/C:H/I:H/A:H/H:U",
        "severity-description": "critical",
        "cvss-score": 9.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-8817",
        "https://www.securitytracker.com/id/1039897",
        "https://www.securitytracker.com/id/1039897"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "Library specific",
        "architectural-location": "Python Package",
        "application": "libcurl",
        "subsystem": "N/A",
        "package": "libcurl3 7.38.0-4+deb8u13 i386",
        "languages": "Python",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "OSS-Fuzz",
        "reported-by-relationship": "N/A",
        "issue": "N/A",
        "reproducibility": "Any file transfer done via libcurl",
        "trace": "N/A",
        "reproduction": "N/A",
        "reproduction-image": "N/A"
    },
    "exploitation": {
        "description": "A remote server can return specially crafted data to trigger an out-of-bounds memory read error in the FTP wildcard matching function (CURLOPT_WILDCARDMATCH) and cause the target connected libcurl client to be redirected.",
        "exploitation-image": "N/A",
        "exploitation-vector": "N/A"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libcurl3",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
