### ISSUE TITLE
Null pointer dereference vulnerability causes TLS/SSL server using NSS to crash.

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1429]
```yaml
{
    "id": 0,
    "title": "Null pointer dereference vulnerability causes TLS/SSL server using NSS to crash.",
    "type": "vulnerabitity",
    "description": "Null pointer dereference vulnerability exists in K11_SignWithSymKey / ssl3_ComputeRecordMACConstantTime in NSS before 3.26, which causes the TLS/SSL server using NSS to crash.",
    "cwe": "CWE-476",
    "cve": "CVE-2016-5285",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 7.5,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "high",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-5285"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libnss3 2:3.14.5-1+deb7u3 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "Alias Robotics. S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": null
    },
    "exploitation": {
        "description": "A missing null check within MNSS can be remotely triggered leading to a DoS",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libnss3",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
