### ISSUE TITLE
Crafted file can lead to a DoS due to a memory alocation failure in elfutils

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1430]
```yaml
{
    "id": 0,
    "title": "Crafted file can lead to a DoS due to a memory alocation failure in elfutils",
    "type": "vulnerabitity",
    "description": "The __libelf_set_rawdata_wrlock function in elf_getdata.c in elfutils before 0.168 allows remote attackers to cause a denial of service (crash) via a crafted (1) sh_off or (2) sh_size ELF header value, which triggers a memory allocation failure.",
    "cwe": "CWE-119",
    "cve": "CVE-2016-10255",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 6.5,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:R/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "medium",
        "cvss-score": 6.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-10255"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libelf1 0.159-3 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not Available",
        "reproduction-image": "Not Available"
    },
    "exploitation": {
        "description": "Two functions in elfutils can be remotely exploited to trigger a DoS via a memory allocation failure",
        "exploitation-image": "Not Available",
        "exploitation-vector": "Not Available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libelf1",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
