### ISSUE TITLE
libgcrypt before version 1.7.8 is vulnerable to a cache side-channel attack

### ISSUE THREAD

**Issue by unaithetutamatumatu** [aliasrobotics/RVD#1431]
```yaml
{
    "id": 0,
    "title": "libgcrypt before version 1.7.8 is vulnerable to a cache side-channel attack",
    "type": "vulnerabitity",
    "description": "libgcrypt before version 1.7.8 is vulnerable to a cache side-channel attack resulting into a complete break of RSA-1024 while using the left-to-right method for computing the sliding-window expansion. The same attack is believed to work on RSA-2048 with moderately more computation. This side-channel requires that attacker can run arbitrary software on the hardware where the private RSA key is used.",
    "cwe": "CWE-310",
    "cve": "CVE-2017-7526",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 8.0,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:H/PR:N/UI:N/Y:M/S:C/C:H/I:N/A:N/H:U",
        "severity-description": "High",
        "cvss-score": 6.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-7526",
        "https://www.ibm.com/support/pages/security-bulletin-vulnerability-libgcrypt-affects-ibm-flex-system-manager-fsm-cve-2017-7526",
        "https://access.redhat.com/security/cve/cve-2017-7526",
        "https://eprint.iacr.org/2017/627"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "Cryptographic keys done by ligcrypt",
        "architectural-location": "GnuPG",
        "application": "DSA keys",
        "subsystem": "ElGamal keys",
        "package": "gnupg 1.4.12-7+deb7u6 i386",
        "languages": "OpenGPG",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "Daniel J. Bernstein",
        "reported-by-relationship": "N/A",
        "issue": "Information Exposure",
        "reproducibility": "For any key generated with libgcrypt",
        "trace": "N/A",
        "reproduction": "N/A",
        "reproduction-image": "N/A"
    },
    "exploitation": {
        "description": "Vulnerable to a to cache side-channel attack resulting into a complete break of RSA-1024 while using the left-to-right method for computing the sliding-window expansion.",
        "exploitation-image": "N/A",
        "exploitation-vector": "N/A"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade gnupg",
        "pull-request": "N/A",
        "date-mitigation": null
    }
}
```
