### ISSUE TITLE
A remote code execution vulnerability in libxml2 could allow execution of arbritary code.

### ISSUE THREAD

**Issue by unaithetutamatumatu** [aliasrobotics/RVD#1434]
```yaml
{
    "id": 0,
    "title": "A remote code execution vulnerability in libxml2 could allow execution of arbritary code.",
    "type": "vulnerabitity",
    "description": "A remote code execution vulnerability in libxml2 could enable an attacker using a specially crafted file to execute arbitrary code within the context of an unprivileged process. This issue is rated as High due to the possibility of remote code execution in an application that uses this library. Product: Android. Versions: 4.4.4; 5.0.2; 5.1.1; 6.0; 6.0.1; 7.0; 7.1.1; 7.1.2; Android ID: A-37104170.",
    "cwe": "CWE-787",
    "cve": "CVE-2017-0663",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 8.7,
        "rvss-vector": "RVSS:1.0/AV:L/AC:L/PR:N/UI:R/Y:M/S:U/C:H/I:H/A:H/H:U",
        "severity-description": "high",
        "cvss-score": 7.8,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-0663",
        "https://www.debian.org/security/2017/dsa-3952",
        "https://www.securitytracker.com/id/1038623"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "libxml2",
        "subsystem": "N/A",
        "package": "libxml2 2.8.0+dfsg1-7+wheezy2 i386",
        "languages": "XML",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "The vendor",
        "reported-by-relationship": "N/A",
        "issue": null,
        "reproducibility": "always if you have the crafted package",
        "trace": "N/A",
        "reproduction": "N/A",
        "reproduction-image": "N/A"
    },
    "exploitation": {
        "description": "Using a crafted file through libxml2 user can execute arbitrary code within the context of an unprivileged process",
        "exploitation-image": "N/A",
        "exploitation-vector": "N/A"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libxml2",
        "pull-request": "N/A",
        "date-mitigation": null
    }
}
```
