### ISSUE TITLE
elflint.c in elfutils 0.168 does not validate the number of sections nor segments allowing a DoS Attack

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1435]
```yaml
{
    "id": 0,
    "title": "elflint.c in elfutils 0.168 does not validate the number of sections nor segments allowing a DoS Attack",
    "type": "vulnerabitity",
    "description": "elflint.c in elfutils 0.168 does not validate the number of sections and the number of segments, which allows remote attackers to cause a denial of service (memory consumption) via a crafted ELF file.",
    "cwe": "CWE-20",
    "cve": "CVE-2017-7613",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 5.0,
        "rvss-vector": "RVSS:1.0/AV:IN/AC:L/PR:N/UI:R/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "medium",
        "cvss-score": 5.5,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-7613"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libelf1 0.159-3 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-01",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "Using a crafted ELF file, a memory consumption attack can be performed triggering a DoS",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libelf1",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
