### ISSUE TITLE
RVD#1444: RTDE Interface allows unauthenticated reading of robot data and unauthenticated writing of registers and outputs

### ISSUE THREAD

**Issue by bbreilin** [aliasrobotics/RVD#1444]
Fill in following the example below. If you need further clarifications on any of the items, refer to our [taxonomy](https://github.com/aliasrobotics/RVD/blob/master/docs/TAXONOMY.md) (remove these lines line).

```yaml
id: 
title: "RVD#1444: RTDE Interface allows unauthenticated reading of robot data and unauthenticated writing of registers and outputs"
type: vulnerability
description: "CB3 SW Version 3.3 and upwards, e-series SW Version 5.0 and upwards allow authenticated access to the RTDE (Real-Time Data Exchange) interface on port 30004 which allows setting registers, the speed slider fraction as well as digital and analog Outputs. Additionally unautheticated reading of robot data is also possible"
cwe: "CWE-200 (Exposure of Sensitive Information to an Unauthorized Actor)"
cve: 
keywords: [
    "Universal Robots",
    "RTDE",
    "cobot",
    "CB 3.3",
    "e-series"
]
system: "Universal Robots Robot Controllers CB 3.1 3.3 and upwards, e-series 5.0 and upwards"
vendor: "Universal Robots"
severity:
  rvss-score: 0
  rvss-vector: ""
  severity-description: "critical"
  cvss-score: 
  cvss-vector: 
links: [
https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/real-time-data-exchange-rtde-guide/
]
flaw:
  phase: testing
  specificity: subject-specific
  architectural-location: application-specific code
  application: manipulator, control box
  subsystem: cognition:manipulation
  package: N/A
  languages: N/A
  date-detected:
  detected-by: Bernhard Dieber, Benjamin Breiling (and many others)
  detected-by-method: testing violation
  date-reported: 2020-04-01 (16:00)
  reported-by: Bernhard Dieber, Benjamin Breiling (and many others)
  reported-by-relationship: security researcher
  issue: 
  reproducibility: always
  trace: N/A
  reproduction: Not disclosed
  reproduction-image: Not disclosed
exploitation:
  description: Not disclosed
  exploitation-image: Not disclosed
  exploitation-vector: Not disclosed
mitigation:
  description: Not disclosed
  pull-request: Not disclosed
```
