### ISSUE TITLE
RVD#1445: Default password for root user on robot controller

### ISSUE THREAD

**Issue by bbreilin** [aliasrobotics/RVD#1445]
```yaml
id:
title: "RVD#1445: Default password for root user on robot Controller"
type: vulnerability
description: "Default password for root user on the robot controller"
cwe: "CWE-798 (Use of Hard-coded Credentials)"
cve: "CVE-2018-10633"
keywords: [
    "Universal Robots",
    "password",
    "cobot",
    "CB 2"
    "CB 3.1",
    "e-series"
]
system: "Universal Robots Robot Controllers"
vendor: "Universal Robots"
severity:
  rvss-score: 0
  rvss-vector: ""
  severity-description: "critical"
  cvss-score: 
  cvss-vector: 
links: [
   
]
flaw:
  phase: testing
  specificity: subject-specific
  architectural-location: application-specific code
  application: manipulator, control box
  subsystem: cognition:manipulation
  package: N/A
  languages: N/A
  date-detected: 
  detected-by: Bernhard Dieber, Benjamin Breiling (and many others)
  detected-by-method: online research
  date-reported: 2018-04-01 (16:30)
  reported-by: Bernhard Dieber, Benjamin Breiling
  reported-by-relationship: security researcher
  issue:
  reproducibility: always
  trace: N/A
  reproduction: Not disclosed
  reproduction-image: Not disclosed
exploitation:
  description: Not disclosed
  exploitation-image: Not disclosed
  exploitation-vector: Not disclosed
mitigation:
  description: Not disclosed
  pull-request: Not disclosed
```
