### ISSUE TITLE
Carry propagating bug in the Broadwell-specific Montgomery multiplication procedure in OpenSSL 1.0.2 and 1.1.0 before 1.1.0cspecific Montgo

### ISSUE THREAD

**Issue by unaithetutamatumatu** [aliasrobotics/RVD#1447]
```yaml
{
    "id": 0,
    "title": "Carry propagating bug in the Broadwell-specific Montgomery multiplication procedure in OpenSSL 1.0.2 and 1.1.0 before 1.1.0cspecific Montgo",
    "type": "vulnerabitity",
    "description": "There is a carry propagating bug in the Broadwell-specific Montgomery multiplication procedure in OpenSSL 1.0.2 and 1.1.0 before 1.1.0c that handles input lengths divisible by, but longer than 256 bits. Analysis suggests that attacks against RSA, DSA and DH private keys are impossible. This is because the subroutine in question is not used in operations with the private key itself and an input of the attacker's direct choice. Otherwise the bug can manifest itself as transient authentication and key negotiation failures or reproducible erroneous outcome of public-key operations with specially crafted input. Among EC algorithms only Brainpool P-512 curves are affected and one presumably can attack ECDH key negotiation. Impact was not analyzed in detail, because pre-requisites for attack are considered unlikely. Namely multiple clients have to choose the curve in question and the server has to share the private key among them, neither of which is default behavior. Even then only clients that chose the curve will be affected.",
    "cwe": "CWE-320",
    "cve": "CVE-2016-7055",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 6.5,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:H/PR:N/UI:N/Y:T/S:U/C:N/I:N/A:H/H:U",
        "severity-description": "medium",
        "cvss-score": 5.9,
        "cvss-vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-7055",
        "https://www.oracle.com/security-alerts/cpujan2018.html",
        "https://www.openssl.org/news/secadv/20161110.txt",
        "https://www.tenable.com/security/tns-2017-04"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "OpenSSl",
        "subsystem": "libssl1",
        "package": "libssl1.0.0 1.0.1e-2+deb7u13 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-02",
        "reported-by": "Unai Ayucar Carbajo, Richard Morgan (original bug)",
        "reported-by-relationship": "N/A",
        "issue": null,
        "reproducibility": "Unlikely",
        "trace": "N/A",
        "reproduction": "M/A",
        "reproduction-image": "M/A"
    },
    "exploitation": {
        "description": "Among EC algorithms only Brainpool P-512 curves are affected and one presumably can attack ECDH key negotiation",
        "exploitation-image": "N/A",
        "exploitation-vector": "N/A"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libssl1.0.0",
        "pull-request": "N/A",
        "date-mitigation": null
    }
}
```
