### ISSUE TITLE
Integer overflow in the GNU C Library before 2.22 allows context-dependent attackers to cause a DoS

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1450]
```yaml
{
    "id": 0,
    "title": "Integer overflow in the GNU C Library before 2.22 allows context-dependent attackers to cause a DoS",
    "type": "vulnerability",
    "description": "Integer overflow in the _IO_wstr_overflow function in libio/wstrops.c in the GNU C Library (aka glibc or libc6) before 2.22 allows context-dependent attackers to cause a denial of service (application crash) or possibly execute arbitrary code via vectors related to computing a size in bytes, which triggers a heap-based buffer overflow.",
    "cwe": "CWE-190",
    "cve": "CVE-2015-8983",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 8.1,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:H/PR:N/UI:N/Y:U/S:U/C:H/I:H/A:H/H:N",
        "severity-description": "high",
        "cvss-score": 8.1,
        "cvss-vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8983"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libc6 2.19-11 i386",
        "languages": "C",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-02",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "The _IO_wstr_overflow function in libio/wstrops.c in libc6 can be attacked by performing a integer overflow, thus triggering a Crash.",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libc6",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
