### ISSUE TITLE
There is an overflow bug in the AVX2 Montgomery multiplication procedure

### ISSUE THREAD

**Issue by unaithetutamatumatu** [aliasrobotics/RVD#1451]
```yaml
{
    "id": 0,
    "title": "There is an overflow bug in the AVX2 Montgomery multiplication procedure",
    "type": "vulnerability",
    "description": "There is an overflow bug in the AVX2 Montgomery multiplication procedure used in exponentiation with 1024-bit moduli. No EC algorithms are affected. Analysis suggests that attacks against RSA and DSA as a result of this defect would be very difficult to perform and are not believed likely. Attacks against DH1024 are considered just feasible, because most of the work necessary to deduce information about a private key may be performed offline. The amount of resources required for such an attack would be significant. However, for an attack on TLS to be meaningful, the server would have to share the DH1024 private key among multiple clients, which is no longer an option since CVE-2016-0701. This only affects processors that support the AVX2 but not ADX extensions like Intel Haswell (4th generation). Note: The impact from this issue is similar to CVE-2017-3736, CVE-2017-3732 and CVE-2015-3193. OpenSSL version 1.0.2-1.0.2m and 1.1.0-1.1.0g are affected. Fixed in OpenSSL 1.0.2n. Due to the low severity of this issue we are not issuing a new release of OpenSSL 1.1.0 at this time. The fix will be included in OpenSSL 1.1.0h when it becomes available. The fix is also available in commit e502cc86d in the OpenSSL git repository.",
    "cwe": "CWE-200",
    "cve": "CVE-2017-3738",
    "keywords": [
        "libssl"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 6.5,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:H/PR:N/UI:N/Y:T/S:U/C:H/I:N/A:N/H:U",
        "severity-description": "medium",
        "cvss-score": 5.9,
        "cvss-vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-3738",
        "https://www.oracle.com/security-alerts/cpuapr2018.html",
        "https://access.redhat.com/errata/RHSA-2018:0998",
        "https://github.com/openssl/openssl/commit/e502cc86df9dafded1694fceb3228ee34d11c11a"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "Internal",
        "application": "OpenSSL",
        "subsystem": "AVX2 Montgomery multiplication",
        "package": "libssl1.0.0 1.0.1e-2+deb7u13 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-02",
        "reported-by": "Alias Robotics SL,",
        "reported-by-relationship": "N/A",
        "issue": null,
        "reproducibility": "Unlikely",
        "trace": "N/A",
        "reproduction": "N/A",
        "reproduction-image": "N/A"
    },
    "exploitation": {
        "description": "Attacks against RSA and DSA as a result of this defect would be very difficult to perform and are not believed likely. Attacks against DH1024 are considered just feasible, because most of the work necessary to deduce information about a private key may be performed offline. The amount of resources required for such an attack would be significant. ",
        "exploitation-image": "N/A",
        "exploitation-vector": "N/A"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libssl1.0.0",
        "pull-request": "https://github.com/openssl/openssl/commit/5630661aecbea5fe3c4740f5fea744a1f07a6253",
        "date-mitigation": null
    }
}
```
