### ISSUE TITLE
Double free vulnerability in JasPer 1.900.17 allows remote attackers to cause a DoS

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1454]
```yaml
{
    "id": 0,
    "title": "Double free vulnerability in JasPer 1.900.17 allows remote attackers to cause a DoS",
    "type": "vulnerability",
    "description": "Double free vulnerability in the jasper_image_stop_load function in JasPer 1.900.17 allows remote attackers to cause a denial of service (crash) via a crafted JPEG 2000 image file.",
    "cwe": "CWE-415",
    "cve": "CVE-2015-5203",
    "keywords": "triage",
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 5.0,
        "rvss-vector": "RVSS:1.0/AV:IN/AC:L/PR:N/UI:R/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "medium",
        "cvss-score": 5.5,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-5203"
    ],
    "flaw": {
        "phase": "exploitation",
        "specificity": "N/A",
        "architectural-location": "application-specific",
        "application": "JasPer",
        "subsystem": "N/A",
        "package": "libjasper1 1.900.1-13+deb7u2 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-02",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "By means of a crafted file the jasper_image_stop_load function can be used to trigger a crash",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libjasper1",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
