### ISSUE TITLE
An invalid memory address dereference in elfutils through v0.174. that allows attackers to cause a DoS

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1457]
```yaml
{
    "id": 0,
    "title": "An invalid memory address dereference in elfutils through v0.174. that allows attackers to cause a DoS",
    "type": "vulnerability",
    "description": "An invalid memory address dereference was discovered in dwfl_segment_report_module.c in libdwfl in elfutils through v0.174. The vulnerability allows attackers to cause a denial of service (application crash) with a crafted ELF file.",
    "cwe": "CWE-119",
    "cve": "CVE-2018-18310",
    "keywords": [
        "elfutils",
        "libelf",
        "ELF"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 5.0,
        "rvss-vector": "RVSS:1.0/AV:IN/AC:L/PR:N/UI:R/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "medium",
        "cvss-score": 5.5,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-18310"
    ],
    "flaw": {
        "phase": "exploitation",
        "specificity": "N/A",
        "architectural-location": "application-specific",
        "application": "elfutils",
        "subsystem": "N/A",
        "package": "libelf1 0.159-3 i386",
        "languages": "C",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-02",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "Using a crafted ELF file the application can be lead to a DoS via invalid memory address dereference under dwfl_segment_report_module.c on libdwfl",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libelf1",
        "pull-request": "https://sourceware.org/git/?p=elfutils.git;a=commit;h=20f9de9b5f704cec55df92406a50bcbcfca96acd",
        "date-mitigation": null
    }
}
```
