### ISSUE TITLE
Use-after-free vulnerability in bzip2 1.0.6 allows remote attackers to cause a DoS

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1459]
```yaml
{
    "id": 0,
    "title": "Use-after-free vulnerability in bzip2 1.0.6 allows remote attackers to cause a DoS",
    "type": "vulnerability",
    "description": "Use-after-free vulnerability in bzip2recover in bzip2 1.0.6 allows remote attackers to cause a denial of service (crash) via a crafted bzip2 file, related to block ends set to before the start of the block.",
    "cwe": "CWE-416",
    "cve": "CVE-2016-3189",
    "keywords": [
        "bzip2",
        "Use-after-free"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 6.5,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:R/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "medium",
        "cvss-score": 6.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-3189"
    ],
    "flaw": {
        "phase": "exploitation",
        "specificity": "N/A",
        "architectural-location": "application-specific",
        "application": "bzip2",
        "subsystem": "N/A",
        "package": "libbz2-1.0 1.0.6-4 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-02",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "By means of a crafted bzip2 file a use-after-free vulnerability could be exploited in bzip2recover triggering a Crash",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libbz2-1.0",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
