### ISSUE TITLE
Some python versions 2.7/3.7. are vulnerable to DoS via catastrophic backtracking

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1467]
```yaml
{
    "id": 0,
    "title": "Some python versions 2.7/3.7. are vulnerable to DoS via catastrophic backtracking",
    "type": "vulnerability",
    "description": "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in the difflib.IS_LINE_JUNK method.  An attacker could use this flaw to cause denial of service.",
    "cwe": "NVD-CWE-noinfo",
    "cve": "CVE-2018-1061",
    "keywords": [
        "Python"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 9.1,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:U/S:U/C:N/I:H/A:H/H:N",
        "severity-description": "critical",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-1061",
        "http://www.securitytracker.com/id/1042001",
        "https://access.redhat.com/errata/RHBA-2019:0327",
        "https://access.redhat.com/errata/RHSA-2018:3041",
        "https://access.redhat.com/errata/RHSA-2018:3505",
        "https://access.redhat.com/errata/RHSA-2019:1260",
        "https://access.redhat.com/errata/RHSA-2019:3725",
        "https://bugs.python.org/issue32981",
        "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1061",
        "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1",
        "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1",
        "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html",
        "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html",
        "https://lists.fedoraproject.org/archives/list/package- announce@lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/",
        "https://lists.fedoraproject.org/archives/list/package- announce@lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/",
        "https://lists.fedoraproject.org/archives/list/package- announce@lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/",
        "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbst03951en_us",
        "https://usn.ubuntu.com/3817-1/",
        "https://usn.ubuntu.com/3817-2/",
        "https://www.debian.org/security/2018/dsa-4306",
        "https://www.debian.org/security/2018/dsa-4307"
    ],
    "flaw": {
        "phase": "exploitation",
        "specificity": "N/A",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "python2.7-minimal 2.7.3-6+deb7u2 i386",
        "languages": "python",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-03",
        "reported-by": "James Davis (Original Bug), Alias robotics S.L.",
        "reported-by-relationship": "Security Researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "the catastrophic backtracking in the difflib.IS_LINE_JUNK method can be leveraged to cause the application to crash.",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade python2.7-minimal",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
