### ISSUE TITLE
http.cookiejar.DefaultPolicy.domain_return_ok in Python before 3.7.3 can be tricked into sending existing cookies to the wrong server.

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1468]
```yaml
{
    "id": 0,
    "title": "http.cookiejar.DefaultPolicy.domain_return_ok in Python before 3.7.3 can be tricked into sending existing cookies to the wrong server.",
    "type": "vulnerability",
    "description": "http.cookiejar.DefaultPolicy.domain_return_ok in Lib/http/cookiejar.py in Python before 3.7.3 does not correctly validate the domain it can be tricked into sending existing cookies to the wrong server. An attacker may abuse this flaw by using a server with a hostname that has another valid hostname as a suffix (e.g., pythonicexample.com to steal cookies for example.com). When a program uses http.cookiejar.DefaultPolicy and tries to do an HTTP connection to an attacker-controlled server, existing cookies can be leaked to the attacker. This affects 2.x through 2.7.16, 3.x before 3.4.10, 3.5.x before 3.5.7, 3.6.x before 3.6.9, and 3.7.x before 3.7.3.",
    "cwe": "CWE-20",
    "cve": "CVE-2018-20852",
    "keywords": [
        "Python"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 5.3,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:U/S:U/C:L/I:N/A:N/H:N",
        "severity-description": "medium",
        "cvss-score": 5.3,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-20852",
        "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00071.html",
        "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00074.html",
        "https://access.redhat.com/errata/RHSA-2019:3725",
        "https://access.redhat.com/errata/RHSA-2019:3948",
        "https://bugs.python.org/issue35121",
        "https://lists.debian.org/debian-lts-announce/2019/08/msg00022.html",
        "https://lists.debian.org/debian-lts-announce/2019/08/msg00040.html",
        "https://lists.fedoraproject.org/archives/list/package- announce@lists.fedoraproject.org/message/COATURTCY7G67AYI6UDV5B2JZTBCKIDX/",
        "https://lists.fedoraproject.org/archives/list/package- announce@lists.fedoraproject.org/message/K7HNVIFMETMFWWWUNTB72KYJYXCZOS5V/",
        "https://lists.fedoraproject.org/archives/list/package- announce@lists.fedoraproject.org/message/ZBTGPBUABGXZ7WH7677OEM3NSP6ZEA76/",
        "https://python-security.readthedocs.io/vuln/cookie-domain-check.html",
        "https://usn.ubuntu.com/4127-1/",
        "https://usn.ubuntu.com/4127-2/"
    ],
    "flaw": {
        "phase": "exploitation",
        "specificity": "N/A",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "python2.7-minimal 2.7.3-6+deb7u2 i386",
        "languages": "python",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-03",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "When a program uses http.cookiejar.DefaultPolicy and tries to do an HTTP connection to an attacker-controlled server, existing cookies can be leaked to the attacker",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade python2.7-minimal",
        "pull-request": "https://github.com/python/cpython/commit/979daae300916adb399ab5b51410b6ebd0888f13",
        "date-mitigation": null
    }
}
```
