### ISSUE TITLE
An issue was discovered in Python through 2.7.16, 3.x through 3.5

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1469]
```yaml
{
    "id": 0,
    "title": "An issue was discovered in Python through 2.7.16, 3.x through 3.5",
    "type": "vulnerability",
    "description": "An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.",
    "cwe": "CWE-20",
    "cve": "CVE-2019-16056",
    "keywords": [
        "Python"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 8.7,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:T/S:U/C:H/I:N/A:N/H:N",
        "severity-description": "high",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-16056",
        "https://access.redhat.com/errata/RHSA-2019:3725",
        "https://access.redhat.com/errata/RHSA-2019:3948",
        "https://bugs.python.org/issue34155",
        "https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9",
        "https://lists.debian.org/debian-lts-announce/2019/09/msg00018.html",
        "https://lists.debian.org/debian-lts-announce/2019/09/msg00019.html"
    ],
    "flaw": {
        "phase": "exploitation",
        "specificity": "N/A",
        "architectural-location": "application-specific",
        "application": "email.utils.parseaddr",
        "subsystem": "N/A",
        "package": "python2.7-minimal 2.7.3-6+deb7u2 i386",
        "languages": "python",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-03",
        "reported-by": "Cyril Nicod\u00e8me (Original bug), Alias Robotics S.L.",
        "reported-by-relationship": "Security researcher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade python2.7-minimal",
        "pull-request": "https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9",
        "date-mitigation": null
    }
}
```
