### ISSUE TITLE
RVD#147: test_communication: detected memory leaks, rosidl_generator_...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#147]
```yaml
{
    "id": 147,
    "title": "RVD#147: test_communication: detected memory leaks, rosidl_generator_...",
    "type": "weakness",
    "description": "Issue detected while running Address Sanitizer (ASan).\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "package: test_communication",
        "robot component: ROS2",
        "robot component: moveit2",
        "weakness"
    ],
    "system": "moveit2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/147"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "Wed, 31 Jul 2019 12:32:42 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Wed, 31 Jul 2019 12:32:42 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/147",
        "reproducibility": "",
        "trace": "#0 0x7fd396d6df40 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdef40) 
#1 0x7fd3965c8f75 in rosidl_generator_c__String__assignn /opt/ros2_asan_ws/src/ros2/rosidl/rosidl_generator_c/src/string_functions.c:85 
#2 0x7fd3965c90af in rosidl_generator_c__String__assign /opt/ros2_asan_ws/src/ros2/rosidl/rosidl_generator_c/src/string_functions.c:101 
#3 0x7fd3961882d2 in test_msgs__msg__Arrays__init /opt/ros2_asan_ws/build-asan/test_msgs/rosidl_generator_c/test_msgs/msg/arrays__functions.c:130 
#4 0x7fd39618c082 in test_msgs__msg__MultiNested__init /opt/ros2_asan_ws/build-asan/test_msgs/rosidl_generator_c/test_msgs/msg/multi_nested__functions.c:34 
#5 0x5614e934c054 in void get_message<test_msgs__msg__MultiNested>(test_msgs__msg__MultiNested*, unsigned long) /opt/ros2_asan_ws/src/ros2/system_tests/test_communication/test/test_messages_c.cpp:1197 
#6 0x5614e9399d75 in void TestMessagesFixture::test_message_type<test_msgs__msg__MultiNested>(char const*, rosidl_message_type_support_t const*, rcl_context_t*) (/opt/ros2_asan_ws/build-asan/test_communication/test_messages_c__rmw_fastrtps_dynamic_cpp+0x80d75) 
#7 0x5614e934ca96 in TestMessagesFixture_test_multi_nested_Test::TestBody() /opt/ros2_asan_ws/src/ros2/system_tests/test_communication/test/test_messages_c.cpp:1266 
#8 0x5614e941e419 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447 
#9 0x5614e94102ff in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483 
#10 0x5614e93bc067 in testing::Test::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2522 
#11 0x5614e93bd492 in testing::TestInfo::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2703 
#12 0x5614e93be036 in testing::TestCase::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2825 
#13 0x5614e93d9147 in testing::internal::UnitTestImpl::RunAllTests() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:5216 
#14 0x5614e9420ecc in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447 
#15 0x5614e94125c8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483 
#16 0x5614e93d5edb in testing::UnitTest::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:4824 
#17 0x5614e93a942a in RUN_ALL_TESTS() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:2370 
#18 0x5614e93a9370 in main /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc:36 #19 0x7fd3955ecb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
