### ISSUE TITLE
RVD#1481: The makecontext function in the GNU C Library (aka glibc or libc6) before 2.25 creates execution contexts incompatible with the unwinder on ARM EABI (32-bit) platforms, which might allow context-dependent attackers to cause a denial of service.

### ISSUE THREAD

**Issue by mikekaram** [aliasrobotics/RVD#1481]
```yaml
{
    "id": 1481,
    "title": "RVD#1481: The makecontext function in the GNU C Library (aka glibc or libc6) before 2.25 creates execution contexts incompatible with the unwinder on ARM EABI (32-bit) platforms, which might allow context-dependent attackers to cause a denial of service.",
    "type": "vulnerabitity",
    "description": "The makecontext function in the GNU C Library (aka glibc or libc6) before 2.25 creates execution contexts incompatible with the unwinder on ARM EABI (32-bit) platforms, which might allow context-dependent attackers to cause a denial of service (hang), as demonstrated by applications compiled using gccgo, related to backtrace generation.",
    "cwe": "CWE-284",
    "cve": "CVE-2016-6323",
    "keywords": [
        "Universal Robots",
        "manipulation",
        "cobot",
        "CB 3.x"
    ],
    "system": "Universal Robots Robot Controllers CB 3.x",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 7.5,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:U/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "high",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-6323",
        "https://github.com/aliasrobotics/RVD/issues/1481"
    ],
    "flaw": {
        "phase": "explotation",
        "specificity": "N/A",
        "architectural-location": "internal",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "libc6 2.19-11 i386",
        "languages": "C",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-03",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "security researcher",
        "issue": "https://github.com/aliasrobotics/RVD/issues/1481",
        "reproducibility": "always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "Denial of service can be caused due to a incompatibility with 32bit EABI.",
        "exploitation-image": "Not avialable",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libc6",
        "pull-request": null,
        "date-mitigation": null
    }
}
```
