### ISSUE TITLE
Improper Handling of Unicode Encoding during NFKC normalization on python 2.7.x through 2.7.16 and 3.x through 3.7.2

### ISSUE THREAD

**Issue by glerapic** [aliasrobotics/RVD#1492]
```yaml
{
    "id": 0,
    "title": "Improper Handling of Unicode Encoding during NFKC normalization on python 2.7.x through 2.7.16 and 3.x through 3.7.2",
    "type": "vulnerability",
    "description": "Python 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are urllib.parse.urlsplit, urllib.parse.urlparse.",
    "cwe": "CWE-255",
    "cve": "CVE-2019-9636",
    "keywords": [
        "Python"
    ],
    "system": "URx",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 10.0,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:T/S:U/C:H/I:H/A:N/H:N",
        "severity-description": "critical",
        "cvss-score": 9.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-9636",
        "http://www.securityfocus.com/bid/107400",
        "https://access.redhat.com/errata/RHSA-2019:3170",
        "https://bugs.python.org/issue36216",
        "https://github.com/python/cpython/pull/12201",
        "https://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html",
        "https://usn.ubuntu.com/4127-1/",
        "https://usn.ubuntu.com/4127-2/"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "application-specific",
        "application": "python",
        "subsystem": "N/A",
        "package": "python2.7-minimal 2.7.3-6+deb7u2 i386",
        "languages": "None",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-03",
        "reported-by": "Laura Pardo (original bug), Alias Robotics S.L.",
        "reported-by-relationship": "Security Reasercher",
        "issue": null,
        "reproducibility": "Always",
        "trace": "N/A",
        "reproduction": "Not available",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly.",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade python2.7-minimal",
        "pull-request": "https://github.com/python/cpython/pull/12201",
        "date-mitigation": null
    }
}
```
