### ISSUE TITLE
The function `read_data()` in security.c in curl is vulnerable to memory double free.

### ISSUE THREAD

**Issue by mikekaram** [aliasrobotics/RVD#1496]
```yaml
{
    "id": 0,
    "title": "The function `read_data()` in security.c in curl is vulnerable to memory double free.",
    "type": "vulnerability",
    "description": "The function `read_data()` in security.c in curl before version 7.51.0 is vulnerable to memory double free.",
    "cwe": "CWE-415",
    "cve": "CVE-2016-8619",
    "keywords": [
        "Universal Robots",
        "manipulation",
        "cobot",
        "CB 3.x"
    ],
    "system": "Universal Robots Robot Controllers CB 3.x",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 10.0,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:T/S:U/C:H/I:H/A:H/H:U",
        "severity-description": "Critical",
        "cvss-score": 10.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-8619"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "N/A",
        "architectural-location": "platform code",
        "application": "libcurl",
        "subsystem": "N/A",
        "package": "libcurl3 7.38.0-4+deb8u13 i386",
        "languages": "C",
        "date-detected": null,
        "detected-by": "Victor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "N/A",
        "date-reported": "2020-04-03",
        "reported-by": "Alias Robotics S.L.",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "always",
        "trace": "N/A",
        "reproduction": "N/A",
        "reproduction-image": "N/A"
    },
    "exploitation": {
        "description": "Remote attackers could conduct a Man-in-the-Middle attack to obtain sensitive information, cause a Denial of Service condition, or execute arbitrary code.",
        "exploitation-image": "N/A",
        "exploitation-vector": "N/A"
    },
    "mitigation": {
        "description": "sudo apt-get --assume-yes install --only-upgrade libcurl3",
        "pull-request": "https://curl.haxx.se/CVE-2016-8619.patch",
        "date-mitigation": null
    }
}
```
