### ISSUE TITLE
RVD#154: test_communication: detected memory leaks, rosidl_generator_...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#154]
```yaml
{
    "id": 154,
    "title": "RVD#154: test_communication: detected memory leaks, rosidl_generator_...",
    "type": "weakness",
    "description": "Issue detected while running Address Sanitizer (ASan).\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "package: test_communication",
        "robot component: ROS2",
        "robot component: moveit2",
        "weakness"
    ],
    "system": "moveit2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/154"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "Wed, 31 Jul 2019 12:32:48 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Wed, 31 Jul 2019 12:32:48 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/154",
        "reproducibility": "",
        "trace": "#0 0x7f1253444b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50) 
#1 0x7f12506bdd56 in rosidl_generator_c__octet__Sequence__init /opt/ros2_asan_ws/src/ros2/rosidl/rosidl_generator_c/src/primitives_sequence_functions.c:68 
#2 0x7f1252d0648d in test_msgs__msg__BoundedSequences__init /opt/ros2_asan_ws/build-asan/test_msgs/rosidl_generator_c/test_msgs/msg/bounded_sequences__functions.c:153 
#3 0x5652f7ea4dbd in TestMessageSerialization_cdr_integrity_Test::TestBody() /opt/ros2_asan_ws/src/ros2/system_tests/test_communication/test/test_message_serialization.cpp:218 
#4 0x5652f7f4ef97 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447 
#5 0x5652f7f4110b in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483 
#6 0x5652f7eed1bf in testing::Test::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2522 
#7 0x5652f7eee5ea in testing::TestInfo::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2703 
#8 0x5652f7eef18e in testing::TestCase::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2825 
#9 0x5652f7f0a29f in testing::internal::UnitTestImpl::RunAllTests() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:5216 
#10 0x5652f7f51944 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447 
#11 0x5652f7f432ba in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483 
#12 0x5652f7f07033 in testing::UnitTest::Run() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:4824 
#13 0x5652f7eda582 in RUN_ALL_TESTS() /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:2370 
#14 0x5652f7eda4c8 in main /opt/ros2_asan_ws/install-asan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc:36 
#15 0x7f1251abbb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
