### ISSUE TITLE
test_security: detected memory leaks, __default_zero_allocat...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#160]
```yaml
{
    "id": 160,
    "title": "test_security: detected memory leaks, __default_zero_allocat...",
    "type": "weakness",
    "description": "Issue detected while running Address Sanitizer (ASan).\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "package: test_security",
        "robot component: ROS2",
        "weakness"
    ],
    "system": "ROS 2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/160"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "Sun, 08 Sep 2019 09:19:50 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Sun, 08 Sep 2019 09:19:50 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/160",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
