### ISSUE TITLE
RVD#165: rcl_action: SEGV on unknown address, rcl_node_is_valid_excep...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#165]
```yaml
{
    "id": 165,
    "title": "RVD#165: rcl_action: SEGV on unknown address, rcl_node_is_valid_excep...",
    "type": "weakness",
    "description": "Issue detected while running Thread Sanitizer (TSan). ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "components software",
        "package: rcl_action",
        "robot component: ROS2",
        "weakness"
    ],
    "system": "ROS 2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/165"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "Tue, 10 Sep 2019 09:34:26 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Tue, 10 Sep 2019 09:34:26 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/165",
        "reproducibility": "",
        "trace": "    #0 0x7ff1f35dfe61 in rcl_node_is_valid_except_context /opt/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:463\r\n    #1 0x7ff1f3845f8d in rcl_action_server_fini /opt/ros2_ws/src/ros2/rcl/rcl_action/src/rcl_action/action_server.c:232\r\n    #2 0x55c667772f1a in TestActionServer::TearDown() (/opt/ros2_ws/build-tsan/rcl_action/test_action_server+0x41f1a)\r\n    #3 0x55c6677f85ab in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447\r\n    #4 0x55c6677ea555 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483\r\n    #5 0x55c667796e43 in testing::Test::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2530\r\n    #6 0x55c6677981e4 in testing::TestInfo::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2703\r\n    #7 0x55c667798d88 in testing::TestCase::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2825\r\n    #8 0x55c6677b3e99 in testing::internal::UnitTestImpl::RunAllTests() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:5216\r\n    #9 0x55c6677fb05e in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447\r\n    #10 0x55c6677ec81e in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483\r\n    #11 0x55c6677b0c2d in testing::UnitTest::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:4824\r\n    #12 0x55c66778417c in RUN_ALL_TESTS() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:2370\r\n    #13 0x55c6677840c2 in main /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc:36\r\n    #14 0x7ff1f25c0b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\r\n    #15 0x55c66774b8a9 in _start (/opt/ros2_ws/build-tsan/rcl_action/test_action_server+0x1a8a9)\r\n\r\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
