### ISSUE TITLE
nav2_costmap_2d: heap-use-after-free on address, __gnu_cxx::...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#172]
```yaml
{
    "id": 172,
    "title": "nav2_costmap_2d: heap-use-after-free on address, __gnu_cxx::...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "0.2.4",
        "components software",
        "package: nav2_costmap_2d",
        "robot component: ROS2",
        "robot component: navigation2",
        "weakness"
    ],
    "system": "navigation2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/172"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "nav2_costmap_2d",
        "languages": "None",
        "date-detected": "Thu, 12 Sep 2019 20:06:33 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Thu, 12 Sep 2019 20:06:33 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/172",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
