### ISSUE TITLE
RVD#229: demo_nodes_cpp_native: detected memory leaks, class_loader::...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#229]
```yaml
{
    "id": 229,
    "title": "RVD#229: demo_nodes_cpp_native: detected memory leaks, class_loader::...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "dashing",
        "package: demo_nodes_cpp_native",
        "robot component: ROS2",
        "weakness"
    ],
    "system": "ros2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/229"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:ros2",
        "package": "demo_nodes_cpp_native",
        "languages": "None",
        "date-detected": "Thu, 19 Sep 2019 08:24:52 +0000",
        "detected-by": "",
        "detected-by-method": "testing dynamic",
        "date-reported": "Thu, 19 Sep 2019 08:24:52 +0000",
        "reported-by": "Alias Robotics (http://aliasrobotics.com)",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/229",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
