### ISSUE TITLE
demo_nodes_cpp: detected memory leaks, void class_loader::im...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#239]
```yaml
{
    "id": 239,
    "title": "demo_nodes_cpp: detected memory leaks, void class_loader::im...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "dashing",
        "package: demo_nodes_cpp",
        "robot component: ROS2",
        "weakness"
    ],
    "system": "ros2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/239"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:ros2",
        "package": "demo_nodes_cpp",
        "languages": "None",
        "date-detected": "Thu, 19 Sep 2019 08:25:03 +0000",
        "detected-by": "",
        "detected-by-method": "testing dynamic",
        "date-reported": "Thu, 19 Sep 2019 08:25:03 +0000",
        "reported-by": "Alias Robotics (http://aliasrobotics.com)",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/239",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
