### ISSUE TITLE
RVD#291: rcl: lock-order-inversion, eprosima::fastrtps::rtps::Livelin...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#291]
```yaml
{
    "id": 291,
    "title": "RVD#291: rcl: lock-order-inversion, eprosima::fastrtps::rtps::Livelin...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "components software",
        "dashing",
        "package: rcl",
        "robot component: FastRTPS",
        "robot component: ROS2",
        "vendor: eProsima",
        "weakness"
    ],
    "system": "ros2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/291"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:ros2",
        "package": "rcl",
        "languages": "None",
        "date-detected": "Thu, 19 Sep 2019 10:41:50 +0000",
        "detected-by": "",
        "detected-by-method": "testing dynamic",
        "date-reported": "Thu, 19 Sep 2019 10:41:50 +0000",
        "reported-by": "Alias Robotics (http://aliasrobotics.com)",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/291",
        "reproducibility": "",
        "trace": " #0 pthread_mutex_lock <null> (libtsan.so.0+0x3fadb) #1 __gthread_mutex_lock /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:748 (libfastrtps.so.1+0x1c5c0b) #2 std::mutex::lock() /usr/include/c++/7/bits/std_mutex.h:103 (libfastrtps.so.1+0x1c5c0b) #3 std::unique_lock<std::mutex>::lock() /usr/include/c++/7/bits/std_mutex.h:267 (libfastrtps.so.1+0x1c5c0b) #4 std::unique_lock<std::mutex>::unique_lock(std::mutex&) /usr/include/c++/7/bits/std_mutex.h:197 (libfastrtps.so.1+0x1c5c0b) #5 eprosima::fastrtps::rtps::LivelinessManager::assert_liveliness(eprosima::fastrtps::rtps::GUID_t, eprosima::fastrtps::LivelinessQosPolicyKind, eprosima::fastrtps::Time_t) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/writer/LivelinessManager.cpp:137 (libfastrtps.so.1+0x1c5c0b) #6 eprosima::fastrtps::rtps::WLP::assert_liveliness(eprosima::fastrtps::rtps::GUID_t, eprosima::fastrtps::LivelinessQosPolicyKind, eprosima::fastrtps::Time_t) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/builtin/liveliness/WLP.cpp:870 (libfastrtps.so.1+0x56cb97) #7 eprosima::fastrtps::rtps::StatelessWriter::unsent_change_added_to_history(eprosima::fastrtps::rtps::CacheChange_t*, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/writer/StatelessWriter.cpp:204 (libfastrtps.so.1+0x1f80db) #8 eprosima::fastrtps::rtps::WriterHistory::add_change_(eprosima::fastrtps::rtps::CacheChange_t*, eprosima::fastrtps::rtps::WriteParams&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/history/WriterHistory.cpp:106 (libfastrtps.so.1+0x21102f) #9 eprosima::fastrtps::PublisherHistory::add_pub_change(eprosima::fastrtps::rtps::CacheChange_t*, eprosima::fastrtps::rtps::WriteParams&, std::unique_lock<std::recursive_timed_mutex>&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/publisher/PublisherHistory.cpp:99 (libfastrtps.so.1+0x2f3234) #10 eprosima::fastrtps::PublisherImpl::create_new_change_with_params(eprosima::fastrtps::rtps::ChangeKind_t, void*, eprosima::fastrtps::rtps::WriteParams&) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/publisher/PublisherImpl.cpp:230 (libfastrtps.so.1+0x2dd004) #11 eprosima::fastrtps::PublisherImpl::create_new_change(eprosima::fastrtps::rtps::ChangeKind_t, void*) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/publisher/PublisherImpl.cpp:124 (libfastrtps.so.1+0x2e05b2) #12 eprosima::fastrtps::Publisher::write(void*) /opt/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/publisher/Publisher.cpp:39 (libfastrtps.so.1+0x2d73cc) #13 rmw_fastrtps_shared_cpp::__rmw_publish(char const*, rmw_publisher_t const*, void const*, rmw_publisher_allocation_t*) /opt/ros2_ws/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/rmw_publish.cpp:51 (librmw_fastrtps_shared_cpp.so+0x447a7) #14 rmw_publish /opt/ros2_ws/src/ros2/rmw_fastrtps/rmw_fastrtps_dynamic_cpp/src/rmw_publish.cpp:35 (librmw_fastrtps_dynamic_cpp.so+0x1fa66) #15 rcl_publish /opt/ros2_ws/src/ros2/rcl/rcl/src/rcl/publisher.c:256 (librcl.so+0x21179) #16 TestEventFixture__rmw_fastrtps_dynamic_cpp_test_pubsub_liveliness_kill_pub_Test::TestBody() /opt/ros2_ws/src/ros2/rcl/rcl/test/rcl/test_events.cpp:493 (test_events__rmw_fastrtps_dynamic_cpp+0xfd66) #17 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447 (test_events__rmw_fastrtps_dynamic_cpp+0x56a27) #18 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483 (test_events__rmw_fastrtps_dynamic_cpp+0x56a27) #19 testing::Test::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2522 (test_events__rmw_fastrtps_dynamic_cpp+0x45286) #20 testing::TestInfo::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2703 (test_events__rmw_fastrtps_dynamic_cpp+0x4566d) #21 testing::TestCase::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2825 (test_events__rmw_fastrtps_dynamic_cpp+0x45922) #22 testing::internal::UnitTestImpl::RunAllTests() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:5216 (test_events__rmw_fastrtps_dynamic_cpp+0x45f85) #23 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2447 (test_events__rmw_fastrtps_dynamic_cpp+0x57143) #24 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:2483 (test_events__rmw_fastrtps_dynamic_cpp+0x57143) #25 testing::UnitTest::Run() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/./src/gtest.cc:4824 (test_events__rmw_fastrtps_dynamic_cpp+0x46575) #26 RUN_ALL_TESTS() /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:2370 (test_events__rmw_fastrtps_dynamic_cpp+0xa02a) #27 main /opt/ros2_ws/install-tsan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc:36 (test_events__rmw_fastrtps_dynamic_cpp+0xa02a)",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
