### ISSUE TITLE
rcl_action: data race, eprosima::fastrtps::rtps::WriterProxy...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#298]
```yaml
{
    "id": 298,
    "title": "rcl_action: data race, eprosima::fastrtps::rtps::WriterProxy...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "components software",
        "dashing",
        "package: rcl_action",
        "robot component: FastRTPS",
        "robot component: ROS2",
        "vendor: eProsima",
        "weakness"
    ],
    "system": "ros2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/298"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:ros2",
        "package": "rcl_action",
        "languages": "None",
        "date-detected": "Thu, 19 Sep 2019 10:41:55 +0000",
        "detected-by": "",
        "detected-by-method": "testing dynamic",
        "date-reported": "Thu, 19 Sep 2019 10:41:55 +0000",
        "reported-by": "Alias Robotics (http://aliasrobotics.com)",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/298",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
