### ISSUE TITLE
RVD#3: Rovio improper implemented authentication

### ISSUE THREAD

**Issue by aliasbot** [aliasrobotics/RVD#3]
```yaml
{
    "id": 3,
    "title": "RVD#3: Rovio improper implemented authentication",
    "type": "vulnerability",
    "description": " Improper implemented authentication mechanisms in WowWee Rovio could allow local network attackers to access sensitive information via web access to unsecure WebUI resources.On version 4.7b.201\r\n Credits to: Brian Dowling of Simplicity Communications disclosed this vulnerability to WowWee.",
    "cwe": "CWE-Missing Authorization (CWE-862)",
    "cve": "None",
    "keywords": [
        "malformed",
        "robot",
        "robot: Rovio",
        "severity: critical",
        "state: new",
        "vendor: WowWee",
        "vulnerability"
    ],
    "system": "Rovio",
    "vendor": "WowWee",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "RVSS:1.0/AV:RN/AC:L/PR:N/UI:N/Y:M/S:U/C:H/I:N/A:N/H:N",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/3"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2009-01-06",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2009-01-06",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/3",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
