### ISSUE TITLE
RVD#303: message_filters: data race, eprosima::fastrtps::rtps::UDPCha...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#303]
```yaml
{
    "id": 303,
    "title": "RVD#303: message_filters: data race, eprosima::fastrtps::rtps::UDPCha...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "components software",
        "dashing",
        "package: message_filters",
        "robot component: FastRTPS",
        "robot component: ROS2",
        "vendor: eProsima",
        "weakness"
    ],
    "system": "ros2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/303"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:ros2",
        "package": "message_filters",
        "languages": "None",
        "date-detected": "Thu, 19 Sep 2019 10:41:59 +0000",
        "detected-by": "",
        "detected-by-method": "testing dynamic",
        "date-reported": "Thu, 19 Sep 2019 10:41:59 +0000",
        "reported-by": "Alias Robotics (http://aliasrobotics.com)",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/303",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
