### ISSUE TITLE
RVD#329: tf2_ros: detected memory leaks, ServiceListener::onNewDataMe...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#329]
```yaml
{
    "id": 329,
    "title": "RVD#329: tf2_ros: detected memory leaks, ServiceListener::onNewDataMe...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "components software",
        "dashing",
        "package: tf2_ros",
        "robot component: ROS2",
        "weakness"
    ],
    "system": "ros2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/329"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:ros2",
        "package": "tf2_ros",
        "languages": "None",
        "date-detected": "Fri, 20 Sep 2019 08:42:17 +0000",
        "detected-by": "",
        "detected-by-method": "testing dynamic",
        "date-reported": "Fri, 20 Sep 2019 08:42:17 +0000",
        "reported-by": "Alias Robotics (http://aliasrobotics.com)",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/329",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
