### ISSUE TITLE
nav2_util: detected memory leaks, __default_reallocate 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#333]
```yaml
{
    "id": 333,
    "title": "nav2_util: detected memory leaks, __default_reallocate ",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "CWE-[CWE-401: Missing Release of Memory after Effective Lifetime](https://cwe.mitre.org/data/definitions/401.html)",
    "cve": "None",
    "keywords": [
        "0.2.4",
        "components software",
        "mitigated",
        "package: nav2_util",
        "package: rcl",
        "quality",
        "robot component: ROS2",
        "robot component: navigation2",
        "weakness"
    ],
    "system": "navigation2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/333"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "nav2_util",
        "languages": "None",
        "date-detected": "Fri, 20 Sep 2019 09:34:23 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Fri, 20 Sep 2019 09:34:23 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/333",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
