### ISSUE TITLE
nav2_util: data race, hash_map_find 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#345]
```yaml
{
    "id": 345,
    "title": "nav2_util: data race, hash_map_find ",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "0.2.4",
        "components software",
        "package: nav2_util",
        "robot component: ROS2",
        "robot component: navigation2",
        "weakness"
    ],
    "system": "navigation2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/345"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "nav2_util",
        "languages": "None",
        "date-detected": "Sat, 21 Sep 2019 18:33:21 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Sat, 21 Sep 2019 18:33:21 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/345",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
