### ISSUE TITLE
RVD#35: Pepper's head plastic lid can be easily removed to access the LAN port

### ISSUE THREAD

**Issue by aliasbot** [aliasrobotics/RVD#35]
```yaml
{
    "id": 35,
    "title": "RVD#35: Pepper's head plastic lid can be easily removed to access the LAN port",
    "type": "vulnerability",
    "description": "Pepper's head plastic lid can be easily removed to access the LAN port. Port allows access to robot network services.Access to robot's network services can be achieved through these ports. Connecting an Ethernet cable allows sending commands/messages to robot services that are available through this interface. Credits to: Cesar Cerrudo and Lucas Apa from IOActive",
    "cwe": "CWE-Command Injection - Generic (CWE-77)",
    "cve": "None",
    "keywords": [
        "malformed",
        "robot",
        "robot: Pepper",
        "severity: high",
        "state: new",
        "vendor: SoftBank Robotics",
        "vulnerability"
    ],
    "system": "Pepper",
    "vendor": "SoftBank Robotics",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "RVSS:1.0/AV:PP/AC:H/PR:N/UI:N/Y:T/S:U/C:N/I:H/A:N/H:H",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/35"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2017-03-01",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2017-03-01",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/35",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
