### ISSUE TITLE
RVD#374: nav2_recoveries: unlock of an unlocked mutex, nav2_util::Sim...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#374]
```yaml
{
    "id": 374,
    "title": "RVD#374: nav2_recoveries: unlock of an unlocked mutex, nav2_util::Sim...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "0.2.4",
        "components software",
        "package: nav2_recoveries",
        "robot component: ROS2",
        "robot component: navigation2",
        "weakness"
    ],
    "system": "navigation2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/374"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "nav2_recoveries",
        "languages": "None",
        "date-detected": "Mon, 23 Sep 2019 07:01:30 +0000",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Mon, 23 Sep 2019 07:01:30 +0000",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/374",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
