### ISSUE TITLE
RVD#445: rclcpp, UBSAN: runtime error publisher_options.hpp

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#445]
```yaml
{
    "id": 445,
    "title": "RVD#445: rclcpp, UBSAN: runtime error publisher_options.hpp",
    "type": "weakness",
    "description": "",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "malformed",
        "package: rclcpp",
        "robot component: ROS2",
        "weakness"
    ],
    "system": null,
    "vendor": null,
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/445"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/445",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
