### ISSUE TITLE
RVD#448: Misuse of fnmatch used by DDS Security Access Control 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#448]
```yaml
{
    "id": 448,
    "title": "RVD#448: Misuse of fnmatch used by DDS Security Access Control ",
    "type": "weakness",
    "description": "The two-way fnmatch implementation allows for remote data readers/writers to use the topic name string as the expression to pattern match against its respective permissions. Further details available at https://github.com/eProsima/Fast-RTPS/issues/441",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "components software",
        "malformed",
        "robot component: FastRTPS",
        "robot component: ROS2",
        "vendor: eProsima",
        "weakness"
    ],
    "system": null,
    "vendor": null,
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/448",
        "https://github.com/eProsima/Fast-RTPS/issues/441",
        "https://github.com/eProsima/Fast-RTPS/pull/442"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2019-03-08 (00:00)",
        "detected-by": "Ruffin White",
        "detected-by-method": "N/A",
        "date-reported": "2019-10-07 (00:00)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "security researcher",
        "issue": "https://github.com/aliasrobotics/RVD/issues/448",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
