### ISSUE TITLE
rcl: data race, eprosima::fastrtps::rtps::PDPSimple::assignR...

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#456]
```yaml
{
    "id": 456,
    "title": "rcl: data race, eprosima::fastrtps::rtps::PDPSimple::assignR...",
    "type": "weakness",
    "description": "Issue detected while running Google Sanitizers.\n\n ",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "components software",
        "master",
        "package: rcl",
        "robot component: ROS2",
        "weakness"
    ],
    "system": "ros2",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/456"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:ros2",
        "package": "rcl",
        "languages": "None",
        "date-detected": "Sat, 19 Oct 2019 12:08:23 +0000",
        "detected-by": "",
        "detected-by-method": "testing dynamic",
        "date-reported": "Sat, 19 Oct 2019 12:08:23 +0000",
        "reported-by": "Alias Robotics (http://aliasrobotics.com)",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/456",
        "reproducibility": "always",
        "trace": null,
        "reproduction": "Find a    pre-compiled environment in the Docker image below. Reproducing it implies    source the workspace, finding the appropriate test and executing it.",
        "reproduction-image": "registry.gitlab.com/aliasrobotics/offensive/alurity/ros2/ros2:build-tsan2-commit-b2dca472a35109cece17d3e61b18af5cb9be5772"
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
