### ISSUE TITLE
RVD#511: OpenSplice community data race condition on x86

### ISSUE THREAD

**Issue by LanderU** [aliasrobotics/RVD#511]
```yaml
{
    "id": 511,
    "title": "RVD#511: OpenSplice community data race condition on x86",
    "type": "weakness",
    "description": "\r\nFirst report and description: ADLINK-IST/opensplice#102",
    "cwe": "CWE-362",
    "cve": "None",
    "keywords": [
        "components software",
        "robot component: DDS",
        "vendor: ADLINK",
        "weakness"
    ],
    "system": "robot component",
    "vendor": "ADLINK",
    "severity": {
        "rvss-score": "None",
        "rvss-vector": "N/A",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/511"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/511",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": "None"
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
