### ISSUE TITLE
Missing tcpclient lock

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#513]
```yaml
{
    "id": 513,
    "title": "Missing tcpclient lock",
    "type": "weakness",
    "description": "The \"MAVConnTCPServer::client_closed\" method is responsible for safely closing a given client's connection to the TCP server. In the buggy implementation of this method, the lock for the client (represented as a pointer to an MAVConnTCPClient instance) was not acquired before closing the connection, leading to a possible race condition that can result in deadlocking or a segmentation fault.\n",
    "cwe": "CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition') #RESOURCE",
    "cve": "None",
    "keywords": [
        "client deletion",
        "tcp"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/513"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: missing lock",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-07-31 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/513",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "1f019166ccedf8ce5151944f5e33302afaf82679",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "src/mavconn/mavconn_tcp.cpp",
            "include/mavros/mavconn_tcp.h"
        ],
        "languages": [
            "C++"
        ],
        "time": "2014-08-04 (11:14)"
    }
}
```
