### ISSUE TITLE
Missing ENU->NED frame conversion in send_attitude_target

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#514]
```yaml
{
    "id": 514,
    "title": "Missing ENU->NED frame conversion in send_attitude_target",
    "type": "weakness",
    "description": "The \"send_attitude_target\" function in \"setpoint_attribute.cpp\" accepts a 3D affine transformation (along with a timestamp), and forwards an attitude target to MAVLink via the lower-level \"send_attitude_target\" in \"setpoint_attribute.cpp\". Amongst other parameters, the lower-level function accepts attitude as a size 4 array of floats, representing a quaternion. The (buggy) higher-level function converts the affine transformation to a quarternion in the ENU frame, but fails to convert the resulting quaternion to the NED frame expected by the lower-level frame.\n",
    "cwe": "Missing Frame Conversion (no CWE); possibly CWE-137?",
    "cve": "None",
    "keywords": [
        "incorrect argument",
        "frame conversion"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/514"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "UNCLEAR",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "N/A",
        "detected-by-method": "N/A",
        "date-reported": "unreported",
        "reported-by": "unreported",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/514",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "248cb389b122fa94a68578a48e50d4f240df4629",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/setpoint_attitude.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-07-28 (18:18)"
    }
}
```
