### ISSUE TITLE
Incorrect parameter names used to fetch values

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#515]
```yaml
{
    "id": 515,
    "title": "Incorrect parameter names used to fetch values",
    "type": "weakness",
    "description": "Lines 311--313 are used to fetch the current x, y, and z coordinates. The \"ros::NodeHandle::param\" function used to fetch these values accepts the name of a parameter, a reference to the variable to which its value should be written, and a default value which should be written to the variable in the case that no parameter can be found that matches the given name. Lines 312 and 313 incorrectly retrieve the \"sensor_position/x\" parameter, rather than the \"sensor_position/y\" and \"sensor_position/z\" parameters.\n",
    "cwe": "CWE-628: Function Call with Incorrectly Specified Arguments",
    "cve": "None",
    "keywords": [
        "bad (string) parameter name"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/515"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: incorrect parameter name",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/515",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "ff581a0752107f7ad875c16f83f7b75ccd92f847",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros_extras/src/plugins/distance_sensor.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-05-17 (03:28)"
    }
}
```
