### ISSUE TITLE
Incorrect argument name and positional->keyword argument

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#516]
```yaml
{
    "id": 516,
    "title": "Incorrect argument name and positional->keyword argument",
    "type": "weakness",
    "description": "This commit fixes two bugs in the \"mavros/scripts/mavcmd\" script:\nThe first bug is on lines 278 and 279. These lines implement '-e' and '-d' command-line flags, which are used to enable and disable the camera trigger. The buggy version of these lines incorrectly saves the state of these flags to the \"enable\" attribute of the arguments object. The code which handles the state of this flag is on line 191, and expects the flag to be saved to \"trigger_enable\".\nThe second bug is on line 191. The buggy implementation incorrectly passes the state of the \"trigger_enable\" flag to \"command.trigger_control\" as its first (and only) positional argument. The \"command.trigger_control\" function expects the flag to be passed as its \"trigger_enable\" argument.\n",
    "cwe": "CWE-628: Function Call with Incorrectly Specified Arguments",
    "cve": "None",
    "keywords": [
        "positional-to-keyword",
        "bad parameter name"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/516"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "general issue: positional to keyword | bad parameter name",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/516",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "564f935bc1ddd6c7849923a647ebd3828cde99f0",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/scripts/mavcmd"
        ],
        "languages": [
            "Python"
        ],
        "time": "2015-06-16 (17:42)"
    }
}
```
