### ISSUE TITLE
Arithmetic error in reporting of TCP I/O statistics

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#517]
```yaml
{
    "id": 517,
    "title": "Arithmetic error in reporting of TCP I/O statistics",
    "type": "weakness",
    "description": "An assignment operator is incorrectly used instead of addition assignment during the reporting of TCP I/O statistics. Only the statistics for the last client in `client_list` will be reported, rather than the statistics for all of the clients in `client_list`.\n",
    "cwe": "CWE-480: Use of Incorrect Operator",
    "cve": "None",
    "keywords": [
        "typo"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/517"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "MAVCONN library",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-06-28 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/517",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "1a746c326c49c0c265e01556bd4da45dadeacaa7",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "libmavconn/src/tcp.cpp"
        ],
        "languages": "C++",
        "time": "2016-06-28 (18:38)"
    }
}
```
