### ISSUE TITLE
Missing mavros dependency

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#518]
```yaml
{
    "id": 518,
    "title": "Missing mavros dependency",
    "type": "weakness",
    "description": "Missing list of dependency for \"gcs_bridge\" in \"CMakeLists.txt\"\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing dependencies"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/518"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue: missing dependency",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/518",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "942eb3b173b97c66c8cb8df213acf01d32642002",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2014-11-02 (00:00)"
    }
}
```
