### ISSUE TITLE
Missing bounds checking code in legacy mode

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#519]
```yaml
{
    "id": 519,
    "title": "Missing bounds checking code in legacy mode",
    "type": "weakness",
    "description": "The \"UAS::orientation_from_str\" function accepts a string that gives the name of one of 39 pre-defined orientations (e.g., \"NONE\", \"YAW_45\", \"ROLL_90_PITCH_90\"), and returns an integer, giving the index of the corresponding OrientationPair object for that orientation (stored in the \"sensor_orientations\" array). The function is also intended to implement a fallback behaviour (for legacy code that operates using indices directly, instead of indirectly via strings) for cases in which the string does not match one of the pre-defined orientations. This fallback behaviour attempts to convert the string to an integer and returns the result. In cases where the string encodes a legal index, this behaviour operates as intended. However, the buggy implementation fails to account for cases where the string can be converted to an integer, but that integer does not represent a legal index (i.e., 0 <= i < 39). The bug fix introduces error checking code that ensures that the integer is within the expected range, and if not, it reports an error to ROS and returns -1, indicating failure.\nNote, a test case is added to \"mavros/test/test_sensor_orientation.cpp\" to demonstrate this bug.\n",
    "cwe": "CWE-20: Improper Input Validation",
    "cve": "None",
    "keywords": [
        "missing input validation"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/519"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "UNCLEAR",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": "C++",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/519",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "4fb6e7e8190145ba6fa49fa6e13cc49730885b7f",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/lib/uas_sensor_orientation.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-08-02 (13:13)"
    }
}
```
