### ISSUE TITLE
Incorrect ROS parameter names used throughout a file

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#520]
```yaml
{
    "id": 520,
    "title": "Incorrect ROS parameter names used throughout a file",
    "type": "weakness",
    "description": "All ROS parameter interactions within \"mavros/src/plugins/sys_time.cpp\" use an older name for each parameter. Following a refactoring of the source code, namespaces were introduced to separate these parameters (e.g., \"conn_system_time\" -> \"conn/system_time\"). Since \"ros::NodeHandle::param\" -- the function used to fetch parameter values -- returns a default value when no parameter matching the given name is found, this regression goes undetected.\n",
    "cwe": "CWE-628: Function Call with Incorrectly Specified Arguments #EVOLUTION",
    "cve": "None",
    "keywords": [
        "API change",
        "incorrect parameter name",
        "namespace issue"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/520"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: outdated API calls",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-02-03 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/520",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "e1a80052fbdb8324573c8cce0401b01aa78765ae",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/sys_time.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-03-11 (10:27)"
    }
}
```
