### ISSUE TITLE
Incorrect topic name used to fetch GPS information

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#521]
```yaml
{
    "id": 521,
    "title": "Incorrect topic name used to fetch GPS information",
    "type": "weakness",
    "description": "Following changes to MAVROS, the name of the \"gps\" topic was renamed to \"global_position\". The buggy function, \"_find_gps_topic\", continues to use the older, incorrect name of the \"gps\" topic.\n",
    "cwe": "Incorrect (String-Based) Parameter Name (no CWE) #EVOLUTION",
    "cve": "None",
    "keywords": [
        "topic path"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/521"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/521",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "263650d6c1a9c9aebc6b8a0e3ea4627e59c58a77",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/scripts/mavcmd"
        ],
        "languages": [
            "Python"
        ],
        "time": "2015-08-03 (22:23)"
    }
}
```
