### ISSUE TITLE
Typo in include headers

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#522]
```yaml
{
    "id": 522,
    "title": "Typo in include headers",
    "type": "weakness",
    "description": "Include headers were incorrectly stated. Quotation marks were used instead of \"<>\", causing compilation errors.\n",
    "cwe": "Wrong Inclusion Directive (no CWE)",
    "cve": "None",
    "keywords": [
        "incorrect headers"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/522"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue (typo)",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/522",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "101c09b7047eac18a2d9989b09c5916181a49cd5",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "test/test_mavconn.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2014-06-30 (21:42)"
    }
}
```
