### ISSUE TITLE
Redundant (static) array entry for removed sensor

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#523]
```yaml
{
    "id": 523,
    "title": "Redundant (static) array entry for removed sensor",
    "type": "weakness",
    "description": "The \"mavros/src/lib/sensor_orientation.cpp\" file defines a static array of sensor orientations (\"sensor_or\").  A list of the names of these 39 sensor orientations can be found in \"mavros/src/lib/uas_sensor_orientation.cpp\". The static array in \"mavros/src/lib/sensor_orientation.cpp\" contains a redundant entry for a sensor that no longer exists. The fix to this \"bug\" removes this entry and decreases the size of the array, reported by MAV_SENSOR_ORIENTATION_MAX.\n",
    "cwe": "CWE-561: Dead Code",
    "cve": "None",
    "keywords": "redundant array entry",
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/523"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue: redundant array entry",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/523",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "7c6514d3d5ec3c9f75b32db9054d468c49dbdfe8",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/lib/sensor_orientation.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-05-21 (07:55)"
    }
}
```
