### ISSUE TITLE
Incorrect use of namespacing in ROS parameter names

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#524]
```yaml
{
    "id": 524,
    "title": "Incorrect use of namespacing in ROS parameter names",
    "type": "weakness",
    "description": "All ROS parameter interactions within \"mavros_extras/src/plugins/visualization.cpp\" incorrectly prefix the name of parameters with a \"visualization\" namespace. This namespace is implicit, and so the fully qualified parameter that result are incorrect. e.g., \"visualization/fixed_frame_id\" becomes \"/visualization/visualization/fixed_frame_id\" when fully qualified.\n",
    "cwe": "Incorrect use of ROS namespacing (no CWE) #EVOLUTION",
    "cve": "None",
    "keywords": [
        "API change",
        "incorrect parameter name",
        "namespace issue"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/524"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "general issue: incorrect parameter name",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-02-03 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/524",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "84264f01aeea79b345fe9f397da8c4759b7846fb",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros_extras/src/plugins/visualization.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-03-05 (00:00)"
    }
}
```
