### ISSUE TITLE
Missing parameter in ROS service call

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#525]
```yaml
{
    "id": 525,
    "title": "Missing parameter in ROS service call",
    "type": "weakness",
    "description": "The \"do_long\" function in the \"mavcmd\" script accepts an object that describes a MAVLink command.  Command objects are supplied with seven arguments, which may be used or ignored by the command handler depending on the type of command. The \"do_long\" function dispatches this command object to the \"mavros.command.long\" function. which forwards the command to MAVLink. Rather than accepting positional arguments, the \"mavros.command.long\" accepts all of its arguments as keywords. Missing keywords are assumed to be irrelevant and substituted by a nominal placeholder value.\nThe buggy implementation of this function fails to pass along the seventh argument during the call to \"mavros.command.long\", causing incorrect information to be forwarded to MAVLink. This bug will only manifest for commands which utilise all seven arguments.\n",
    "cwe": "CWE-628: Function Call with Incorrectly Specified Arguments",
    "cve": "None",
    "keywords": [
        "missing argument",
        "service call"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/525"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: missing a keyword argument (to a ROS service call)",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/525",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "c6791f0f232e85f51cbb9e12d32f791588f5c93a",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/scripts/mavcmd"
        ],
        "languages": [
            "Python"
        ],
        "time": "2015-12-04 (23:20)"
    }
}
```
