### ISSUE TITLE
Incorrect name of class used to register plugin

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#526]
```yaml
{
    "id": 526,
    "title": "Incorrect name of class used to register plugin",
    "type": "weakness",
    "description": "An incorrect name, \"SetpointActuatorControlPlugin\", was used to export the \"ActuatorControlPlugin\" class as a MAVROS plugin.\n",
    "cwe": "Incorrect Class Name (no CWE)",
    "cve": "None",
    "keywords": [
        "incorrect class name"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/526"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue: incorrect parameter name",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/526",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "dab1b8a16d6194056cb7e76215ecf299d1a90f08",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": "mavros/src/plugins/actuator_control.cpp",
        "languages": [
            "C++"
        ],
        "time": "2015-03-01 (01:13)"
    }
}
```
