### ISSUE TITLE
Missing type conversion in u8->hex conversion

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#527]
```yaml
{
    "id": 527,
    "title": "Missing type conversion in u8->hex conversion",
    "type": "weakness",
    "description": "The \"array_to_hex_string\" helper function in \"sys_status.cpp\" accepts an array of uint8_t (along with an argument specifying its size), and returns a hexadecimal string describing the contents of the array. The faulty implementation of this function performs this conversion by passing the raw uint8_t to an ostringstream object; the ostringstream operates on the bits of uint8_t as if it were an int, producing an incorrect result. The fixed version of this function explicitly converts the uint8_t to an int before passing it to the ostringstream.\n",
    "cwe": "CWE-704: Incorrect Type Conversion or Cast",
    "cve": "None",
    "keywords": [
        "type conversion",
        "signedness"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/527"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: missing type conversion",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/527",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "None",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "a67d81d05776a5431e9c0e77f51602ce7987fc7b",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/sys_status.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-06-16 (21:23)"
    }
}
```
