### ISSUE TITLE
Incorrect header installation path

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#528]
```yaml
{
    "id": 528,
    "title": "Incorrect header installation path",
    "type": "weakness",
    "description": "When mavconn was removed from mavros, the install destination for the mavconn headers were not appropriately updated, causing both the 0.9.1 and 0.8.4 builds (of MAVROS) to break.\n",
    "cwe": "Missing Installation Dependencies (no CWE)",
    "cve": "None",
    "keywords": [
        "broken build"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/528"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-11-02 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/528",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "27e7db9d504359d05830fbc9553fd1fd1af3aab2",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": "libmavconn/CMakeLists.txt",
        "languages": [
            "CMake"
        ],
        "time": "2014-11-03 (09:18)"
    }
}
```
