### ISSUE TITLE
Missing assignment during construction of JointState object

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#529]
```yaml
{
    "id": 529,
    "title": "Missing assignment during construction of JointState object",
    "type": "weakness",
    "description": "The \"ServoStatePublisher\" class is used to publish the state of the robot's joints to the \"joint_states\" topic. The \"rc_out_cb\" method is used to describe these states (as sensor_msgs::JointState objects). Following the (implicit) construction of a JointState object (via \"boost::make_shared<sensor_msgs::JointState>();\"), \"rc_out_cb\" assigns appropriate values to each of the fields of this object. However, \"rc_out_cb\" fails to assign a timestamp value to the header of the JointState object. Therefore, any subscribers which rely on this timing information will behave incorrectly.\n",
    "cwe": "CWE-456: Missing Initialization of a Variable #RESOURCE",
    "cve": "None",
    "keywords": [
        "undefined field"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/529"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "UNKNOWN",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-09-16 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/529",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "753226d93a735ba01744620b5654b8a038d1c89d",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros_extras/src/servo_state_publisher.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-09-17 (16:22)"
    }
}
```
