### ISSUE TITLE
Inefficient checking for string emptiness using empty() rather than size()

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#530]
```yaml
{
    "id": 530,
    "title": "Inefficient checking for string emptiness using empty() rather than size()",
    "type": "weakness",
    "description": "This commit performs two small performance/hygiene-related fixes to the code, discovered using the cppcheck static analyser. The first fix replaces code that checks a string is empty by ensuring its length is greater than zero with a call to \".empty()\".\n(The commit also contains a minor optimization: an argument of the \"send_any_path_command\" function has been optimized to now be passed as string by reference, rather than by value.)\n",
    "cwe": "Inefficient use of library function (no CWE)",
    "cve": "None",
    "keywords": [
        "cosmetic",
        "performance"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/530"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "code scanning tool",
        "detected-by-method": "N/A",
        "date-reported": "unreported",
        "reported-by": "unreported",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/530",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "0e2ea0c43b373feb490b45710fb63f4e6cde78eb",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/ftp.cpp"
        ],
        "languages": "C++",
        "time": "2015-07-29 (10:27)"
    }
}
```
