### ISSUE TITLE
Uninitialised variable causes incorrect timestamps to be produced

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#531]
```yaml
{
    "id": 531,
    "title": "Uninitialised variable causes incorrect timestamps to be produced",
    "type": "weakness",
    "description": "The UAS manager, defined in uas_data.cpp, is responsible for describing the state of the robot. This description includes the current position and orientation of the robot, its capabilities, connection status, and more. Part of this manager also records a time offset between MAVROS and MAVLink, which is used to maintain synchronisation. A bug in the constructor fails to initialise the attribute responsible for recording this offset (time_offset), causing incorrect timestamps to be produced.\n",
    "cwe": "CWE-456: Missing Initialization of a Variable #RESOURCE",
    "cve": "None",
    "keywords": [
        "uninitialised field",
        "time synchronisation"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/531"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: uninitialised variable",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/531",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "fcf9cd9de383a20bb98dad3040cc0a6204cb9e10",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/lib/uas_data.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-09-17 (17:05)"
    }
}
```
