### ISSUE TITLE
Missing include in mavconn interface.h

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#532]
```yaml
{
    "id": 532,
    "title": "Missing include in mavconn interface.h",
    "type": "weakness",
    "description": "A missing header, \"boost/make_shared.hpp\", prevented the ROS Hydro-release from building.  This regression was brought about as a result of moving MAVConn to its own package. A missing header is a general issue that could appear in any C++ project.\n",
    "cwe": "Missing header (no CWE)",
    "cve": "None",
    "keywords": [
        "missing headers"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/532"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": [
            "mavlink/mavros/mavros"
        ],
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-11-02 13:28:17",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/532",
        "reproducibility": "always",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "08cd18164e729b0fb0ed1f6b553e5458eb9b6a4c",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "libmavconn/include/mavconn/interface.h"
        ],
        "languages": [
            "C++"
        ],
        "time": "2014-11-02 (17:19)"
    }
}
```
