### ISSUE TITLE
Introduced regression when converting ROS_ASSERT(false) to ROS_BREAK()

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#533]
```yaml
{
    "id": 533,
    "title": "Introduced regression when converting ROS_ASSERT(false) to ROS_BREAK()",
    "type": "weakness",
    "description": "The \"ROS_BREAK\" macro is used to abort program execution, and to output useful debugging information about the failing assertion, and the file in which it failed.  This macro should be used instead of \"ROS_ASSERT(false)\", as outlined in the ROS C++ guidelines.\nIn commit 136f387ffc3bd2ac6983a59c3eb2b63f3512e020, one of the developers incorrectly changes all of the instances of \"ROS_ASSERT(false)\" to \"ROS_BREAK(false)\". The \"ROS_BREAK\" macro does not accept an argument, and so \"ROS_BREAK()\" is the correct usage. This mistake is fixed a day after the commit that introduced the bug.\n",
    "cwe": "CWE-685: Wrong Number of Function Arguments #EVOLUTION",
    "cve": "None",
    "keywords": [
        "code smell"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/CppStyleGuide",
        "https://github.com/aliasrobotics/RVD/issues/533"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS specific # ROS_ASSERT(false) -> ROS_BREAK()",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/533",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "5353982ea0f32783fcf3e296b25ab3b253550201",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/lib/uas_frame_conversions.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2016-01-31 (14:23)"
    }
}
```
