### ISSUE TITLE
Typo in constructor

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#534]
```yaml
{
    "id": 534,
    "title": "Typo in constructor",
    "type": "weakness",
    "description": "The constructor for \"TDRRadioStatus\" is incorrectly declared. The second parameter for this constructor was accidentally placed inside the initialiser list, causing the build to fail.\n",
    "cwe": "CWE-628: Function Call with Incorrectly Specified Arguments",
    "cve": "None",
    "keywords": [
        "build error"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/534"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue typo in constructor",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-07-23 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/534",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "282c9bece1fa7bc87db070d836127b52bb9d1306",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "src/plugins/3dr_radio.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2014-07-26 (00:00)"
    }
}
```
