### ISSUE TITLE
Missing information in packet header. Fix during feature implementation.

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#535]
```yaml
{
    "id": 535,
    "title": "Missing information in packet header. Fix during feature implementation.",
    "type": "weakness",
    "description": "\"mavlink_convert.h\" is used to convert MAVROS messages to MAVLink, and vice versa. The version of this function responsible for converting from MAVROS to MAVLink failed to initialise the \"magic\" attribute for the MAVLink message.\n",
    "cwe": "CWE-456: Missing Initialization of a Variable #RESOURCE",
    "cve": "None",
    "keywords": [
        "undefined field",
        "packet header"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/mavlink/mavros/issues/286",
        "https://github.com/aliasrobotics/RVD/issues/535"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue: missing field information",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/535",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "594978da8302b6194bcf63c8119e3b3801242acd",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros_msgs/include/mavros_msgs/mavlink_convert.h"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-09-16 (14:18)"
    }
}
```
