### ISSUE TITLE
Incorrect ROS build files (e.g., CMakeLists.txt, package.xml)

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#536]
```yaml
{
    "id": 536,
    "title": "Incorrect ROS build files (e.g., CMakeLists.txt, package.xml)",
    "type": "weakness",
    "description": "The build files for the MAVROS project are missing several pieces of information, and use an incorrect, deprecated namespace in several instances:\n- The \"package.xml\" file, used to describe MAVROS as a ROS package, was missing a build-time dependency, \"std_msgs\".\n- Several types in the ROS message and service description files (.msg and .srv) use an incorrect namespace (\"mavros\", rather than \"mavros_msgs\").\n- The \"geometry_msgs\" dependency is also missing from \"CMakeLists.txt\"\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing catkin package",
        "incorrect namespace"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/536"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "XML",
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/536",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "e05c71a824cc1525d7cecb9a5ed021346cea7c8f",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros_msgs/srv/WaypointPush.srv",
            "mavros_msgs/srv/WaypointGOTO.srv",
            "mavros_msgs/package.xml",
            "mavros_msgs/msg/WaypointList.msg",
            "mavros_msgs/CMakeLists.txt"
        ],
        "languages": [
            "XML",
            "srv",
            "CMake"
        ],
        "time": "2015-08-09 (00:00)"
    }
}
```
