### ISSUE TITLE
mavros ignores SIGINT and `rosnode kill mavros`

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#537]
```yaml
{
    "id": 537,
    "title": "mavros ignores SIGINT and `rosnode kill mavros`",
    "type": "weakness",
    "description": "MAVROS ignores SIGNT and `rosnode kill mavros`, but correctly handles SIGTERM. Additionally, termination upon port closure also fails, and produces the output given below.\n[ERROR] [1408358771.110588398]: serial0:receive: End of file terminate called after throwing an instance of 'std::system_error' what(): Resource deadlock avoided\nThis behaviour was caused by a premature closure of the serial device:\nserial_dev.close(); io_service.stop();\nThe premature closure of the serial device caused io_service::run to continue indefinitely, leading to a hang upon join in MAVConnSerial::close.\nThe fix moves \"serial_dev.close()\" to immediately below \"io_service.stop()\", which then terminates correctly and resolves the bug.\n",
    "cwe": "CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition') #RESOURCE",
    "cve": "None",
    "keywords": [
        "signal handling"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/537"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "UNKNOWN",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-08-18 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/537",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/mavlink/mavros/pull/527",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "29af3a3c14da0e5b92ebad40b8befa8e0141b63d",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "libmavconn/src/serial.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2016-03-28 (00:53)"
    }
}
```
