### ISSUE TITLE
Possible array overrun

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#538]
```yaml
{
    "id": 538,
    "title": "Possible array overrun",
    "type": "weakness",
    "description": "The function \"MAVConnInterface::new_channel\" in \"mavconn_interface.cpp\" is used to establish a new communications channel, and to return the index of that channel to the caller. To the channel that should be opened for communications, the \"new_chanel\" function iterates through each of the available channels using a range-based for-loop. At each step in the loop, the program checks to see whether the numbered channel is currently in use; if the channel is free, the index for that channel is added to the \"allocated_channels\" set before being returned to the caller. A typo in the for-loop invariant caused an off-by-one error, where the program would check to see whether a non-existent channel is available. In this case, the non-existent channel, with index \"MAVLINK_COMM_NUM_BUFFERS\", would be added to the set and returned to the user. Subsequent accesses to this channel could then result in an array overrun, or cause unexpected program behaviour.\n",
    "cwe": "CWE-193: Off-by-one Error",
    "cve": "None",
    "keywords": [
        "Incorrect comparison operators",
        "array overrun",
        "off-by-one"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/538"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: off-by-one error (<= should be <)",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/538",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "215010d25409211ccfb35375c218c74c921b1a3a",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "src/mavconn/mavconn_interface.cpp"
        ],
        "languages": [
            "C++"
        ],
        "datetime": "2014-06-30 (21:15)"
    }
}
```
