### ISSUE TITLE
Retry counter isn't decremented, leading to infinite loop

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#539]
```yaml
{
    "id": 539,
    "title": "Retry counter isn't decremented, leading to infinite loop",
    "type": "weakness",
    "description": "The \"ParamPlugin\" class is used to allow users to read and manipulate parameter values. When an incorrect parameter index is used to fetch the value of a parameter, the plugin reports a warning to ROS and (should) decrement a retry counter. The retry counter allows the user to attempt to fetch the value of a given parameter up to three times in a row. When an access request fails, the program will attempt to fetch the parameter until the retry counter has expired. A bug in the code prevents the retry counter from being decremented correctly, causing the plugin to query the parameter value indefinitely.\n",
    "cwe": "CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop')",
    "cve": "None",
    "keywords": [],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/539"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-04-18 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/539",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "86255bac0538d4167de9d2bb9df59b88c587167f",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/param.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-04-18 (12:40)"
    }
}
```
