### ISSUE TITLE
set_mode service always returns true, regardless of success

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#540]
```yaml
{
    "id": 540,
    "title": "set_mode service always returns true, regardless of success",
    "type": "weakness",
    "description": "The \"set_mode\" service provides the user (and the system itself) with the means of requesting a change of mode for the robot (e.g., manual to autonomous navigation). This service call accepts the desired mode as its sole argument, and should return a boolean flag, indicating whether the request was successful, in which case True is returned, or if the request failed, in which case False is returned. In practice, however, calls to this service always return True, even when the requested mode change was unsuccessful.\nCloser inspection of the code reveals that no checking is performed by the service handler, and that the success flag is hardcoded as True.\n",
    "cwe": "Return of Wrong Status Code",
    "cve": "None",
    "keywords": "missing functionality",
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/540"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "UNKNOWN",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "Python",
            "C++"
        ],
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2016-11-07 (00:00)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/540",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "599c5887ad2aadc124d7e1354f3a1597402118da",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/scripts/mavsetp",
            "mavros/scripts/mavsys",
            "mavros/src/plugins/sys_status.cpp",
            "mavros_msgs/srv/SetMode.srv"
        ],
        "languages": [
            "Python",
            "C++"
        ],
        "time": "2017-06-28 (00:00)"
    }
}
```
