### ISSUE TITLE
Typo in function for converting from ROS to MAVLINK messages

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#541]
```yaml
{
    "id": 541,
    "title": "Typo in function for converting from ROS to MAVLINK messages",
    "type": "weakness",
    "description": "The inline \"convert\" function defined in mavlink_convert.h is responsible for converting messages from ROS to MAVLink (a popular communications protocol for small autonomous vehicles). The function accepts two references as its inputs; one for the original ROS message, rmsg, and the other for the destination MAVLink message, mmsg. A typo in this function causes an incomplete conversion.\nThe faulty line, given below, accidentally assigns the initial (placeholder) value of \"mmsg.magic\" to \"mmsg.magic\".\nmmsg.magic = mmsg.magic\nThe fixed version of this line should use the ROS message.\nmmsg.magic = rmsg.magic\n",
    "cwe": "Assignment to wrong identifier (no CWE)",
    "cve": "None",
    "keywords": [
        "typo",
        "message conversion"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/541"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2016-09-30 (00:00)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/541",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "c172409eb3ae3ccce78697d4097db6ed5d9d5721",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros_msgs/include/mavros_msgs/mavlink_convert.h"
        ],
        "languages": [
            "C++"
        ],
        "time": "2016-09-30 (15:53)"
    }
}
```
