### ISSUE TITLE
New PX4 drone now acknowledges sent commands

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#542]
```yaml
{
    "id": 542,
    "title": "New PX4 drone now acknowledges sent commands",
    "type": "weakness",
    "description": "A newer version of the PX4 autopilot module now sends an acknowledgement signal upon receiving a command, unlike all previous versions. To ensure proper functioning, the \"send_command_long_and_wait\" function, responsible for issuing commands to the drone should be updated to expect acknowledgement from the drone (autopilot).\n",
    "cwe": "CWE-252: Unchecked Return Value #EVOLUTION",
    "cve": "None",
    "keywords": [
        "robot behaviour change"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/542"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific: updated robot controller implements slightly different API",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "UNKNOWN",
        "detected-by-method": "N/A",
        "date-reported": "2016-06-15 (00:00)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/542",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "de2cc36b37689363f60876d9892f2630173b4f8c",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/command.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2016-06-23 (00:00)"
    }
}
```
