### ISSUE TITLE
Erroneous import of Goto service

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#543]
```yaml
{
    "id": 543,
    "title": "Erroneous import of Goto service",
    "type": "weakness",
    "description": "\"mavros/src/mavros/mission.py\" attempts to import a class that no longer exists, \"WaypointGOTO\", from the \"mavros_msgs.srv\" module.\n",
    "cwe": "Import of Missing Module (no CWE)",
    "cve": "None",
    "keywords": [
        "import error"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/543"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "general issue",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/543",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "c0067f9f27a5a6ef5354e06fea18279541934520",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/mavros/mission.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2015-11-13 (05:25)"
    }
}
```
