### ISSUE TITLE
Incorrect orientation (wrong frame) passed to set_attitude_target

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#544]
```yaml
{
    "id": 544,
    "title": "Incorrect orientation (wrong frame) passed to set_attitude_target",
    "type": "weakness",
    "description": "MAVROS operates on a frame of base_link->ENU, whereas MAVLink operates on aircraft->NED. Therefore, location and orientation must be transformed between these two frames when communicating between them.  The buggy function correctly performs the necessary frame conversions, but fails to pass the converted orientation in the \"set_attitude_target\" function call.\n",
    "cwe": "CWE-137 Representation Errors",
    "cve": "None",
    "keywords": [
        "incorrect argument",
        "function call",
        "frame conversion"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/544"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue?",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/544",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "b96bf672a718b9f0c9694e4314283e385ba96231",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/setpoint_raw.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2016-04-29 (17:59)"
    }
}
```
