### ISSUE TITLE
Incorrect If guard for checking orientation string is empty

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#545]
```yaml
{
    "id": 545,
    "title": "Incorrect If guard for checking orientation string is empty",
    "type": "weakness",
    "description": "Line 337 of distance_sensor.cpp is responsible for checking if a valid orientation is stored in the local \"orientation_str\" variable. If a valid orientation is unavailable, a ROS error should be produced. A typo on this line causes the if-statement guarding the error handling code to incorrectly check that the string is not empty, rather than checking the string is empty.\n",
    "cwe": "CWE-20: Improper Input Validation",
    "cve": "None",
    "keywords": [
        "corner case",
        "bad if-condition",
        "bad negation"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/545"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: incorrectly negated condition",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/545",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "c15904101ca0ecc8aa13712d92cc5382ddc0af18",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros_extras/src/plugins/distance_sensor.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-08-08 (00:52)"
    }
}
```
