### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#546]
```yaml
{
    "id": 546,
    "title": "Missing semicolon",
    "type": "weakness",
    "description": "The method call on line 70 of \"actuator_control.cpp\" is missing a trailing semi-colon, thus preventing the program from compiling.\n",
    "cwe": "Syntax Error (no CWE)",
    "cve": "None",
    "keywords": [
        "missing semicolon"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/546"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue: missing semi-colon",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/546",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "b6b975421c8242fad83138a67fb026ef0d90704d",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/plugins/actuator_control.cpp"
        ],
        "languages": [
            "C++"
        ],
        "datetime": "2015-03-01 (19:23)"
    }
}
```
