### ISSUE TITLE
OSX compilation failure due to library incompatibilities

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#547]
```yaml
{
    "id": 547,
    "title": "OSX compilation failure due to library incompatibilities",
    "type": "weakness",
    "description": "The libmavconn module fails to compile on OSX due to library incompatibilities in thread_utils.h. Specifically, the pthread_setname_np function defined in pthread.h implements a different interface for OSX and (tested) Linux systems. On OSX, this function sets the name of the calling thread to a given (C) string; on Linux, the function also accepts the pthread_t object of the thread which should be renamed.\n",
    "cwe": "OS-library incompatibility (no CWE)",
    "cve": "None",
    "keywords": [
        "porting",
        "OSX"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/547"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "UNKNOWN",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-11-14 (00:00)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/547",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "31ad11dc57aaf7dfac6f8d810162184b0f4d3ef4",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "libmavconn/include/mavconn/thread_utils.h",
            "mavros/include/mavros/utils.h"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-02-07 (00:00)"
    }
}
```
