### ISSUE TITLE
Run-time missing attribute/method error

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#548]
```yaml
{
    "id": 548,
    "title": "Run-time missing attribute/method error",
    "type": "weakness",
    "description": "Following a rosrun call to mavsetp (e.g., rosrun mavros mavsetp local -p 2 2 2 2), a missing attribute is encountered on line 40 of the \"mavsetp\" (Python) script. The attribute in question is \"guided_enable\", which no longer exists, following a refactoring of the code. The aforementioned refactoring (https://github.com/mavlink/mavros/issues/407) removed the \"cmd/guided_enabled\" service, responsible for enabling and disabling the robot's \"guided\" mode, and consequently removed the \"guided_enabled\" function responsible for handling the request; instead, these calls can be handled by the \"cmd/set_mode\" service. During this refactoring, the developer introduced a regression into the \"mavsetp\" script by failing to remove the \"guided_enabled\" call and replace it with an appropriate \"set_mode\" call.\n",
    "cwe": "Undeclared Identifier (no CWE) #EVOLUTION: CWE-439",
    "cve": "None",
    "keywords": [
        "call to missing method"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/548"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "UNKNOWN",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2016-01-21 (00:00)",
        "reported-by": "user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/548",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "bdda1fab32a9d084cfe980fe4f364b5eb35173e0",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/scripts/mavsetp",
            "mavros/src/mavros/command.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2016-01-22 (06:10)"
    }
}
```
