### ISSUE TITLE
Weak if-condition causes incorrect control flow

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#549]
```yaml
{
    "id": 549,
    "title": "Weak if-condition causes incorrect control flow",
    "type": "weakness",
    "description": "The \"passthrough\" timesync mode is used when synchronisation between MAVROS and MAVLink is not required; e.g., in cases where both are running on the same physical machine. In cases where passthrough is used, a new ROS::Time instance should be generated by adding the current offset, stored in \"time_offset\". The buggy version of the code fails to apply this offset, and thus returns incorrect timestamps.\n",
    "cwe": "CWE-670: Always-Incorrect Control Flow Implementation",
    "cve": "None",
    "keywords": [
        "weak if-condition",
        "timestamp synchronisation"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/549"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: weak if-condition",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/549",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "6bb267295ec87d8a089cc0f2f7d23555ea342943",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "mavros/src/lib/uas_timesync.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-03-30 (08:08)"
    }
}
```
