### ISSUE TITLE
Incorrect string length

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#550]
```yaml
{
    "id": 550,
    "title": "Incorrect string length",
    "type": "weakness",
    "description": "On line 210 of \"sys_status.cpp\", the contents of a decoded message (represented by a std::string) are copied to a local std::string variable, \"text\". The parameters for the initialisation of the \"text\" variable are intended to accept the contents of the original message string, and the number of characters within the string. The original, buggy code incorrectly passes the size of the message string in bytes rather than in characters. The fixed version of the code determines the number of characters in the decoded message using the \"strnlen\" function.\n",
    "cwe": "CWE-137 Representation Errors",
    "cve": "None",
    "keywords": "string length",
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/550"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue: size passed in bytes instead of length",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/550",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "2998e9f7f9e0fb969e7248a46d5ecd0749614d06",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "src/plugins/sys_status.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2014-01-13 (00:00)"
    }
}
```
