### ISSUE TITLE
Missing mavlink dependency

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#551]
```yaml
{
    "id": 551,
    "title": "Missing mavlink dependency",
    "type": "weakness",
    "description": "Versions 0.9 and 0.8.3 of MAVROS fail to build due to a missing \"mavlink\" dependency.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing dependencies"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/551"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue: missing dependency",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavros",
        "languages": [
            "XML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/551",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "dc1327f35887f9337bb4f29bb94fb8a5c5fa8a73",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "libmavconn/package.xml"
        ],
        "languages": [
            "XML"
        ],
        "time": "2013-11-03 (00:00)"
    }
}
```
