### ISSUE TITLE
Segmentation fault due to incorrect resource sharing between threads

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#552]
```yaml
{
    "id": 552,
    "title": "Segmentation fault due to incorrect resource sharing between threads",
    "type": "weakness",
    "description": "MAVROS (asynchronously) runs its TCP, UDP, and serial connection services using dedicated threads.  The \"utils::set_thread_name\" function is used to assign appropriate names to each of those threads (e.g., \"MAVConnTCPs981\"). \"utils::set_thread_name\" accepts an std::thread instance and a string, and attempts to assign the name given by the string to the thread using \"pthread_setname_np\". However, a segmentation fault occurs when the faulty program is run. This is due to the std::thread instance, \"t\", being incorrectly accessed from within the lambda for the thread. To fix this issue, \"pthread_self()\" is used to fetch a valid \"pthread_t\" instance for the current thread, instead.\n",
    "cwe": "CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition') #RESOURCE",
    "cve": "None",
    "keywords": [
        "segmentation fault",
        "race condition"
    ],
    "system": "mavros",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/552"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general issue",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "mavlink/mavros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "N/A",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/552",
        "reproducibility": "N/A",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "N/A",
        "repo": "https://github.com/mavlink/mavros",
        "hash": "400949c5b152a888a8b4fd94b085bbfc2092f146",
        "license": [
            "BSD",
            "GPLv3",
            "LGPLv3"
        ],
        "fix-in": [
            "libmavconn/include/mavconn/thread_utils.h",
            "libmavconn/include/mavconn/interface.h",
            "libmavconn/src/interface.cpp",
            "libmavconn/src/serial.cpp",
            "libmavconn/src/tcp.cpp",
            "libmavconn/src/udp.cpp",
            "libmavconn/test/test_hang.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2016-06-06 (00:00)"
    }
}
```
