### ISSUE TITLE
Use of Deprecated Functions

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#553]
```yaml
{
    "id": 553,
    "title": "Use of Deprecated Functions",
    "type": "weakness",
    "description": "Kobuki's plugin for Gazebo was using some deprecated functions to parse models. These were replaced with recommended alternatives.\n",
    "cwe": "CWE-477: Use of Obsolete Functions #EVOLUTION",
    "cve": "None",
    "keywords": [
        "gazebo, deprecation, sdf"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/553"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "simulation plugin",
        "package": "yujinrobot/kobuki_desktop/kobuki_gazebo_plugins",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "2013-07-31 02:30:12",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/553",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "27e85fc224fc6198b55c5af0d066c7901af8ec0b",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_gazebo_plugins/src/gazebo_ros_kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-08-09 (08:14)"
    }
}
```
