### ISSUE TITLE
Multiple Warnings When Unable to Check Battery Level

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#554]
```yaml
{
    "id": 554,
    "title": "Multiple Warnings When Unable to Check Battery Level",
    "type": "weakness",
    "description": "When a laptop battery monitor script was not able to check the laptop's battery (e.g. the laptop is operating without one) it would repeatedly print warnings, instead of warning just once.\n",
    "cwe": "CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop')",
    "cve": "None",
    "keywords": [
        "laptop",
        "battery",
        "power"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/554"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "yujinrobot/kobuki/kobuki_node",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-06-04 00:55:19",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/554",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "e34428db1df893b36e604f17156837af3ab380cb",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/scripts/laptop_battery.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2012-06-07 (00:55)"
    }
}
```
