### ISSUE TITLE
Use of Error Stream Instead of Debug Stream

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#555]
```yaml
{
    "id": 555,
    "title": "Use of Error Stream Instead of Debug Stream",
    "type": "weakness",
    "description": "The developers were printing out the message for a caught exception in the ROS error stream, instead of using the debug stream. This lead others to believe an actual error was occurring, when the problem was in truth handled.\n",
    "cwe": "CWE-703: Improper Check or Handling of Exceptional Conditions",
    "cve": "None",
    "keywords": [
        "exceptions",
        "debug",
        "logging"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/roscpp/Overview/Logging",
        "https://github.com/aliasrobotics/RVD/issues/555"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_node",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-11-27 15:13:11",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/555",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "816370545bf199f03e6259443861226b9701775e",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/src/library/kobuki_ros.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-12-01 (07:36)"
    }
}
```
