### ISSUE TITLE
Node Starts Normally Even When Robot Is Turned Off

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#556]
```yaml
{
    "id": 556,
    "title": "Node Starts Normally Even When Robot Is Turned Off",
    "type": "weakness",
    "description": "The Kobuki driver's node started normally even when the robot base was turned off. There was no indication of this, not even a warning. A watchdog was added to keep track of whether data is being received through the serial cable within a time limit.\n",
    "cwe": "Dangerous behavior: operation during off (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "watchdog",
        "power",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/556"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-04-16 05:41:17",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/556",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "e45b2b6a02152021764f3ca9d8d0ed17084c3bcd",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-04-16 (10:51)"
    }
}
```
