### ISSUE TITLE
Cannot Retrieve Version Information From Robot

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#557]
```yaml
{
    "id": 557,
    "title": "Cannot Retrieve Version Information From Robot",
    "type": "weakness",
    "description": "Sometimes the driver would fail to retrieve version information from the robot's firmware. This issue was fixed using a kind of flag, that, under the failing scenarios, would indicate that the driver should explicitly request version information again.\n",
    "cwe": "Missing Version Information (no CWE)",
    "cve": "None",
    "keywords": [
        "version",
        "driver",
        "firmware"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/557"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-11-21 00:03:13",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/557",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "38bee3acd7cf36960a4ce2bef821421db27a57f4",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-11-21 (00:38)"
    }
}
```
