### ISSUE TITLE
Incorrect Motion for Certain Values

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#558]
```yaml
{
    "id": 558,
    "title": "Incorrect Motion for Certain Values",
    "type": "weakness",
    "description": "Kobuki's differential drive had problems dealing with low negative linear velocities and rotation commands. The robot would move very slowly and turn in the wrong direction. It seems to be a calculation problem (logical error), when converting from the input commands to the output speeds that the firmware understands.\n",
    "cwe": "CWE-682: Incorrect Calculation #PHYSICAL",
    "cve": "None",
    "keywords": [
        "motion",
        "differential drive",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "None",
        "https://github.com/aliasrobotics/RVD/issues/558"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-05-17 10:24:41",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/558",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "af7946f9b5a5a8536c5df6cbefc83b6020d38dd0",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/src/driver/diff_drive.cpp",
            "kobuki_driver/src/test/velocity_commands.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-05-17 (12:12)"
    }
}
```
