### ISSUE TITLE
The inactivity Timeout Was Too Long

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#559]
```yaml
{
    "id": 559,
    "title": "The inactivity Timeout Was Too Long",
    "type": "weakness",
    "description": "Kobuki has a parameter with the default timeout period for inactivity.  This means that if no commands are received within X seconds (where X is the parameter value), then the robot stops moving. This timeout had a very long value of 2 seconds, which allows for a diverse range of problematic scenarios.\n",
    "cwe": "Wrong Parameter Value (no CWE)",
    "cve": "None",
    "keywords": [
        "timeout",
        "driver",
        "motion"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/559"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2012-05-16 16:10:04",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/559",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "d9aa65681b3f10d0b6dda3d591a24b8be5119fb6",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_bringup/resources/yaml/kobuki.yaml"
        ],
        "languages": [
            "YAML"
        ],
        "time": "2012-05-16 (17:29)"
    }
}
```
