### ISSUE TITLE
Nodelets Hanging on Shutdown

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#560]
```yaml
{
    "id": 560,
    "title": "Nodelets Hanging on Shutdown",
    "type": "weakness",
    "description": "Under certain scenarios, when shutdown was requested (by pressing Ctrl+C), the various Kobuki nodelets would not properly shutdown. For instance, when launching a minimal configuration (the nodelet manager plus the driver nodelet) and, in another terminal, launching extra nodelets (teleoperation), the system would hang if the second launch sequence was terminated first. This is due to some nodelets spawning additional threads and relying solely on `ros::ok()` to detect termination. However, the nodelet documentation clearly states that additional threads spawned by the user have to be manually cleaned up. In short, the termination signal was being ignored when the nodelet manager was not terminated directly.\n",
    "cwe": "CWE-404: Improper Resource Shutdown or Release #RESOURCE",
    "cve": "None",
    "keywords": [
        "threading",
        "termination",
        "synchronization",
        "shutdown",
        "nodelet"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/nodelet",
        "https://github.com/aliasrobotics/RVD/issues/560"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "safety controller",
        "package": "yujinrobot/kobuki/kobuki_safety_controller",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-12-01 16:15:01",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/560",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "38dce2aac9c4a519fbcec4032838a3451662e7b6",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_safety_controller/src/nodelet.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-12-05 (03:43)"
    }
}
```
