### ISSUE TITLE
Unknown Type Due to Missing Include

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#561]
```yaml
{
    "id": 561,
    "title": "Unknown Type Due to Missing Include",
    "type": "weakness",
    "description": "The compiler complains about not knowing the type `uint16_t`, which is declared in `stdint.h`. The original code relied on another library (libusb-dev) to include the required header as a dependency, instead of including it directly.  This worked only for some systems.\n",
    "cwe": "Missing Include / Dependency (no CWE) internal classification (cause): internal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "includes",
        "header files",
        "stdint",
        "dependencies"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/561"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_ftdi",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "2013-01-24 21:33:53",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/561",
        "reproducibility": "sometimes",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "0027b57fea017e610baa226b6645a5a1c071f05c | 087aa595f7c93ed7f34c3fb9db5629532bdf972a",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_ftdi/include/kobuki_ftdi/scanner.hpp",
            "kobuki_ftdi/manifest.xml"
        ],
        "languages": [
            "C++",
            "package.xml"
        ],
        "time": "2013-01-25 (08:40)"
    }
}
```
