### ISSUE TITLE
Possible Race Condition When Accessing Sensor Data

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#562]
```yaml
{
    "id": 562,
    "title": "Possible Race Condition When Accessing Sensor Data",
    "type": "weakness",
    "description": "Sensor data could potentially be accessed in multi-threaded contexts, but there were no synchronization mechanisms in place. It worked well for Kobuki due to chance: all read and write operations were in the same thread. But, due to the way it is built, it could have been an issue for other users.\n",
    "cwe": "CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition') #RESOURCE",
    "cve": "None",
    "keywords": [
        "concurrency",
        "race condition",
        "synchronization",
        "threading"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/562"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-02-28 07:50:34",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/562",
        "reproducibility": "rare",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "3c4c399a460b314152722de6b99804e138d68e88",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/src/driver/kobuki.cpp",
            "kobuki_node/src/library/kobuki_ros.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-08-22 (09:40)"
    }
}
```
