### ISSUE TITLE
Unexpected Movement Due to Wrong Calculation

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#563]
```yaml
{
    "id": 563,
    "title": "Unexpected Movement Due to Wrong Calculation",
    "type": "weakness",
    "description": "Kobuki moves using differential drive. Originally, the command velocities (linear and angular) were provided as `short`, and were converted to `short` after each step, even though the calculations yielded floating point numbers. This lead to calculation errors in some special cases, where the robot was supposed to move forward but ended up moving backwards instead.\n",
    "cwe": "CWE-704: Incorrect Type Conversion or Cast #PHYSICAL",
    "cve": "None",
    "keywords": [
        "differential drive",
        "rounding",
        "driver",
        "movement"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://en.wikipedia.org/wiki/Differential_wheeled_robot",
        "https://github.com/aliasrobotics/RVD/issues/563"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-04-05 09:27:36",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/563",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "1c141a54fb2c0e2ec453b32f8026d1cd0ffb14d9",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/modules/diff_drive.hpp",
            "kobuki_driver/src/driver/diff_drive.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-05-07 (06:40)"
    }
}
```
