### ISSUE TITLE
Unclean termination leads to exceptions and segmentation faults

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#565]
```yaml
{
    "id": 565,
    "title": "Unclean termination leads to exceptions and segmentation faults",
    "type": "weakness",
    "description": "When an interrupt signal is issued (Ctrl+C), termination code should ensure a clean program exit. It was found that some threads outlived the termination code, and kept running normally. With the system in an unstable state (half terminated, half running), the program ended in a crash, by raising exceptions or segmentation faults. The reported issue was closed once, with the assignee stating that he had found a fix by accident (with no referenced commit). It was then reopened, because the bug still persisted and manifested less often. The fix involved a complete rework of the way threads and concurrent code were handled. The initial implementation used ecl::Threadable, while the new solution uses a plain ecl::Thread. The new solution still uses Boolean flags to communicate between threads, but now the main thread uses `join` to wait for the worker thread to finish (also synchronizing memory). In the initial implementation there seems to be no mechanism in place to synchronize both threads, which could be the cause for the worker thread to remain unaware of termination. With this in mind, \"Race Condition within a Thread (CWE-366)\" is applicable, but we will classify the bug in terms of its visible effect.\n",
    "cwe": "CWE-672: Operation on a Resource after Expiration or Release #RESOURCE",
    "cve": "None",
    "keywords": [
        "thread-safety",
        "concurrency",
        "termination"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/565"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2012-04-05 21:35:09",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/565",
        "reproducibility": "sometimes",
        "trace": "terminate called after throwing an instance of 'ecl::StandardException'\nwhat():\nLocation : /opt/yujin/unstable/stacks/ecl/ecl_core/ecl_devices/include/ecl/devices/serial_pos.hpp:407\nFlag     : Attempted to work on an invalid object.\nDetail   : The device is not a valid device for writing.\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "62a38a99cdfaf511cff1dd9e03b7bb88516f9033",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-04-14 (14:12)"
    }
}
```
