### ISSUE TITLE
Use of Platform-specific Functions

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#566]
```yaml
{
    "id": 566,
    "title": "Use of Platform-specific Functions",
    "type": "weakness",
    "description": "Kobuki's driver was making use of the deprecated `usleep` function, along with other sleep functions from `ctime`. For cross-platform support, these have been replaced with the sleep functions from the platform-independent `ecl` library.\n",
    "cwe": "CWE-477: Use of Obsolete Functions #EVOLUTION",
    "cve": "None",
    "keywords": [
        "posix",
        "sleep",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/566"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-04-05 20:41:37",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/566",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "95b24e8218ea593cf820478e0829adc92fff7457",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-04-09 (06:13)"
    }
}
```
