### ISSUE TITLE
Node Crashes When the Robot is Disconnected

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#567]
```yaml
{
    "id": 567,
    "title": "Node Crashes When the Robot is Disconnected",
    "type": "weakness",
    "description": "When the USB serial cable is unplugged, the Kobuki driver's node crashes. This is related to the node trying to read data from the Bluetooth interface when USB is unplugged. Under certain conditions (not specified) it causes a crash.\n",
    "cwe": "Use of Wrong Interface (no CWE)",
    "cve": "None",
    "keywords": [
        "udev",
        "serial",
        "bluetooth",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/567"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_ftdi | yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2013-02-18 06:52:19",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/567",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "606b8b9434ce501ff663e9252f5459eb9c50c6af",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_ftdi/57-kobuki.rules"
        ],
        "languages": [
            "udev rules"
        ],
        "time": "2013-02-19 (07:15)"
    }
}
```
