### ISSUE TITLE
Battery Charge Was Not Showing on Android Applications

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#568]
```yaml
{
    "id": 568,
    "title": "Battery Charge Was Not Showing on Android Applications",
    "type": "weakness",
    "description": "Turtlebot features some Android applications to control the robot (e.g. teleoperation, or make a map of the surroundings). These applications have a battery indicator to let the user know how much battery the robot has left. However, this indicator was displaying no information at all. The reason was that the application listens for the robot's diagnostics and looks for a specific name in the diagnostics fields, but the robot was emitting diagnostics with a prefix attached to the names.  Changing the diagnostics parameter file to indicate that the prefix should be removed fixes the issue.\n",
    "cwe": "Looking for Wrong Name (no CWE)",
    "cve": "None",
    "keywords": [
        "diagnostics",
        "power",
        "android",
        "battery"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "None",
        "https://github.com/aliasrobotics/RVD/issues/568"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "generic task component",
        "package": "yujinrobot/kobuki/kobuki_node | yujinrobot/kobuki/kobuki_bringup",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-06-20 02:51:39",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/568",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "bb3c7ec8a7e656aa7e75753864351c27d571db47",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_bringup/resources/yaml/diagnostics.yaml",
            "kobuki_node/src/node/diagnostics.cpp"
        ],
        "languages": [
            "C++",
            "YAML"
        ],
        "time": "2012-06-20 (04:01)"
    }
}
```
