### ISSUE TITLE
Test Suite GUI Crashing Due to API Changes

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#569]
```yaml
{
    "id": 569,
    "title": "Test Suite GUI Crashing Due to API Changes",
    "type": "weakness",
    "description": "Kobuki's test suite uses GUI plugins for rqt in order to plot collected data. This plotting component crashed due to changes in rqt's interface.\n",
    "cwe": "API Incompatibility (no CWE)",
    "cve": "None",
    "keywords": [
        "rqt",
        "rqt_plot",
        "test suite",
        "testing",
        "api"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/569"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "test suite",
        "subsystem": "test suite",
        "package": "yujinrobot/kobuki_desktop/kobuki_qtestsuite",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2013-03-12 04:20:06",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/569",
        "reproducibility": "always",
        "trace": "Traceback (most recent call last): File \"/opt/ros/groovy/lib/python2.7/dist-packages/rqt_plot/plot_widget.py\", line 168, in update_plot self.data_plot.redraw() File \"/opt/turtlebot/kobuki_desktop/kobuki_qtestsuite/plugins/../src/kobuki_qtestsuite/full_size_data_plot.py\", line 54, in redraw data_x, data_y, plot = curve ValueError: too many values to unpack\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "3c7f92a2c6a51b4896e669d0da34b4de90a71914",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_qtestsuite/scripts/kobuki_qtestsuite",
            "kobuki_qtestsuite/setup.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/battery_profile_frame.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/configuration_dock_widget.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/full_size_data_plot.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/testsuite_widget.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/ui/configuration_dock.ui"
        ],
        "languages": [
            "Python",
            "XML"
        ],
        "time": "2013-08-21 (10:23)"
    }
}
```
