### ISSUE TITLE
rqt_plot Failing When Kobuki Is Installed

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#570]
```yaml
{
    "id": 570,
    "title": "rqt_plot Failing When Kobuki Is Installed",
    "type": "weakness",
    "description": "Starting the rqt_plot tool (a plotting GUI with plugins) resulted in a crash when Kobuki was also installed (for specific versions, and after a certain update to rqt_plot). The crash was due to the tool interpreting some resource paths relative to the XML file that defines the plugin, while its documentation stated that paths should be relative to the ROS package path.  Since most plugins had the XML file at the root of the package, this was not an issue. But Kobuki did not, and so the issue came up. In the end, the tool was changed to interpret all paths relative to the XML file, as was that the intended behaviour.\n",
    "cwe": "Misinterpretation of relative paths (no CWE) #EVOLUTION",
    "cve": "None",
    "keywords": [
        "rqt",
        "rqt_plot",
        "plugins"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/rqt_plot",
        "http://wiki.ros.org/rqt/Tutorials/Create%20your%20new%20rqt%20plugin",
        "https://github.com/aliasrobotics/RVD/issues/570"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "ROS tool",
        "package": "ros-visualization/qt_gui_core/qt_gui | ros-visualization/qt_gui_core/qt_gui_cpp | ros-visualization/rqt/rqt_gui",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2013-04-02 11:45:01",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/570",
        "reproducibility": "always",
        "trace": "Traceback (most recent call last):\n  File \"/opt/ros/groovy/lib/rqt_plot/rqt_plot\", line 10, in <module>\n    sys.exit(main.main(standalone=plugin, plugin_argument_provider=Plot.add_arguments))\n  File \"/opt/ros/groovy/lib/python2.7/dist-packages/rqt_gui/main.py\", line 57, in main\n    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider)\n  File \"/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/main.py\", line 468, in main\n    plugins = plugin_manager.find_plugins_by_name(plugin)\n  File \"/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_manager.py\", line 118, in find_plugins_by_name\n    for plugin_id, plugin_full_name in self.get_plugins().items():\n  File \"/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_manager.py\", line 124, in get_plugins\n    self.discover()\n  File \"/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_manager.py\", line 108, in discover\n    self._plugin_menu.add_plugin(plugin_descriptor)\n  File \"/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_menu.py\", line 79, in add_plugin\n    self._enrich_action(action, action_attributes, base_path)\n  File \"/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_menu.py\", line 130, in _enrich_action\n    raise UserWarning('icon \"%s\" not found' % str(path))\nUserWarning: icon \"../src/kobuki_qtestsuite/resources/images/kobuki_icon.png\" not found\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/ros-visualization/rqt | https://github.com/ros-visualization/qt_gui_core",
        "hash": "9682b9af78eecd368004fe7596e341eb84abc719 | ffae1f756dbf23194a2628922939d9633df947f6",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "qt_gui/src/qt_gui/help_provider.py",
            "qt_gui/src/qt_gui/plugin_manager.py",
            "qt_gui_cpp/include/qt_gui_cpp/ros_pluginlib_plugin_provider.h",
            "rqt_gui/src/rqt_gui/ros_plugin_provider.py"
        ],
        "languages": [
            "Python",
            "C++"
        ],
        "time": "2013-05-28 (20:03)"
    }
}
```
