### ISSUE TITLE
Calculation Error Inverts Turning Direction

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#571]
```yaml
{
    "id": 571,
    "title": "Calculation Error Inverts Turning Direction",
    "type": "weakness",
    "description": "Due to an error in velocity calculations, when Kobuki was issued a very low negative linear speed (very slow backwards movement), it would also inadvertently invert its turning direction. That is, if it was supposed to move backwards while turning left, it would move backwards and turn right instead.\n",
    "cwe": "CWE-682: Incorrect Calculation #PHYSICAL",
    "cve": "None",
    "keywords": [
        "differential drive",
        "velocity",
        "driver",
        "movement"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "None",
        "https://github.com/aliasrobotics/RVD/issues/571"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-02-22 09:09:21",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/571",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "e964bbb8700fb1a9b95c0cfe5a44d43321294d4f",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/src/driver/diff_drive.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-02-25 (09:31)"
    }
}
```
