### ISSUE TITLE
No Graceful Termination When Firmware is Outdated

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#572]
```yaml
{
    "id": 572,
    "title": "No Graceful Termination When Firmware is Outdated",
    "type": "weakness",
    "description": "There were no checks on firmware version, and thus no graceful termination if the driver and firmware were incompatible.\n",
    "cwe": "CWE-754: Improper Check for Unusual or Exceptional Conditions #EVOLUTION",
    "cve": "None",
    "keywords": [
        "firmware",
        "termination",
        "version",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/572"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-11-24 07:41:21",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/572",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "c04eae575167f579f9fce4e11f212e6d73b3deac | d92a96e5a05f69c626132db42490ac382298df93",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/src/library/kobuki_ros.cpp",
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/include/kobuki_driver/packets/firmware.hpp",
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-11-29 (11:47)"
    }
}
```
