### ISSUE TITLE
Misaligned or Overflowed Buffer

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#573]
```yaml
{
    "id": 573,
    "title": "Misaligned or Overflowed Buffer",
    "type": "weakness",
    "description": "Sometimes, when reading serial data, the Kobuki driver would find the buffer to be overflowed (missing data) or misaligned (including unintended bits of data). This showed up when using formatters to convert the byte buffer to a convenient string representation. The main problem was in the formatters, and not in the Kobuki driver.  It consumed data always from index zero, even though sometimes it should start from a greater index.\n",
    "cwe": "CWE-125: Out-of-bounds Read",
    "cve": "None",
    "keywords": [
        "buffer",
        "arrays"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/ecl_formatters",
        "http://wiki.ros.org/ecl_containers",
        "https://github.com/aliasrobotics/RVD/issues/573"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver | stonier/ecl_core/ecl_containers",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-11-22 01:47:19",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/573",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/stonier/ecl_core",
        "hash": "9397c6b872cba3e894171507ef23f366fc968f3e",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ecl_containers/include/ecl/containers/push_and_pop/formatters.hpp",
            "ecl_containers/include/ecl/containers/push_and_pop/push_and_pop_dynamic.hpp",
            "ecl_containers/include/ecl/containers/push_and_pop/push_and_pop_fixed.hpp",
            "ecl_containers/src/examples/formatters.cpp",
            "ecl_containers/src/test/push_and_pop.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-12-03 (03:20)"
    }
}
```
