### ISSUE TITLE
Robot Model Viewer Fails to Display Model

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#574]
```yaml
{
    "id": 574,
    "title": "Robot Model Viewer Fails to Display Model",
    "type": "weakness",
    "description": "Launching the robot model viewer would result in an error, stating that there was no robot model to display. The reason behind this was that the xacro file only defined the `kobuki` tag, but did not instantiate it. In other words, it was not a standalone file.\n",
    "cwe": "Wrong Robot Model (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "urdf",
        "xacro",
        "rviz"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/574"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "robot model viewer",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_description",
        "languages": "None",
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2012-12-27 15:23:00",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/574",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "4ea5ea7ff535323baeada165764b5b8ceb7bfa87",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_description/launch/view_model.launch",
            "kobuki_description/rviz/model.rviz",
            "kobuki_description/urdf/kobuki.urdf.xacro",
            "kobuki_description/urdf/kobuki_standalone.urdf.xacro"
        ],
        "languages": [
            "Launch XML",
            "RViz",
            "xacro"
        ],
        "time": "unfixed"
    }
}
```
