### ISSUE TITLE
Potential Race Condition on Serial Writes

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#575]
```yaml
{
    "id": 575,
    "title": "Potential Race Condition on Serial Writes",
    "type": "weakness",
    "description": "The Kobuki driver communicates with the actual robot by sending commands over a serial cable. This interface was not protected against concurrent accesses, while being used in an environment that, more often that not, features multithreading.\n",
    "cwe": "CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition') #RESOURCE",
    "cve": "None",
    "keywords": [
        "multithreading",
        "concurrency",
        "race condition",
        "driver",
        "serial"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/575"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-06-04 04:54:19",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/575",
        "reproducibility": "rare",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "03660afb5917366cc6d57567e2f695450fd95feb",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-06-04 (05:58)"
    }
}
```
