### ISSUE TITLE
Teleoperation Nodelet Crashing on Keyboard Input

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#576]
```yaml
{
    "id": 576,
    "title": "Teleoperation Nodelet Crashing on Keyboard Input",
    "type": "weakness",
    "description": "The Kobuki keyboard teleoperation nodelet, `kobuki_keyop`, crashed under two scenarios: 1. when Ctrl+C was pressed during execution and the driver nodelet was not running; 2. when any key was pressed during initialization. When this abrupt termination occurred, it also had side effects on the formatting of that terminal's output. The main issue for (1) was a lack of exception handlers to handle the interrupt signals during sleeps. Regarding (2), the thread that processes keyboard input was being spawned before all initialization operations were performed, leading to manipulation of uninitialized state if there was premature input to process. The fix also places thread start at the right time.\n",
    "cwe": "CWE-248: Uncaught Exception",
    "cve": "None",
    "keywords": [
        "teleop",
        "exceptions",
        "interrupt"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/576"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "teleoperation",
        "subsystem": "generic task component",
        "package": "yujinrobot/kobuki/kobuki_keyop",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2012-11-27 15:21:53",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/576",
        "reproducibility": "always",
        "trace": "[FATAL] [1354029622.148262110]: ASSERTION FAILED\n    file = /opt/ros/groovy/include/ros/publisher.h\n    line = 69\n    cond = false\n    message =\n[FATAL] [1354029622.152687114]: Call to publish() on an invalid Publisher\n[FATAL] [1354029622.153042536]:\n[keyop-1] process has died [pid 13442, exit code -5, cmd /opt/turtlebot_groovy/kobuki/kobuki_keyop/bin/keyop keyop/enable:=/enable keyop/disable:=/disable keyop/cmd_vel:=/cmd_vel keyop/mobile_robot/reset_odometry:=/mobile_base/reset_odometry __name:=keyop __log:=/home/yujin/.ros/log/97190902-3887-11e2-b4e2-0026c7d760cc/keyop-1.log].\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "f548cc73fb2959c7ceb6ab1c7f5a973bf95e5594",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_keyop/include/keyop_core/keyop_core.hpp",
            "kobuki_keyop/manifest.xml",
            "kobuki_keyop/src/keyop_core.cpp",
            "kobuki_keyop/src/main.cpp"
        ],
        "languages": [
            "C++",
            "Package XML"
        ],
        "time": "2012-12-01 (06:26)"
    }
}
```
