### ISSUE TITLE
Robot Reports Full Battery Before Charging It

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#577]
```yaml
{
    "id": 577,
    "title": "Robot Reports Full Battery Before Charging It",
    "type": "weakness",
    "description": "Just after connecting to the power adapter the robot would send a \"battery charged\" signal, and only after would it transition to the appropriate \"charging\" state.\n",
    "cwe": "CWE-393: Return of Wrong Status Code",
    "cve": "None",
    "keywords": [
        "battery",
        "power",
        "driver",
        "charging"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "None",
        "https://github.com/aliasrobotics/RVD/issues/577"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver | yujinrobot/kobuki/kobuki_node",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-06-20 04:35:39",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/577",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "841720ab97e442a11ae30b7abdbef07150e56c97",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_comms/msg/PowerSystemEvent.msg",
            "kobuki_driver/include/kobuki_driver/event_manager.hpp",
            "kobuki_driver/src/driver/event_manager.cpp",
            "kobuki_node/include/kobuki_node/kobuki_node.hpp",
            "kobuki_node/src/node/kobuki_node.cpp",
            "kobuki_node/src/node/slot_callbacks.cpp"
        ],
        "languages": [
            "C++",
            "ROS Message"
        ],
        "time": "2012-06-25 (13:14)"
    }
}
```
