### ISSUE TITLE
Not using zero-copy message publishing when possible

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#578]
```yaml
{
    "id": 578,
    "title": "Not using zero-copy message publishing when possible",
    "type": "weakness",
    "description": "ROS works mainly in the form of publisher-subscriber systems, where nodes publish messages that they want to share with others. The nodes can be physically distributed, so, by default, messages are serialized, deserialized, and the receiver gets a copy of the original message. Often nodes are very coupled and live within the same machine. In this case, copying every message incurs an unnecessary cost. ROS provides a concept, called nodelets, that are essentially nodes living as threads inside the same process, rather than each node being its own process. When nodelets are used, an alternative publish function can be used, so that the messages are shared by pointers between nodelets (shared memory), and no copies are made. This can represent a significant performance boost. This bug consists on using the traditional publish by copy, even when using nodelets. The fix consists on storing shared pointers to messages, so that the pointers can be published instead of a copy of the message structure.\n",
    "cwe": "Creating Unnecessary Copies of Objects (no CWE) #RESOURCE",
    "cve": "None",
    "keywords": [
        "nodelet",
        "shared memory",
        "publish",
        "pointer",
        "object copy"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/nodelet",
        "https://github.com/aliasrobotics/RVD/issues/578"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_node",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-12-01 02:51:33",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/578",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "dbcdb12acb4b7811084d4f4dc75e0408b9899de0",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/include/kobuki_node/odometry.hpp",
            "kobuki_node/src/library/odometry.cpp",
            "kobuki_node/src/library/slot_callbacks.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-12-04 (05:59)"
    }
}
```
