### ISSUE TITLE
Node Fails Due to Bad Linking

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#579]
```yaml
{
    "id": 579,
    "title": "Node Fails Due to Bad Linking",
    "type": "weakness",
    "description": "The nodelet was linked directly against an executable, resulting in a crash during runtime. Nodelets should be separated into their own libraries and loaded dynamically.\n",
    "cwe": "Linking error (no CWE)",
    "cve": "None",
    "keywords": [
        "linking",
        "catkin",
        "nodelet",
        "class loader"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "None",
        "https://github.com/aliasrobotics/RVD/issues/579"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "auto docking",
        "subsystem": "specific application component",
        "package": "yujinrobot/kobuki/kobuki_auto_docking",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2013-02-25 04:32:32",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/579",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "3e88010293c350ffa71f5e8b64ec58ec09a64549",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_auto_docking/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2013-02-25 (04:36)"
    }
}
```
