### ISSUE TITLE
Maintaining Constructs From Old Versions

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#580]
```yaml
{
    "id": 580,
    "title": "Maintaining Constructs From Old Versions",
    "type": "weakness",
    "description": "A change of protocol was not fully reflected in the code.  There were remnants of the initial version, resulting in two different topics publishing the same sensor information under different names.  Another issue was having multiple functions that were doing mostly the same thing, but named accordingly to each protocol version (e.g. `getData`, `getData2`, `getDefaultData`).\n",
    "cwe": "CWE-477: Use of Obsolete Functions #EVOLUTION",
    "cve": "None",
    "keywords": [
        "protocol",
        "topics",
        "api",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/580"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_node",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-04-09 05:24:47",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/580",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "b18f55910cc032f967b436b26710c01ec435291d",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/src/driver/kobuki.cpp",
            "kobuki_node/include/kobuki_node/kobuki_node.hpp",
            "kobuki_node/src/nodelets/kobuki_node.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-04-09 (06:34)"
    }
}
```
