### ISSUE TITLE
Keyboard Teleoperation Not Issuing Commands to Base

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#581]
```yaml
{
    "id": 581,
    "title": "Keyboard Teleoperation Not Issuing Commands to Base",
    "type": "weakness",
    "description": "The node for keyboard teleoperation for Kobuki was not issuing commands to the robot. As it turns out, it was an issue of wrong remappings and namespaces.  The teleop node was advertising a topic different than the one the base was subscribed to. A contributing factor for this issue may be the fact that the teleop node and the base node are launched in different launch files.\n",
    "cwe": "Wrong Remappings (no CWE)",
    "cve": "None",
    "keywords": [
        "remappings",
        "topics",
        "namespaces",
        "launch",
        "teleop"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/roslaunch/XML/remap",
        "http://wiki.ros.org/Remapping%20Arguments",
        "http://wiki.ros.org/Names",
        "https://github.com/aliasrobotics/RVD/issues/581"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "keyboard teleoperation",
        "subsystem": "specific application component",
        "package": "yujinrobot/kobuki/kobuki_meta",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-04-05 22:58:49",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/581",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "fbe70c7d5e6d3b85fea6296c23039958c428e6df",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_meta/resources/launch/components/base.launch",
            "kobuki_meta/resources/launch/keyop.launch"
        ],
        "languages": [
            "Launch XML"
        ],
        "time": "2012-04-05 (23:57)"
    }
}
```
