### ISSUE TITLE
Wrong topic remapping makes robot ignore velocity commands

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#582]
```yaml
{
    "id": 582,
    "title": "Wrong topic remapping makes robot ignore velocity commands",
    "type": "weakness",
    "description": "ROS allows resource names to be remapped. Topics, in particular, are resources that can be remapped. When topic \"A\" is remapped to \"B\" and a node tries to publish/subscribe on \"A\", it will (automatically) publish/subscribe to \"B\" instead. Remappings are commonly defined in launch files. Launch files are special XML files used by the tool `roslaunch` to initialize several nodes, parameters and remappings at once. In this particular bug, a node (cmd_vel_mux) publishes velocity messages that are received by the driver node (mobile_base). A launch file defined a remapping from \"cmd_vel_mux/mux_cmd_vel\" to \"mobile_base/commands/velocity\", but the cmd_vel_mux node is, in fact, publishing on \"cmd_vel_mux/output\". Since the node is publishing on a different topic, the remapping has no effect, and so the two expected topic names are not connected. The end result is that the published messages never reach their destination, i.e., the robot does not move at all. This issue is very specific to ROS, as it is located and solved in launch.xml files, but the issue of a runtime configuration of a distributed system is general, in principle.\n",
    "cwe": "Wrong Remappings (no CWE)",
    "cve": "None",
    "keywords": [
        "remapping",
        "topic",
        "launch",
        "architecture configuration"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/Remapping%20Arguments",
        "http://wiki.ros.org/roslaunch/XML/remap",
        "https://github.com/aliasrobotics/RVD/issues/582"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "automatic docking",
        "subsystem": "launch file",
        "package": "yujinrobot/kobuki/kobuki_auto_docking",
        "languages": [
            "launch XML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-02-25 07:37:24",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/582",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "35682ec3c3e7177373c66c48228ad58b2eb34aae",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_auto_docking/launch/auto_dock_with_safe_keyop.launch"
        ],
        "languages": [
            "launch XML"
        ],
        "time": "2013-02-25 (08:34)"
    }
}
```
