### ISSUE TITLE
Robot With Lack of Acceleration Smoothing

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#583]
```yaml
{
    "id": 583,
    "title": "Robot With Lack of Acceleration Smoothing",
    "type": "weakness",
    "description": "Initially, Kobuki did not have an acceleration smoother, a component that was reponsible for inhibiting sudden acceleration changes and smooth the motion over a few steps. It was reported that rotation commands at rest would not finish smoothly and would interfere with translation commands. There are also reports of the robot performing wheelies when a command was issued after staying idle: the robot had a very high torque for half a second before returning to normal levels.\n",
    "cwe": "CWE-682: Incorrect Calculation #PHYSICAL",
    "cve": "None",
    "keywords": [
        "motion",
        "acceleration",
        "smoother",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/583"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2012-06-04 04:56:40",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/583",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "ad906f0a6ebeb732afb5938f79200f8eb4bccabf",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/modules/gate_keeper.hpp",
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2012-06-11 (04:40)"
    }
}
```
