### ISSUE TITLE
Robot Getting Stuck When Auto-docking

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#584]
```yaml
{
    "id": 584,
    "title": "Robot Getting Stuck When Auto-docking",
    "type": "weakness",
    "description": "Kobuki is a mobile robot base that is used mainly for version 2 of Turtlebot, but there are some other uses for it with heavier payloads. The movement speeds were hard-coded for the auto-docking algorithm, and worked well for regular Kobuki and Turtlebot, but were too slow for heavier robots, causing them to get stuck. To solve this issue, the minimum speed limits had to be configurable.\n",
    "cwe": "Wrong behavior (no CWE) #CWE-344 #PHYSICAL",
    "cve": "None",
    "keywords": [
        "hard-coded values",
        "auto-docking",
        "speed"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/584"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "auto-docking",
        "subsystem": "specific application component",
        "package": "yujinrobot/kobuki/kobuki_auto_docking",
        "languages": "N/A",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-05-24 00:29:17",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/584",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "0416c81e5d08466477c5806443a580a142d0d465",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_auto_docking/include/kobuki_auto_docking/dock_drive.hpp",
            "kobuki_auto_docking/src/auto_docking_ros.cpp",
            "kobuki_auto_docking/src/dock_drive.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-05-24 (07:28)"
    }
}
```
