### ISSUE TITLE
Missing Build Dependency

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#585]
```yaml
{
    "id": 585,
    "title": "Missing Build Dependency",
    "type": "weakness",
    "description": "A package dependency was missing in order for the build to succeed.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "package",
        "dependencies",
        "build"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/package.xml#Dependencies",
        "https://github.com/aliasrobotics/RVD/issues/585"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki_core/kobuki_ftdi",
        "languages": [
            "package.xml",
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "build system",
        "detected-by-method": "N/A",
        "date-reported": "2017-03-01 08:57:20",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/585",
        "reproducibility": "always",
        "trace": "CMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:552 (message):\n  None of the required 'libusb' found\nCall Stack (most recent call first):\n  CMakeLists.txt:7 (pkg_search_module)\n-- checking for one of the modules 'libftdi'\nCMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:552 (message):\n  None of the required 'libftdi' found\nCall Stack (most recent call first):\n  CMakeLists.txt:8 (pkg_search_module)\nCMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):\n  catkin_package() DEPENDS on 'libusb' but neither 'libusb_INCLUDE_DIRS' nor\n  'libusb_LIBRARIES' is defined.\nCall Stack (most recent call first):\n  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)\n  CMakeLists.txt:10 (catkin_package)\nCMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):\n  catkin_package() DEPENDS on 'libftdi' but neither 'libftdi_INCLUDE_DIRS'\n  nor 'libftdi_LIBRARIES' is defined.\nCall Stack (most recent call first):\n  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)\n  CMakeLists.txt:10 (catkin_package)\n-- Configuring incomplete, errors occurred!\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_core",
        "hash": "eed104dcdd8862824598838b65a7e2339f8e660a",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_ftdi/package.xml"
        ],
        "languages": [
            "Package XML"
        ],
        "time": "2017-03-03 (00:11)"
    }
}
```
