### ISSUE TITLE
Terminal Becomes Unresponsive Due To Uninitialized Objects

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#586]
```yaml
{
    "id": 586,
    "title": "Terminal Becomes Unresponsive Due To Uninitialized Objects",
    "type": "weakness",
    "description": "Sometimes, the logging functions of ROS would misbehave, for instance printing all text in capital letters. Additionally, the terminal would become unresponsive, ignoring Ctrl+C signals to shutdown the application. Kobuki uses a serial port to communicate between the robot itself and the computer running ROS. To handle the serial port communication, the `serial` API from the `ecl_devices` library package is used.  The developer's idea is to set the reading mode to blocking (synchronous).  However, the `block(timeout)` function is called before the `Serial` object is fully initialized (via the `open` function). Setting the blocking mode on an uninitialized `Serial` object will try to manipulate a file descriptor that is only initialized with the `open` function. In short, calling the functions in the wrong order leads to using uninitialized values, causing the wrong behaviour.\n",
    "cwe": "CWE-908: Use of Uninitialized Resource #RESOURCE",
    "cve": "None",
    "keywords": [
        "serial",
        "ecl",
        "terminal",
        "blocking"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/ecl/about",
        "http://wiki.ros.org/ecl_devices/Tutorials/Introduction%20to%20Ecl%20Devices",
        "https://github.com/aliasrobotics/RVD/issues/586"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-06-19 01:15:47",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/586",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/yujinrobot/kobuki/pull/278",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "054c753b40b56b20c39051e14bdab71bc50e1ae8",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/src/driver/kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-08-01 (07:33)"
    }
}
```
