### ISSUE TITLE
Exporting Non-Existent Libraries

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#587]
```yaml
{
    "id": 587,
    "title": "Exporting Non-Existent Libraries",
    "type": "weakness",
    "description": "A CMake file was declaring a couple libraries as being part of the Kobuki driver package, but it was actually a copy and paste mistake.\n",
    "cwe": "Exporting Non-Existent Libraries (no CWE)",
    "cve": "None",
    "keywords": [
        "CMake",
        "libraries",
        "package"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/587"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki_core/kobuki_ftdi",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-02-11 18:21:19",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/587",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "Building the rosinstall file and the Docker container did not run into any issues. However, running the test scripts within the container did manifest a bug that was not the expected one. This is likely due to a missing dependency when building the Docker container. Following the issue at: https://github.com/robust-rosin/robust/issues/144\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_core",
        "hash": "45ee84aa1e920b26f8191763e20c10c5806ead60",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_ftdi/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2015-02-12 (00:18)"
    }
}
```
