### ISSUE TITLE
Missing Information in ROS Distribution Index

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#588]
```yaml
{
    "id": 588,
    "title": "Missing Information in ROS Distribution Index",
    "type": "weakness",
    "description": "For each ROS major version (ROS distribution / ROS release) there is a distribution index, an index that collects information about all packages that are considered to be part of that release. This index stores not only information about the binary release, but documentation and source code repository as well.\nThe entries for Kobuki repositories were missing source code information in this index. This information is useful, for instance, for users to download the latest source code for a specific package.\n",
    "cwe": "Missing Package Documentation (no CWE)",
    "cve": "None",
    "keywords": [
        "rosdistro",
        "index",
        "source"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/ros/rosdistro",
        "https://github.com/aliasrobotics/RVD/issues/588"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "ROS",
        "package": "yujinrobot/kobuki_desktop/kobuki_desktop | yujinrobot/kobuki_core/kobuki_core | yujinrobot/kobuki_soft/kobuki_soft",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-05-28 00:47:38",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/588",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "We decided to not reproduce this bug, as this is not really an interesting case from the perspective of software analysis. Besides, the fix occurs in the rosdistro repository, which does not contain a ROS package, and makes the reproduction process harder.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros/rosdistro/pull/4560",
        "repo": "https://github.com/ros/rosdistro",
        "hash": "e3c9bbcd9a3c05a5375375732d52e185cca5afb0",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "hydro/distribution.yaml"
        ],
        "languages": [
            "YAML"
        ],
        "time": "2014-05-28 (17:50)"
    }
}
```
