### ISSUE TITLE
ABI/API Incompatibility

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#589]
```yaml
{
    "id": 589,
    "title": "ABI/API Incompatibility",
    "type": "weakness",
    "description": "When the Gazebo simulator upgraded from version 1.9 to version 2.0 there were compatibility issues with Kobuki's plugin. For instance, some header files changed paths.\n",
    "cwe": "API Incompatibility (no CWE) #EVOLUTION",
    "cve": "None",
    "keywords": [
        "gazebo",
        "abi",
        "api",
        "compatibility"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/589"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "simulation plugin",
        "package": "yujinrobot/kobuki_desktop/kobuki_gazebo_plugins",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "2013-10-10 08:51:22",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/589",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "5abe7d4ae9f8fb323d4acb6fe131d87a82efef31",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_gazebo_plugins/include/kobuki_gazebo_plugins/gazebo_ros_kobuki.h",
            "kobuki_gazebo_plugins/src/gazebo_ros_kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-10-11 (03:36)"
    }
}
```
