### ISSUE TITLE
Missing Queue Sizes for Some Publishers

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#590]
```yaml
{
    "id": 590,
    "title": "Missing Queue Sizes for Some Publishers",
    "type": "weakness",
    "description": "When publishing or subscribing to a topic in ROS, the developer often declares a queue size to be associated with that publisher/subscriber.  The queues store messages temporarily, if the system is not fast enough to process every message before a new one arrives. In older versions of ROS, declaring the queue size was not mandatory when using the Python client libraries. As of ROS Indigo, this was kept optional for backward compatibility, but a warning is issued.  Not specifying the queue size is a problem because it changes the behaviour of the publisher, which might not be expected. When a queue size is not specified, publishing a message is done synchronously. On the other hand, if a queue size is specified, publishing a message is done asynchronously, which is more in line with the behaviour of the C++ libraries. Publishing synchronously is concerning, because if a subscriber is not fast enough to receive the message, the publisher blocks.\n",
    "cwe": "CWE-628: Function Call with Incorrectly Specified Arguments #EVOLUTION",
    "cve": "None",
    "keywords": [
        "missing arguments",
        "rospy",
        "publisher",
        "subscriber",
        "queue sizes"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers",
        "https://github.com/aliasrobotics/RVD/issues/590"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "test suite",
        "subsystem": "test suite",
        "package": "yujinrobot/kobuki/kobuki_testsuite | yujinrobot/kobuki/kobuki_node",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2014-08-08 06:28:25",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/590",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "Due to the renaming of the geometry_experimental repository to geometry2, the rosinstall file had to be manually changed to use the correct URIs. The test case strategy is straightforward. Replace the ROS Publisher with a class that crashes when the queue_size argument is not given. In order to use the faulty code directly, Python dynamic imports had to be used, due to the fact that the bugs reside in executable scripts, which are not part of the source code that is importable by standard means.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "dd40270d17cdd3e1729437f0988c0acb6c622d5e",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/scripts/getOdom2D.py",
            "kobuki_node/scripts/getYaw.py",
            "kobuki_testsuite/src/kobuki_testsuite/drift_estimation.py",
            "kobuki_testsuite/src/kobuki_testsuite/motion_rotate.py",
            "kobuki_testsuite/src/kobuki_testsuite/motion_travel_forward.py",
            "kobuki_testsuite/src/kobuki_testsuite/motion_wander.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2014-08-11 (06:13)"
    }
}
```
