### ISSUE TITLE
Missing Queue Sizes for Some Publishers

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#591]
```yaml
{
    "id": 591,
    "title": "Missing Queue Sizes for Some Publishers",
    "type": "weakness",
    "description": "When publishing or subscribing to a topic in ROS, the developer often declares a queue size to be associated with that publisher/subscriber.  The queues store messages temporarily, if the system is not fast enough to process every message before a new one arrives. In older versions of ROS, declaring the queue size was not mandatory when using the Python client libraries. As of ROS Indigo, this was kept optional for backward compatibility, but a warning is issued.  Not specifying the queue size is a problem because it changes the behaviour of the publisher, which might not be expected. When a queue size is not specified, publishing a message is done synchronously. On the other hand, if a queue size is specified, publishing a message is done asynchronously, which is more in line with the behaviour of the C++ libraries. Publishing synchronously is concerning, because if a subscriber is not fast enough to receive the message, the publisher blocks.\n",
    "cwe": "CWE-628: Function Call with Incorrectly Specified Arguments #EVOLUTION",
    "cve": "None",
    "keywords": [
        "missing arguments",
        "rospy",
        "publisher",
        "subscriber",
        "queue sizes"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers",
        "https://github.com/aliasrobotics/RVD/issues/591"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "dashboard",
        "subsystem": "specific application component",
        "package": "yujinrobot/kobuki_desktop/kobuki_dashboard",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2014-08-08 06:03:03",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/591",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "Building the rosinstall file using a link to the issue on GitHub ran into errors, as per issue https://github.com/robust-rosin/robust/issues/55. This was due to the fact that the kobuki_desktop was only released on ROS Indigo, but this issue was opened before the official release, and thus rosdistro did not know the repository at the time the bug was reported. In order to create the rosinstall file, a date had to be manually selected, after the release of the package into the distribution. Another issue surfaced when building the docker image, as it could not find tf2 packages. This was due to the repository being named `geometry_experimental` at the time this issue was reported, and having been renamed to `geometry2` later on. To fix this, the rosinstall file had to be patched manually. Cf. issue https://github.com/robust-rosin/robust/issues/63. Regarding the test case, the strategy is very straightforward. Since the bug is related to misuse of ROS primitives, the test script has to override said primitives (`rospy.Publisher` in this case) and fail whenever the wrong arguments are passed to it. The implementation of the test case faced an issue, however. Since the faulty original code used widgets from a GUI application, it cannot be called directly in the test case. This is due to the Qt library inhibiting initialization of widgets without initializing a GUI application first, but these cannot be initialized within Docker images, which provide no access to GUI primitives (X server). Thus, the final solution has to mimic the original code, but stripping the GUI-related parts.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "5ee65b061a4a919b2a32e80087f4cb3e51e924ed",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_dashboard/src/kobuki_dashboard/led_widget.py",
            "kobuki_dashboard/src/kobuki_dashboard/motor_widget.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2014-08-08 (11:25)"
    }
}
```
