### ISSUE TITLE
Compilation Error due to Missing File Inclusion

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#593]
```yaml
{
    "id": 593,
    "title": "Compilation Error due to Missing File Inclusion",
    "type": "weakness",
    "description": "When building the `yocs_navigator` package, a user experienced a C++ compilation error, stating that one of the header files was missing.  This header file declares some custom ROS messages. The ROS community uses CMake to declare compilation instructions, in order to build a ROS package. In CMake files, there is a macro/function to declare dependencies of a build target. A build target can be a library or an executable (e.g. a ROS node). CMake-generated makefiles ensure that the dependencies of a target are built before the target. In this case, a dependency was missing for the faulty build target.  The dependency generated custom ROS messages, among which was the missing file. In the end, it is possible that the file was not missing, but actually being built after the target (due to the missing dependency), causing the error.\n",
    "cwe": "Missing Include / Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "compilation error",
        "CMake",
        "dependencies"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://cmake.org/cmake/help/v3.0/command/add_dependencies.html",
        "https://github.com/aliasrobotics/RVD/issues/593"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "Navigation module",
        "subsystem": "motion",
        "package": "yujinrobot/yujin_ocs/yocs_navigator",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "2014-08-22 20:38:36",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/593",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "Building the rosinstall file using a link to the issue on GitHub ran into errors, due to the yocs_navigator package not being released at the time the issue was reported. In order to create the rosinstall file, a date had to be manually selected, after the release of the package into the distribution.\nAn issue surfaced when building the docker image, as it could not find tf2 packages. This was due to the repository being named `geometry_experimental` at the time this issue was reported, and having been renamed to `geometry2` later on. To fix this, the rosinstall file had to be patched manually. Cf. issue https://github.com/robust-rosin/robust/issues/63.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/yujin_ocs",
        "hash": "17560e98ef751714a352a5cee403fd3eb53c9fdb",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "yocs_navigator/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2014-08-25 (02:04)"
    }
}
```
