### ISSUE TITLE
Odometry Could Not Be Reset

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#595]
```yaml
{
    "id": 595,
    "title": "Odometry Could Not Be Reset",
    "type": "weakness",
    "description": "Odometry is the use of data from motion sensors to estimate change in position over time. The Kobuki driver has a function that is supposed to reset the odometry (bringing its position and rotation estimates back to zero). In this case, calling this function would not reset rotation at all, and the position would keep an offset. The cause for this bug is that IMU readings (for rotation) cannot be reset, and thus an offset had to be subtracted for every reading, after reset is called. Resetting the encoder readings (for position) is possible, but the observed offset came from accumulators that remained in another node, `robot_pose_ekf`. The Robot Pose EKF is used to estimate the 3D pose of a robot, based on (partial) pose measurements coming from different sources.  It uses an extended Kalman filter to combine various measurements.  The basic idea is to offer loosely coupled integration with different sensors, where sensor signals are received as ROS messages. Since `robot_pose_ekf` was not needed for Kobuki to provide correct odometry, the final solution also removed it from the launch sequences.\n",
    "cwe": "CWE-682: Incorrect Calculation #PHYSICAL",
    "cve": "None",
    "keywords": [
        "sensors",
        "imu",
        "encoders",
        "odometry",
        "ekf"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/yujinrobot/yujin_ocs/issues/7",
        "http://wiki.ros.org/robot_pose_ekf",
        "https://github.com/aliasrobotics/RVD/issues/595"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_node | yujinrobot/kobuki/kobuki_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-06-28 00:26:50",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/595",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "2f647af053c451e4248d7741c542f63511eee45e | a174dbbb9375d22828b0d7f4f41b7265978845c0 | 9c4835ad5b2eb3a4945f57076501b7699057ec66",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/include/kobuki_driver/kobuki.hpp",
            "kobuki_driver/include/kobuki_driver/modules/diff_drive.hpp",
            "kobuki_driver/src/driver/diff_drive.cpp",
            "kobuki_driver/src/driver/kobuki.cpp",
            "kobuki_node/include/kobuki_node/odometry.hpp",
            "kobuki_node/src/library/odometry.cpp",
            "kobuki_node/param/base.yaml",
            "kobuki_node/src/library/slot_callbacks.cpp",
            "kobuki_node/package.xml",
            "kobuki_node/launch/robot_with_tf.launch"
        ],
        "languages": [
            "C++",
            "YAML",
            "Launch XML",
            "Package XML"
        ],
        "time": "2013-08-21 (06:59)"
    }
}
```
