### ISSUE TITLE
Use of Deprecated and Removed Features

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#596]
```yaml
{
    "id": 596,
    "title": "Use of Deprecated and Removed Features",
    "type": "weakness",
    "description": "Kobuki's source code was using some features of the Boost libraries related to type casting that were marked as deprecated, and were later removed in a newer version of the libraries. This upgrade caused builds to fail. The fix was essentially a find and replace, since other (recommended) constructs existed to replace the deprecated ones.\n",
    "cwe": "CWE-477: Use of Obsolete Functions #EVOLUTION",
    "cve": "None",
    "keywords": [
        "deprecation",
        "boost",
        "type cast"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/596"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "simulation plugins",
        "package": "yujinrobot/kobuki_desktop/kobuki_gazebo_plugins",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "2014-02-28 00:52:29",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/596",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "An issue surfaced when building the Docker image, as it could not find tf2 packages. This was due to the repository being named `geometry_experimental` at the time this issue was reported, and having been renamed to `geometry2` later on. To fix this, the rosinstall file had to be patched manually. Cf. issue https://github.com/robust-rosin/robust/issues/63. An additional issue surfaced, also when building the Docker image. In this case, the package 'libpcl-1.7-all-dev' is reported as missing. This package is not distributed in the standard Ubuntu repositories for Ubuntu Precise, the distribution used to reproduce this bug.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/yujinrobot/kobuki_desktop/pull/26",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "9c8abeb81acb2d18a086ac18cd88a8cf6dd9e200",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_gazebo_plugins/src/gazebo_ros_kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2014-03-02 (15:03)"
    }
}
```
