### ISSUE TITLE
API Change Causes Incompatibility

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#597]
```yaml
{
    "id": 597,
    "title": "API Change Causes Incompatibility",
    "type": "weakness",
    "description": "The ROS rqt_plot tool was updated and its API changed, causing incompatibility problems in Kobuki's test suite.\n",
    "cwe": "API Incompatibility (no CWE)",
    "cve": "None",
    "keywords": [
        "rqt",
        "api",
        "incompatibility",
        "plot"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/597"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "test suite",
        "subsystem": "test suite",
        "package": "yujinrobot/kobuki_desktop/kobuki_qtestsuite",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "testing violation",
        "detected-by-method": "N/A",
        "date-reported": "2014-08-08 06:25:24",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/597",
        "reproducibility": "always",
        "trace": "PluginManager._load_plugin() could not load plugin \"kobuki_qtestsuite/Kobuki Test Suite\":\nTraceback (most recent call last):\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler.py\", line 98, in load\n    self._load()\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py\", line 54, in _load\n    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py\", line 71, in load\n    instance = plugin_provider.load(plugin_id, plugin_context)\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py\", line 71, in load\n    instance = plugin_provider.load(plugin_id, plugin_context)\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py\", line 60, in load\n    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py\", line 71, in load\n    instance = plugin_provider.load(plugin_id, plugin_context)\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py\", line 94, in load\n    return class_ref(plugin_context)\n  File \"/home/jihoonl/research/ros/kobuki/src/kobuki_desktop/kobuki_qtestsuite/src/kobuki_qtestsuite/testsuite.py\", line 43, in __init__\n    self._widget.setupUi()\n  File \"/home/jihoonl/research/ros/kobuki/src/kobuki_desktop/kobuki_qtestsuite/src/kobuki_qtestsuite/testsuite_widget.py\", line 43, in setupUi\n    self._ui.battery_profile_frame.setupUi(self._ui.configuration_dock.cmd_vel_topic_name())\n  File \"/home/jihoonl/research/ros/kobuki/src/kobuki_desktop/kobuki_qtestsuite/src/kobuki_qtestsuite/battery_profile_frame.py\", line 51, in setupUi\n    self._plot_widget.switch_data_plot_widget(FullSizeDataPlot(self._plot_widget))\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/rqt_plot/plot_widget.py\", line 150, in switch_data_plot_widget\n    self.data_plot.autoscroll(self.autoscroll_checkbox.isChecked())\nAttributeError: 'FullSizeDataPlot' object has no attribute 'autoscroll'\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "5ee65b061a4a919b2a32e80087f4cb3e51e924ed | 6df4bd7e92aea5cf3696b20861fca0ed413ece6e | 55e84a61e50d23be20f1d7abb4018a635370bff4",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_qtestsuite/src/kobuki_qtestsuite/battery_profile_frame.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/full_size_data_plot.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/gyro_drift_frame.py",
            "kobuki_qtestsuite/src/kobuki_qtestsuite/testsuite_widget.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2014-08-11 (06:02)"
    }
}
```
