### ISSUE TITLE
Missing Comment Token

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#598]
```yaml
{
    "id": 598,
    "title": "Missing Comment Token",
    "type": "weakness",
    "description": "ROS parameters (key-value pairs) can be loaded from YAML files. One such file was missing a line comment token, causing part of the text to be interpreted as YAML data, and loaded as a ROS parameter. There was no crash or error report because the text happened to contain a colon, which made it valid YAML syntax for the parser. The end result was a strangely named parameter showing up during operation.\n",
    "cwe": "Syntax Error (no CWE)",
    "cve": "None",
    "keywords": [
        "parameters",
        "yaml",
        "syntax",
        "comments"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/598"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_node",
        "languages": [
            "YAML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-30 04:41:49",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/598",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "Building the image ran into some issues, as per the following thread #177 on the issue tracker. The test strategy is straightforward. Just initialise a node and read the parameter that is created by mistake. The successful reading of this parameter should fail the test.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "b213df3324cd933ddfc1bbd7ef8dce50cc233d51",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/param/base.yaml"
        ],
        "languages": [
            "YAML"
        ],
        "time": "2013-08-30 (09:45)"
    }
}
```
