### ISSUE TITLE
Wrong Inertia and Center of Mass in Robot Description

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#599]
```yaml
{
    "id": 599,
    "title": "Wrong Inertia and Center of Mass in Robot Description",
    "type": "weakness",
    "description": "The URDF file for Kobuki's physical model assumed the center of mass to be in the center of the robot's cylinder body. This is wrong, since the battery was intentionally placed at the front of the robot to make it heavier at the front. The wrong placement of the robot's center of mass had the effect of having it constantly bouncing back and forth in the Gazebo simulator.\n",
    "cwe": "Wrong Robot Model (no CWE)",
    "cve": "None",
    "keywords": [
        "xacro",
        "urdf",
        "gazebo",
        "simulation"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/599"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_description",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-06-17 04:24:51",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/599",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "493e3f9c9f65fbf0283571ca92b89a7203e5f287",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_description/urdf/kobuki.urdf.xacro"
        ],
        "languages": [
            "URDF"
        ],
        "time": "2013-08-20 (10:22)"
    }
}
```
