### ISSUE TITLE
Add an Option to Reset Odometry Values

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#600]
```yaml
{
    "id": 600,
    "title": "Add an Option to Reset Odometry Values",
    "type": "weakness",
    "description": "The Kobuki plugin for Gazebo did not have an option to reset odometry values. Resetting odometry can be useful, for instance, to easily get the distance travelled by the robot from a specific reference point. This is also a feature that the real Kobuki has, so the simulation plugin should try to mimic it. The fix for this also fixed a small issue with IMU data processing, where some values were being recorded as zero, instead of the actual values.\n",
    "cwe": "Missing Features (no CWE)",
    "cve": "None",
    "keywords": [
        "simulation",
        "gazebo",
        "odometry",
        "imu"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/600"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "simulation plugin",
        "package": "yujinrobot/kobuki_desktop/kobuki_gazebo_plugins",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-26 06:56:30",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/600",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "496aac8304f6d3dae568e1559471ed6354fdfe92",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_gazebo_plugins/include/kobuki_gazebo_plugins/gazebo_ros_kobuki.h",
            "kobuki_gazebo_plugins/src/gazebo_ros_kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-08-26 (09:18)"
    }
}
```
