### ISSUE TITLE
Missing Dependency Causes Setup to Fail

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#601]
```yaml
{
    "id": 601,
    "title": "Missing Dependency Causes Setup to Fail",
    "type": "weakness",
    "description": "Kobuki has a package, `kobuki_ftdi` which contains utilities for flashing and enabling Kobuki's USB connection. One such utility copies a udev rule to enable the device to appear on `/dev/kobuki`. When users install Turtlebot and Kobuki packages on their system, they often do so with the deb packages for Ubuntu. However, `kobuki_ftdi` was not included in the main package, and when the users got to the point where they would set up the udev rule, the process would fail, since `kobuki_ftdi` was not found. This package is clearly not a compile time nor runtime dependency, however the solution was to declare it as both, so that users would have to install the package anyway.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "dependencies, setup, installation"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/kobuki_ftdi",
        "http://wiki.ros.org/turtlebot/Tutorials/hydro/Installation",
        "https://github.com/aliasrobotics/RVD/issues/601"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "package metadata",
        "package": "yujinrobot/kobuki/kobuki_node | yujinrobot/kobuki_core/kobuki_ftdi",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-10-09 09:00:42",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/601",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "9de969082a80944fa779a17a570877901289e31f",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/package.xml"
        ],
        "languages": [
            "Package XML"
        ],
        "time": "2013-10-09 (10:01)"
    }
}
```
