### ISSUE TITLE
Program Finishing Too Soon

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#602]
```yaml
{
    "id": 602,
    "title": "Program Finishing Too Soon",
    "type": "weakness",
    "description": "One of the demo applications for Kobuki was supposed to initialize it and let it emit a beep sound, to signal that everything was working as intended. However, the robot would not emit any sound because the program was unintentionally terminating before it had time to read all the necessary data. Adding a `sleep` for some seconds fixed the issue.\n",
    "cwe": "Wrong behavior: Exit too soon (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "sound",
        "initialization",
        "driver"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/602"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "demo",
        "subsystem": "driver",
        "package": "yujinrobot/kobuki/kobuki_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-05-31 05:20:00",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/602",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "5a44eadd3b6ef0f2cb29f057b3e1cdb93205c954",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_driver/src/test/initialisation.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-05-31 (08:09)"
    }
}
```
