### ISSUE TITLE
Wrong Metapackage Dependencies

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#603]
```yaml
{
    "id": 603,
    "title": "Wrong Metapackage Dependencies",
    "type": "weakness",
    "description": "Kobuki metapackages were declaring a list of dependencies (children) that did not correspond to the actual list of children they grouped.\n",
    "cwe": "Wrong Dependencies (no CWE)",
    "cve": "None",
    "keywords": [
        "metapackage",
        "package",
        "dependencies"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/Metapackages",
        "https://github.com/aliasrobotics/RVD/issues/603"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "metapackage",
        "package": "yujinrobot/kobuki/kobuki | yujinrobot/kobuki_core/kobuki_core",
        "languages": [
            "Package XML"
        ],
        "date-detected": "",
        "detected-by": "build system",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-31 02:02:52",
        "reported-by": "automatic",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/603",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_core | https://github.com/yujinrobot/kobuki",
        "hash": "fd6b589ccba8ed8531c66a806cb755074207a4c2 | 710e62408a0c6934e423411b9ae914fb26a3be49",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_core/package.xml",
            "kobuki/package.xml"
        ],
        "languages": [
            "Package XML"
        ],
        "time": "2013-08-31 (07:09)"
    }
}
```
