### ISSUE TITLE
Circular Package Dependencies Cause Build to Fail

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#604]
```yaml
{
    "id": 604,
    "title": "Circular Package Dependencies Cause Build to Fail",
    "type": "weakness",
    "description": "Two packages, `kobuki_node` and `kobuki_capabilities` had launch files with dependencies on the other package, causing a circular dependency. This led to failure of the build process.\n",
    "cwe": "Circular Dependencies (no CWE)",
    "cve": "None",
    "keywords": [
        "dependencies",
        "packages",
        "build"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/604"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "yujinrobot/kobuki/kobuki_node | yujinrobot/kobuki/kobuki_capabilities",
        "languages": [
            "Package XML"
        ],
        "date-detected": "",
        "detected-by": "build system",
        "detected-by-method": "N/A",
        "date-reported": "2014-07-24 23:23:35",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/604",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/yujinrobot/kobuki/pull/334",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "f95c3847d97fba46b6317e00ffd78ce352ec376f",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/package.xml"
        ],
        "languages": [
            "Package XML"
        ],
        "time": "2014-08-08 (01:42)"
    }
}
```
