### ISSUE TITLE
Assertion Error When Running on 32-bit Platform

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#605]
```yaml
{
    "id": 605,
    "title": "Assertion Error When Running on 32-bit Platform",
    "type": "weakness",
    "description": "Kobuki uses the Eigen library for linear algebra.  Some structures in Eigen need to be bit-aligned and some macros need to be present in the code for this to happen.  Adding the missing macros fixed most of the occurrences of the problem.\n",
    "cwe": "CWE-617: Reachable Assertion Violation",
    "cve": "None",
    "keywords": [
        "eigen",
        "bit-alignment",
        "assertions",
        "32-bit"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://eigen.tuxfamily.org/index.php?title=Main_Page",
        "http://eigen.tuxfamily.org/dox/TopicUnalignedArrayAssert.html",
        "https://github.com/aliasrobotics/RVD/issues/605"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "bumper to pointcloud converter",
        "subsystem": "specific application component",
        "package": "yujinrobot/kobuki/kobuki_bumper2pc",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "assertions",
        "detected-by-method": "N/A",
        "date-reported": "2013-05-15 07:58:23",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/605",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "a794de9b6567b69f6c4885a177d017685f518524 | 18b46dc557676adc00b9f17c09c3af5281b5ea88 | f62c63ff94ab65fb3218e647e3886636e250f189 | 193ba75ee7b08b8bdb09b5815e486948913e3442 | 936e46785de6ae1fc473ff670b07ab16016ab7ef",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_bumper2pc/include/kobuki_bumper2pc/kobuki_bumper2pc.hpp",
            "kobuki_auto_docking/include/kobuki_auto_docking/dock_drive.hpp",
            "kobuki_auto_docking/src/dock_drive.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-08-12 (09:03)"
    }
}
```
