### ISSUE TITLE
Multiple Simulated Robots Do Not Update Orientation

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#607]
```yaml
{
    "id": 607,
    "title": "Multiple Simulated Robots Do Not Update Orientation",
    "type": "weakness",
    "description": "When multiple Kobuki robots were spawned in the Gazebo simulator their translations would properly update their odometry, but rotations would not. The underlying issue was that every robot instance was using the same IMU sensor, instead of each having its own.\n",
    "cwe": "CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition') #RESOURCE",
    "cve": "None",
    "keywords": [
        "simulation",
        "gazebo",
        "imu",
        "naming",
        "threading",
        "multithreading",
        "concurrency"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/607"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "multi-robot simulation",
        "subsystem": "simulation plugin",
        "package": "yujinrobot/kobuki_desktop/kobuki_gazebo_plugins",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-09-23 09:51:09",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/607",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/yujinrobot/kobuki_desktop/pull/39",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "4115400a5a9b88bf65bb97a5d44a9a2a695faa55",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_gazebo_plugins/src/gazebo_ros_kobuki_loads.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-03-02 (08:03)"
    }
}
```
