### ISSUE TITLE
Bumpers Stopped Working In Simulation

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#608]
```yaml
{
    "id": 608,
    "title": "Bumpers Stopped Working In Simulation",
    "type": "weakness",
    "description": "Some logical error in the implementation of the Gazebo plugin caused the simulated bumpers to stop working properly.  No additional details are provided. The fix replaces some variables with boolean flags and moves the ordering of some statements.\n",
    "cwe": "Wrong behavior (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "bumper",
        "gazebo",
        "simulaton"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/608"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "simulation plugin",
        "package": "yujinrobot/kobuki_desktop/kobuki_gazebo_plugins",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-28 10:38:41",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/608",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "acd5bfbd5513fb915d54fe7662fb345237f18490",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_gazebo_plugins/include/kobuki_gazebo_plugins/gazebo_ros_kobuki.h",
            "kobuki_gazebo_plugins/src/gazebo_ros_kobuki.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2013-08-29 (04:29)"
    }
}
```
