### ISSUE TITLE
Outdated parameter file

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#609]
```yaml
{
    "id": 609,
    "title": "Outdated parameter file",
    "type": "weakness",
    "description": "The Kobuki (Turtlebot) robot has a graphical tool (Kobuki Dashboard) that shows the status of the various components of the robot and allows access to basic functionalities (e.g. LEDs). This tool runs as a ROS node that subscribes to the diagnostics aggregator node (ros/diagnostics/diagnostic_aggregator/aggregator_node). The diagnostics aggregator consumes a series of parameters from the ROS parameter server, in order to know which diagnostics to aggregate, how to process them and how to output them. Said parameters are initialized from a parameter file in YAML syntax. One of the parameters, `remove_prefix` represents a prefix that should be present in the names of incoming diagnostics sources. If there is no match, the diagnostics are not processed. This bug manifested because the parameter file used an old prefix that had not been changed. As a result, diagnostics were not being processed, and not shown in the dashboard. The fix is to simply change the values of `remove_prefix` in the parameter file to the correct ones.\n",
    "cwe": "Inconsistent naming (no CWE) #EVOLUTION: CWE-439",
    "cve": "None",
    "keywords": [
        "parameter",
        "rosparam",
        "yaml"
    ],
    "system": "kobuki",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/kobuki_dashboard",
        "http://wiki.ros.org/diagnostic_aggregator",
        "http://wiki.ros.org/Parameter%20Server",
        "http://wiki.ros.org/rosparam",
        "https://github.com/aliasrobotics/RVD/issues/609"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "diagnostics dashboard",
        "subsystem": "generic component",
        "package": "yujinrobot/kobuki/kobuki_node",
        "languages": [
            "rosparam YAML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-08-26 05:52:55",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/609",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/yujinrobot/kobuki",
        "hash": "8a729db54ee9a8b43f4634ab8052ddaa24d517fd",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_node/param/diagnostics.yaml"
        ],
        "languages": [
            "rosparam YAML"
        ],
        "time": "2014-08-26 (06:54)"
    }
}
```
