### ISSUE TITLE
Update Breaks Robot Visualization

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#610]
```yaml
{
    "id": 610,
    "title": "Update Breaks Robot Visualization",
    "type": "weakness",
    "description": "An update to the rviz tool broke the visualization for some robots, by requiring additional information in the models.\n",
    "cwe": "API Incompatibility (no CWE) #EVOLUTION",
    "cve": "None",
    "keywords": [
        "rviz",
        "visualization",
        "mesh",
        "compatibility"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/ros-visualization/rviz/issues/622",
        "https://github.com/aliasrobotics/RVD/issues/610"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "visualization",
        "subsystem": "visualization",
        "package": "turtlebot/turtlebot/turtlebot_description | turtlebot/turtlebot_create/create_description",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-03-29 (08:58)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/610",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/turtlebot/turtlebot/pull/66 | https://github.com/turtlebot/turtlebot_create/pull/7",
        "repo": "https://github.com/turtlebot/turtlebot | https://github.com/turtlebot/turtlebot_create",
        "hash": "8cf9d9710e9f2bfb1a7256e2ef292dd70138339c | 9299530eb77b9e8a2a18160fb6ece325d38abfbc",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "turtlebot_description/meshes/stacks/circles/68-02403-125_Spacer.dae",
            "turtlebot_description/meshes/stacks/circles/68-02421-8000-RA_Turtlebot_F-F_Standoff.dae",
            "turtlebot_description/meshes/stacks/circles/68-04552-1000-RA_Turtlebot_M-F_Standoff.dae",
            "turtlebot_description/meshes/stacks/circles/68-04552-2000-RA_Turtlebot_M-F_Standoff.dae",
            "turtlebot_description/meshes/stacks/circles/68-04556-RA_Kinect_Standoff_Assy.dae",
            "turtlebot_description/meshes/stacks/circles/plate_0_logo.dae",
            "turtlebot_description/meshes/stacks/circles/plate_1_logo.dae",
            "turtlebot_description/meshes/stacks/circles/plate_2_logo.dae",
            "turtlebot_description/robots/roomba_circles_asus_xtion_pro.urdf.xacro",
            "turtlebot_description/robots/roomba_circles_asus_xtion_pro.urdf.xacro",
            "turtlebot_description/robots/roomba_circles_kinect.urdf.xacro",
            "turtlebot_description/robots/roomba_circles_kinect.urdf.xacro",
            "turtlebot_description/urdf/stacks/circles.urdf.xacro",
            "create_description/meshes/create_body.dae",
            "create_description/urdf/create.urdf.xacro"
        ],
        "languages": [
            "xacro",
            "collada"
        ],
        "time": "2013-04-01 (04:36)"
    }
}
```
