### ISSUE TITLE
Node Does Not Support Namespaces

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#611]
```yaml
{
    "id": 611,
    "title": "Node Does Not Support Namespaces",
    "type": "weakness",
    "description": "A velocity smoother node for Kobuki's teleoperation was being used with remappings to global topic names.  A global name (starts with \"/\") does not change with ROS name resolution, which makes setups very inflexible. If a user wants to launch multiple robots, or simply launch a robot within a specific namespace, topic names may clash or end up disconnected. The use of global names is not a recommended practice, and relative names should be used instead.\n",
    "cwe": "Use of Global Names (no CWE)",
    "cve": "None",
    "keywords": [
        "names",
        "global names",
        "remaps",
        "topics"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/ROS/Concepts#Names.Graph_Resource_Names | http://wiki.ros.org/Names",
        "https://github.com/aliasrobotics/RVD/issues/611"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "teleoperation",
        "subsystem": "generic component",
        "package": "turtlebot/turtlebot/turtlebot_teleop",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-10-26 (10:29)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/611",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/turtlebot/turtlebot/pull/235",
        "repo": "https://github.com/turtlebot/turtlebot",
        "hash": "9ffffcaeca7dd5a1fbb327c7289b8a11f84da39f",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "turtlebot_teleop/launch/includes/velocity_smoother.launch.xml"
        ],
        "languages": [
            "Launch XML"
        ],
        "time": "2016-10-26 (13:56)"
    }
}
```
