### ISSUE TITLE
Circular Package Dependencies

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#612]
```yaml
{
    "id": 612,
    "title": "Circular Package Dependencies",
    "type": "weakness",
    "description": "Two packages from Turtlebot declared dependencies on each other, which caused errors in the build farm.\n",
    "cwe": "Circular Dependencies (no CWE)",
    "cve": "None",
    "keywords": [
        "dependencies",
        "package",
        "manifest",
        "build farm"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/buildfarm",
        "https://github.com/aliasrobotics/RVD/issues/612"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "core component",
        "package": "turtlebot/turtlebot/turtlebot_bringup | turtlebot/turtlebot/turtlebot_capabilities",
        "languages": "None",
        "date-detected": "",
        "detected-by": "build system",
        "detected-by-method": "N/A",
        "date-reported": "2015-01-06 (23:43)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/612",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "An issue surfaced when building the Docker image, as it could not find tf2 packages. This was due to the repository being named `geometry_experimental` at the time this issue was reported, and having been renamed to `geometry2` later on. To fix this, the rosinstall file had to be patched manually. Cf. issue https://github.com/robust-rosin/robust/issues/63.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/turtlebot/turtlebot",
        "hash": "339078942cf67457bc472e07a3e75e9895ebf2f7",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "turtlebot_bringup/package.xml",
            "turtlebot_capabilities/package.xml"
        ],
        "languages": [
            "Package XML"
        ],
        "time": "2015-01-09 (09:15)"
    }
}
```
