### ISSUE TITLE
Dashboard Crashes In ROS Kinetic

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#613]
```yaml
{
    "id": 613,
    "title": "Dashboard Crashes In ROS Kinetic",
    "type": "weakness",
    "description": "Turtlebot and Kobuki come with a dashboard program for live diagnostics.  This program worked well on previous versions of ROS, but users reported crashes when using it in ROS Kinetic and Ubuntu 16.04 (required by Kinetic). The issue is that the application's GUI was built on top of Qt4, but Ubuntu 16.04 uses Qt5 which changed the API and made it incompatible. On the programming language level the problem manifests as a missing dependency issue. A Python import of a module fails, because the module is not longer available under the same name in Qt5.\n",
    "cwe": "run-time dependency issue (no CWE) #EVOLUTION",
    "cve": "None",
    "keywords": [
        "qt",
        "diagnostics",
        "dashboard",
        "turtlebot",
        "api",
        "dependency"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://answers.ros.org/question/252837/cannot-launch-kobuki_dashboard-on-kinetic/?comment=253230#post-id-253230",
        "https://github.com/aliasrobotics/RVD/issues/613"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "diagnostics dashboard",
        "subsystem": "application-specific component",
        "package": "yujinrobot/kobuki_desktop/kobuki_dashboard",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2017-01-30 (23:27)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/613",
        "reproducibility": "always",
        "trace": "ImportError: cannot import name QMessageBox",
        "reproduction": "Building the Docker image requires the USE_OSRF_REPOS option. Testing the bug is straightforward. Since it is a Python import issue, it suffices for the unit test to import the affected files.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/yujinrobot/kobuki_desktop/pull/49",
        "repo": "https://github.com/yujinrobot/kobuki_desktop",
        "hash": "61a75df171e8ac8f34ed848456a7a267d4d9d3e3",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "kobuki_dashboard/src/kobuki_dashboard/battery_widget.py",
            "kobuki_dashboard/src/kobuki_dashboard/dashboard.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2017-02-22 (14:10)"
    }
}
```
