### ISSUE TITLE
No Support For Namespaces and Multiple Instances

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#614]
```yaml
{
    "id": 614,
    "title": "No Support For Namespaces and Multiple Instances",
    "type": "weakness",
    "description": "Camera processing nodes used hard-coded and global names, making it impossible to launch multiple instances in different namespaces, as the names would clash.\n",
    "cwe": "Use of Global Names (no CWE)",
    "cve": "None",
    "keywords": [
        "names",
        "remappings",
        "namespaces",
        "openni",
        "driver"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/614"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-drivers/openni-launch/openni-launch",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-07-26 (05:45)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/614",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-drivers/openni_launch/pull/3",
        "repo": "https://github.com/ros-drivers/openni_launch",
        "hash": "a482f8268042aa8fae0e73970ed2af5dfd01e5df",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "launch/includes/depth.launch",
            "launch/includes/depth_registered.launch",
            "launch/includes/ir.launch",
            "launch/includes/manager.launch",
            "launch/includes/processing.launch",
            "launch/includes/rgb.launch",
            "launch/openni.launch"
        ],
        "languages": [
            "Launch XML"
        ],
        "time": "2013-07-27 (02:39)"
    }
}
```
