### ISSUE TITLE
Image Processing Sometimes Does Not Receive Data

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#615]
```yaml
{
    "id": 615,
    "title": "Image Processing Sometimes Does Not Receive Data",
    "type": "weakness",
    "description": "One of Turtlebot's launch files launches a node that processes depth images and converts the point cloud data to a laser scan. This node had remappings that expected the images to arrive on a specific topic. However, depending on whether some options were set, the correct topic name could change. This scenario was not foreseen, and under those circumstances the node would not receive any images to process. The fix leveraged the ability to define conditional values in launch files to account for the different cases.\n",
    "cwe": "Wrong Remappings (no CWE)",
    "cve": "None",
    "keywords": [
        "launch",
        "arguments",
        "topics",
        "remappings",
        "camera",
        "depthimage",
        "laserscan"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/615"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "core component",
        "package": "turtlebot/turtlebot/turtlebot_bringup",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-10-16 (04:53)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/615",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/turtlebot/turtlebot",
        "hash": "3e32933c829e308600707a9f971334d13d1cbe19",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "turtlebot_bringup/launch/3dsensor.launch"
        ],
        "languages": [
            "Launch XML"
        ],
        "time": "2014-04-02 (08:50)"
    }
}
```
