### ISSUE TITLE
Launch File Not Working With Some Linux Distributions

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#616]
```yaml
{
    "id": 616,
    "title": "Launch File Not Working With Some Linux Distributions",
    "type": "weakness",
    "description": "One of Turtlebot's launch files launched a component that performed custom operative system checks, and crashed when it encountered Linux Mint and Linux Linaro.  ROS is tested and recommended for Ubuntu systems, and Linux Mint is a distribution based on Ubuntu that shares a great deal of its packages, and, in general, should not cause problems running ROS. The check for the Linux distribution name not being equal to Ubuntu, results in an exception being thrown.\n",
    "cwe": "OS-library incompatibility (no CWE)",
    "cve": "None",
    "keywords": [
        "os",
        "rosdep",
        "linux",
        "rocon",
        "variability",
        "exception"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/616"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "orchestration",
        "package": "robotics-in-concert/rocon_app_platform/rocon_app_manager | ros-infrastructure/rospkg/rospkg",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2015-01-07 (17:20)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/616",
        "reproducibility": "always",
        "trace": "Traceback (most recent call last):\n  File \"/opt/ros/indigo/lib/rocon_app_manager/rapp_manager.py\", line 19, in <module>\n    manager = rocon_app_manager.RappManager()\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/rocon_app_manager/rapp_manager.py\", line 68, in __init__\n    self._dependency_checker = rocon_app_utilities.DependencyChecker(self._indexer)\n  File \"/opt/ros/indigo/lib/python2.7/dist-packages/rocon_app_utilities/dependencies.py\", line 69, in __init__\n    self.installer_keys = self.installer_context.get_os_installer_keys(self.os_name)\n  File \"/usr/lib/python2.7/dist-packages/rosdep2/installers.py\", line 199, in get_os_installer_keys\n    raise KeyError(os_key)\nKeyError: 'linuxmint'\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/robotics-in-concert/rocon_app_platform/pull/270 | https://github.com/ros-infrastructure/rospkg/pull/78",
        "repo": "https://github.com/robotics-in-concert/rocon_app_platform | https://github.com/ros-infrastructure/rospkg",
        "hash": "d379385c4de4323318dbb1dd901ab43a24189c19 | 862254530e105aa6a3a0919dc3c9c06c1b4be8cd | 7a2a9038bdc4f643047360901b0f4f26b0d0ec79 | fceff44c1a5bd99c37f8643fa58a225c5999ec16 | a4f35ee51f0eb8f671173c65095b1a9c1963c5c3",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "rocon_app_manager/src/rocon_app_manager/rapp_manager.py",
            "src/rospkg/os_detect.py",
            "src/rosdep2/platforms/debian.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2015-01-22 (23:52)"
    }
}
```
