### ISSUE TITLE
No Laptop Battery Information Displaying

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#617]
```yaml
{
    "id": 617,
    "title": "No Laptop Battery Information Displaying",
    "type": "weakness",
    "description": "Turtlebot's dashboard application features an indicator for the remaining charge of the laptop controlling the robot. After an upgrade to more recent OS versions and laptops, this indicator stopped displaying information. This was due to a change in the OS layer where the battery information was moved, and thus the script that looked for it could not find it in the old location.\n",
    "cwe": "OS-library incompatibility (no CWE) #EVOLUTION",
    "cve": "None",
    "keywords": [
        "battery",
        "diagnostics",
        "dashboard",
        "ubuntu",
        "acpi"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/617"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific code",
        "application": "diagnostics dashboard",
        "subsystem": "specific application component",
        "package": "turtlebot/turtlebot/turtlebot_bringup | turtlebot/turtlebot/linux_hardware",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-10-04 (08:04)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/617",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/turtlebot/turtlebot/pull/104",
        "repo": "https://github.com/turtlebot/turtlebot",
        "hash": "0c0f53217bbd838d89f6be5584ae1b9f45106875 | 928306ba94acbfcc4e0ee61c7c8e432561b0824f",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "linux_hardware/scripts/laptop_battery.py",
            "turtlebot_bringup/launch/minimal.launch",
            "turtlebot_bringup/launch/minimal_with_appmanager.launch"
        ],
        "languages": [
            "Python",
            "Launch XML"
        ],
        "time": "2013-11-02 (04:24)"
    }
}
```
