### ISSUE TITLE
Missing Runtime Dependency

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#618]
```yaml
{
    "id": 618,
    "title": "Missing Runtime Dependency",
    "type": "weakness",
    "description": "One of Turtlebot's core packages was missing a runtime dependency in its manifest file, resulting in errors when trying to run the nodes.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "dependencies",
        "runtime",
        "launch"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/618"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "mobile robot",
        "subsystem": "core component",
        "package": "turtlebot/turtlebot/turtlebot_bringup",
        "languages": "None",
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2013-11-05 (17:28)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/618",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "geometry2\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/turtlebot/turtlebot",
        "hash": "891cb680e98694e63a55394140bffdcde43f3f5e",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "turtlebot_bringup/package.xml"
        ],
        "languages": [
            "Package XML"
        ],
        "time": "2013-11-06 (08:29)"
    }
}
```
