### ISSUE TITLE
No Image Coming From Camera

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#619]
```yaml
{
    "id": 619,
    "title": "No Image Coming From Camera",
    "type": "weakness",
    "description": "A missing runtime dependency crashed the image processing node, causing no images to be received from the camera.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "camera",
        "eigen",
        "dependencies",
        "runtime"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/619"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-perception/image_pipeline/depth_image_proc",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2014-06-12 (10:04)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/619",
        "reproducibility": "always",
        "trace": "[ INFO] [1402564815.530736554]: /camera/rgb/camera_info -> /camera/rgb/camera_info\n[ERROR] [1402564815.727176562]: Failed to load nodelet [/camera/depth_metric_rect] of type\n [depth_image_proc/convert_metric]: Failed to load library /opt/ros/indigo/lib//libdepth_image_proc.so.\n Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that\n names are consistent between this macro and your XML. Error string: Could not load library (Poco\n exception = libeigen_conversions.so: cannot open shared object file: No such file or directory)\n[FATAL] [1402564815.727410623]: Service call failed!\n",
        "reproduction": "An issue surfaced when building the Docker image, as it could not find tf2 packages. This was due to the repository being named `geometry_experimental` at the time this issue was reported, and having been renamed to `geometry2` later on. To fix this, the rosinstall file had to be patched manually. Cf. issue https://github.com/robust-rosin/robust/issues/63.\n",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-perception/image_pipeline/pull/79",
        "repo": "https://github.com/ros-perception/image_pipeline",
        "hash": "f01d9525901b75858047e6fa81e4efc92c7dfedc",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "depth_image_proc/package.xml"
        ],
        "languages": [
            "Package XML"
        ],
        "time": "2014-06-13 (01:12)"
    }
}
```
