### ISSUE TITLE
Environment Hooks Introduce Undocumented Dependency

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#620]
```yaml
{
    "id": 620,
    "title": "Environment Hooks Introduce Undocumented Dependency",
    "type": "weakness",
    "description": "ROS packages can make use of environment hooks -- shell scripts that are executed, for instance, to set up environment variables. In ROS Indigo, the core Turtlebot package introduced an environment hook that depended on another package that was not listed as a dependency in the package manifest. This caused error messages to be printed to the terminal if the user did not have the package installed. The fix was to move the faulty parts of the environment hook to the package they depended on.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "environment hooks",
        "catkin",
        "package",
        "dependencies"
    ],
    "system": "turtlebot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://answers.ros.org/question/253790/what-are-environment-hooks-in-catkin/",
        "https://github.com/aliasrobotics/RVD/issues/620"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "N/A",
        "subsystem": "scripts",
        "package": "turtlebot/turtlebot/turtlebot_bringup",
        "languages": "shell",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-09-11 (11:54)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/620",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/turtlebot/turtlebot | https://github.com/turtlebot/turtlebot_apps",
        "hash": "36ceb8dc37e0f930986cc86fe3ff2a9f1a930322 | 3ea2c306120774e8ed7e69e4e3fce3eca9f5426e",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "turtlebot_bringup/env-hooks/25.turtlebot.sh.em",
            "turtlebot_navigation/CMakeLists.txt",
            "turtlebot_navigation/env-hooks/25.turtlebot-navigation.sh.em"
        ],
        "languages": [
            "CMake",
            "shell"
        ],
        "time": "2014-09-16 (00:26)"
    }
}
```
