### ISSUE TITLE
Possibly inconclusive result when asking for RWS data

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#621]
```yaml
{
    "id": 621,
    "title": "Possibly inconclusive result when asking for RWS data",
    "type": "weakness",
    "description": "When using Robot Web Services (RWS) to ask the robot controller if a certain condition is true or false, then the current solution report false for all cases except when the data was received correctly and parsed to true. E.g. a network failure would mean that the condition is reported as false. In such cases it is more prudent to report the condition as unknown. This can be done by using a tri state Boolean as output instead of a normal bool.\n",
    "cwe": "Incorrect Data Parsing (no CWE) internal classification (cause): inconclusive result if e.g. communication failure internal classification (effect): inconclusive result will be reported\n",
    "cve": "None",
    "keywords": [
        "network",
        "communication",
        "parsing",
        "RWS"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://developercenter.robotstudio.com/webservice/api_reference",
        "https://github.com/aliasrobotics/RVD/issues/621"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "N/A",
        "application": "RWS interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-06-28 (13:52)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/621",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-07-03 (11:27)"
    }
}
```
