### ISSUE TITLE
Incorrect parsing of multiple RWS content

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#622]
```yaml
{
    "id": 622,
    "title": "Incorrect parsing of multiple RWS content",
    "type": "weakness",
    "description": "When using Robot Web Services (RWS) to extract resources from the different RWS services, then some of the resources might contain several interesting items. E.g. if asking for all mechanical units in the current robot system there might be more than one. The current parsing solution works best when extracting a single item, if there are multiple items then it is cumbersome. This can be solved by adding a proper XML and/or JSON parser.\n",
    "cwe": "Incorrect Data Parsing (no CWE) internal classification (cause): incorrect parsing of multiple RWS content internal classification (effect): data will not be parsed correctly\n",
    "cve": "None",
    "keywords": [
        "parsing",
        "RWS"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://developercenter.robotstudio.com/webservice/api_reference",
        "https://github.com/aliasrobotics/RVD/issues/622"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "N/A",
        "application": "RWS interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-04-10 (10:31)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/622",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-06-27 (16:45)"
    }
}
```
