### ISSUE TITLE
Incorrect parsing of RAPID record data

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#623]
```yaml
{
    "id": 623,
    "title": "Incorrect parsing of RAPID record data",
    "type": "weakness",
    "description": "When using Robot Web Services (RWS) to read RAPID record data, then the values are represented in a string format contatined between '[' and ']' and delimited by ',' characters. E.g. [TRUE, \"text string 1\", 0.1] The problem occurs when the text string contains e.g. delimiter characters.\n",
    "cwe": "Incorrect Data Parsing (no CWE) internal classification (cause): incorrect parsing of text strings internal classification (effect): data will not be parsed correctly\n",
    "cve": "None",
    "keywords": [
        "parsing",
        "RWS"
    ],
    "system": "confidential",
    "vendor": ABB,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://developercenter.robotstudio.com/webservice/api_reference",
        "https://github.com/aliasrobotics/RVD/issues/623"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "N/A",
        "application": "RWS interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-06-01 (09:14)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/623",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "unfixed"
    }
}
```
