### ISSUE TITLE
Incorrect handling of network communication failure

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#624]
```yaml
{
    "id": 624,
    "title": "Incorrect handling of network communication failure",
    "type": "weakness",
    "description": "The POCO C++ libraries that are utilized (for interacting with Robot Web Services (RWS) from ABB Robotics) requires that the communication streams are reset, if an error has occurred on the network. E.g. if the RWS server has been terminated unexpectedly. If the streams are not reset, then it is not possible to reuse them.\n",
    "cwe": "CWE-664: Improper Control of a Resource Through its Lifetime #RESOURCE internal classification (cause): reset not called after network failure internal classification (effect): not possible to reuse network connections\n",
    "cve": "None",
    "keywords": [
        "network",
        "communication",
        "RWS",
        "POCO"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://developercenter.robotstudio.com/webservice/api_reference",
        "https://pocoproject.org/",
        "https://github.com/aliasrobotics/RVD/issues/624"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "N/A",
        "application": "RWS interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-05-03 (14:36)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/624",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-05-04 (10:16)"
    }
}
```
