### ISSUE TITLE
Validation of user input to EGM

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#625]
```yaml
{
    "id": 625,
    "title": "Validation of user input to EGM",
    "type": "weakness",
    "description": "When communicating with the robot controller using Externally Guided Motion, then it is wise to always fill out the messages with data. E.g. if an EGM motion has been ordered for all axes, then data should be provided for all axes. If the user only set values for the first axis, then it is a good idea to fill out the remaining axes with the feedback values received from the robot controller.\n",
    "cwe": "CWE-20: Improper Input Validation internal classification (cause): incorrect validation of user input internal classification (effect): missing input values\n",
    "cve": "None",
    "keywords": [
        "input",
        "validation",
        "EGM"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "None",
        "https://github.com/aliasrobotics/RVD/issues/625"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "N/A",
        "application": "EGM interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-10-06 (14:01)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/625",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-10-07 (16:10)"
    }
}
```
