### ISSUE TITLE
Double deallocation of data

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#626]
```yaml
{
    "id": 626,
    "title": "Double deallocation of data",
    "type": "weakness",
    "description": "If a base class A has a vector containing smart pointers to an abstract class B, and then a class AA (inheriting from A) has data objects of a class BB (inheriting from B). And if pointers to AA's data objects are put into the vector, then during destruction of AA the data objects will be destructed twice which cause an exception. A solution is replace the vectors elements to be raw pointers instead of smart pointers.\n",
    "cwe": "CWE-664: Improper Control of a Resource Through its Lifetime #RESOURCE internal classification (cause): incorrect deallocation of data internal classification (effect): an exception will be thrown\n",
    "cve": "None",
    "keywords": [
        "deallocation"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "None",
        "https://github.com/aliasrobotics/RVD/issues/626"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "application-specific code",
        "application": "RWS interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-06-30 (10:23)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/626",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-07-04 (15:33)"
    }
}
```
