### ISSUE TITLE
New features unavailable in older systems

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#627]
```yaml
{
    "id": 627,
    "title": "New features unavailable in older systems",
    "type": "weakness",
    "description": "When adding the possibility to use features that have been added in new versions of Robot Web Services (RWS), then it will not be possible to use them with older systems. Currently, if using an older system version, then this will be attempted and reported as a failed communication. It might be prudent to check the current system's version and then report if a specific function is unavailable.\n",
    "cwe": "Incorrect Handling of Accessing Unavailable Features (no CWE) #EVOLUTION internal classification (cause): attempting to access features added in newer versions internal classification (effect): possibly inconclusive information reported to user\n",
    "cve": "None",
    "keywords": [
        "RWS"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://developercenter.robotstudio.com/webservice/api_reference",
        "https://github.com/aliasrobotics/RVD/issues/627"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "N/A",
        "application": "RWS interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-06-13 (11:41)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/627",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "unfixed"
    }
}
```
