### ISSUE TITLE
Incorrect joint position order used in trajectory generation

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#628]
```yaml
{
    "id": 628,
    "title": "Incorrect joint position order used in trajectory generation",
    "type": "weakness",
    "description": "Joint space trajectory generation uses the given initial and target joint positions in an incorrect order. The algorithm's input consists in, amongst other parameters, two instances of `sensor_msgs::JointState` class. This class contains an array of strings containing the joint names and another array containing the joint positions. The algorithm, which is internally used by a robot controller node, assumes that the initial and target joint states are provided in the same order, and only checks that both inputs contain the full set of joints for the given _group_. This is true in general, but under certain circumstances a different ordering might be used in the initial and target joint positions, resulting in highly unpredictable outcomes.\n",
    "cwe": "CWE-440: Expected Behavior Violation",
    "cve": "None",
    "keywords": [
        "jointstates",
        "joint ordering"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://docs.ros.org/api/sensor_msgs/html/msg/JointState.html",
        "https://github.com/aliasrobotics/RVD/issues/628"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "manipulator controller",
        "subsystem": "controller",
        "package": "core_manipulator_controller",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "None",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/628",
        "reproducibility": "sometimes",
        "trace": "TBD",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "CONFIDENTIAL",
        "hash": "96e2c6ce746e187ea4276360909e9a71773c3119",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "trajectory_generation.cpp",
            "utils.h"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-02-09 (16:43)"
    }
}
```
