### ISSUE TITLE
Incorrect cleanup of network resources

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#629]
```yaml
{
    "id": 629,
    "title": "Incorrect cleanup of network resources",
    "type": "weakness",
    "description": "When terminating the application unexpectedly by e.g. Ctrl-C, then the network resources are not properly released. If restarting the program immediately, then the same network ports might not be available for use and this cause exceptions to be thrown. This can be fixed by adding a cleanup function.\n",
    "cwe": "CWE-404: Improper Resource Shutdown or Release #RESOURCE internal classification (cause): no proper cleanup of network resources internal classification (effect): might make network resources unavailable for use\n",
    "cve": "None",
    "keywords": [
        "network",
        "cleanup"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://en.wikipedia.org/wiki/Unix_signal",
        "https://github.com/aliasrobotics/RVD/issues/629"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "application specific",
        "architectural-location": "N/A",
        "application": "EGM interface",
        "subsystem": "driver",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-12-07 (16:41)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/629",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repository": "CONFIDENTIAL",
        "hash": null,
        "license": [
            "closed source"
        ],
        "fix-in": [
            "CONFIDENTIAL"
        ],
        "languages": [
            "C++"
        ],
        "time": "2015-12-09 (14:20)"
    }
}
```
