### ISSUE TITLE
Image from the Kinect v2 is flipped

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#630]
```yaml
{
    "id": 630,
    "title": "Image from the Kinect v2 is flipped",
    "type": "weakness",
    "description": "The Kinect v2 is a camera providing images and depth data. The driver Freenect2 is used to access the images from that device. By default, the images provided by the camera + Freenect2 driver are \"mirrored\" or flipped by the vertical axis, which is not standard and/or expected by the application using the images.\n",
    "cwe": "CWE-137 Representation Errors #PHYSICAL",
    "cve": "None",
    "keywords": [
        "camera",
        "driver",
        "image",
        "representation",
        "format"
    ],
    "system": "confidential",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/OpenKinect/libfreenect2",
        "http://docs.opencv.org/2.4.13.2/modules/core/doc/operations_on_arrays.html?highlight=flip#cv2.flip",
        "http://www.ros.org/reps/rep-0118.html",
        "http://www.ros.org/reps/rep-0103.html",
        "https://github.com/aliasrobotics/RVD/issues/630"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "SLAM",
        "subsystem": "driver",
        "package": "robdream/kintinuous/kintinuous_ros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-03-13 (17:05)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/630",
        "reproducibility": "always",
        "trace": "NA",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "NA",
        "repo": "https://git.code.tecnalia.com/robdream/kintinuous/commit/22e4e4f44ed3ead6f9d2d863fcd9d6d677e771f3",
        "hash": "22e4e4f44ed3ead6f9d2d863fcd9d6d677e771f3",
        "license": [
            "Tecnalia"
        ],
        "fix-in": [
            "kintinuous_src/utils/Freenect2Reader.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-03-22 (11:46)"
    }
}
```
