### ISSUE TITLE
component not correctly initialized at activation

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#631]
```yaml
{
    "id": 631,
    "title": "component not correctly initialized at activation",
    "type": "weakness",
    "description": "A robot is providing an interface for pose-based control, i.e., it is ready to receive 6d pose request to move the robot.  Among the different ways to produce the pose target, the one of interest is deduced from user input provided by a joystick interface.  This component reads at launch the current pose of the robot, and waits then for joystick input to produce some motion requests. But if the robot is moved through other means, the joystick-based pose commands does not get the current robot pose updated. It is indeed only set at the component creation.  Thus, when the joystick-based pose generator is activated and receive joystick input, the target pose updated may be based on an old pose of the robot end effector, so that the robot will move back to a previous (and potentially far) pose.\n",
    "cwe": "Dangerous behavior: wrong position from joystick (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "driver",
        "joystick",
        "node life-cycle"
    ],
    "system": "shadow-robot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/631"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotic-specific or general issue",
        "architectural-location": "application-specific code",
        "application": "arm control",
        "subsystem": "driver | controller # (component getting joystick motion and deducing the desired 6D motion of the arm end effector)",
        "package": "shadow_robot/stiff_flop/sf_teleop/",
        "languages": "None",
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2015-12-04 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/631",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/shadow-robot/stiff_flop/issues/276",
        "repo": "https://github.com/shadow-robot/stiff_flop",
        "hash": "473ab5eb82487fb024458c0d709463fb3e046e34",
        "license": [
            "closed source"
        ],
        "fix-in": [
            "sf_teleop/CMAkelists.txt",
            "sf_teleop/package.xml",
            "sf_teleop/scripts/sf_teleop/sf_joystick_control.py"
        ],
        "languages": [
            "python"
        ],
        "time": "2015-12-07 (00:00)"
    }
}
```
