### ISSUE TITLE
Undeclared transitive dependencies to an external library

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#632]
```yaml
{
    "id": 632,
    "title": "Undeclared transitive dependencies to an external library",
    "type": "weakness",
    "description": "The file package.xml is essential for every ROS package and it contains among others the dependencies of the packages. CMakeList is also essential for every ROS package and it contains the information of the packages, which is needed for the buildsystem. In this example the dependency on \"joint_limits_interface\" is missing in the rosdep list and thus, the package could not be installed by \"rosdep install --from-path -i -y src\".  The main problem was an undeclared transitive dependency in gazebo_ros_control package. This could be solved by adding the dependency to the package.xml with the lines: <build_depend>joint_limits_interface</build_depend> <run_depend>joint_limits_interface</run_depend> ...and to CMakeList with the lines: catkin_package(... joint_limits_interface ...).\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing",
        "dependencies",
        "library",
        "package.xml",
        "CMakeList"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/package.xml",
        "http://wiki.ros.org/catkin/CMakeLists.txt",
        "https://github.com/aliasrobotics/RVD/issues/632"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "cob_control",
        "languages": "N/A",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-12-03 (09:04)",
        "reported-by": "developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/632",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-simulation/gazebo_ros_pkgs/pull/343",
        "repo": "https://github.com/ros-simulation/gazebo_ros_pkgs",
        "hash": "e9ed0f8e157398621987bd61e2d78683cd945c2b",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "cob_command_tools/cob_script_server/package.xml"
        ],
        "languages": [
            "package.xml"
        ],
        "time": "2015-08-08 (10:05)"
    }
}
```
