### ISSUE TITLE
Xacro broken because of missing argument

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#633]
```yaml
{
    "id": 633,
    "title": "Xacro broken because of missing argument",
    "type": "weakness",
    "description": "A xacro can reference to other xacros with the ability to pass arguments. In the example a child-xacro was changed by adding an additional argument. However, the parent-xacro (includes the edited child-xacro) was not updated. Therefore it misses the newly introduced argument. The consequence is that the xacro is broken and one can not generate an Urdf out of it anymore.  In the example the child-xacro is named \"schunk_pg70\", the parent \"cob3-9\" and the new argument is \"has_podest\".  The reason for this issue is that there are several parent-xacro using the child-xacro and one needs to update all the parent-xacros, which has been forgotten in the example.  The problem was solved by adding the newly introduced argument to the parent-xacro at the respective call of the child-xacro.\n",
    "cwe": "CWE-685: Wrong Number of Function Arguments #EVOLUTION",
    "cve": "None",
    "keywords": [
        "xacro",
        "arguments",
        "update",
        "outdated"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/xacro",
        "https://github.com/aliasrobotics/RVD/issues/633"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "cob robots",
        "subsystem": "robot description",
        "package": "cob_robots",
        "languages": "xacro",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-11-04 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/633",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ipa320/cob_robots/pull/553",
        "repo": "https://github.com/ipa320/cob_robots",
        "hash": "b826eaeae5c8dc548ac2c97002725c7a8131137e",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "https://github.com/ipa-fmw/cob_robots/blob/b826eaeae5c8dc548ac2c97002725c7a8131137e/cob_hardware_config/cob3-9/urdf/cob3-9.urdf.xacro"
        ],
        "languages": [
            "xacro"
        ],
        "time": "2016-11-10 (00:00)"
    }
}
```
