### ISSUE TITLE
Missing dependencies to an external library

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#634]
```yaml
{
    "id": 634,
    "title": "Missing dependencies to an external library",
    "type": "weakness",
    "description": "The file package.xml is essential for every ROS package and it contains among others the dependencies of the packages.  In this example the dependency on \"ipython\" is missing in the rosdep list and thus, there should be an error by e.g. installing the package from apt-get install.  This could be solved by adding the dependency to the package.xml with the line <run_depend>ipython</run_depend>.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing",
        "dependencies",
        "library",
        "package.xml"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/package.xml",
        "https://github.com/aliasrobotics/RVD/issues/634"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "cob_script_server",
        "languages": "N/A",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-05-20 (16:52)",
        "reported-by": "developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/634",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/ipa320/cob_command_tools",
        "hash": "ac6a18190ef889f464a63ce6056100ce6da10b4d",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "cob_command_tools/cob_script_server/package.xml"
        ],
        "languages": [
            "XML"
        ],
        "time": "2014-08-26 (08:57)"
    }
}
```
