### ISSUE TITLE
Missing dependencies to gencpp, which is important for ROS messages and services

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#635]
```yaml
{
    "id": 635,
    "title": "Missing dependencies to gencpp, which is important for ROS messages and services",
    "type": "weakness",
    "description": "CMakeList is essential for every ROS package and it contains the information of the packages, which is needed for the buildsystem. If you have a target which depends on some other target you need to add an explicit dependency so that they are built in the correct order. In the example the node \"cob_obstacle_distance\" depends on \"cob_obstacle_distance_gencpp\". Gencpp is apparently a helper when adding some msgs as dependencies to a target node.  However, the node was linking to \"cob_srvs_gencpp\" which might have been correct at a former time (Apparently, the package has been renamed).  This could be solved by naming the dependency \"${PROJECT_NAME}_gencpp\". The \"PROJECT_NAME\" corresponds to the package name and thus, one can have a generic name, which is independent of the package name.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing",
        "dependencies",
        "gencpp",
        "project_name",
        "CMakeLists"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/CMakeLists.txt",
        "http://wiki.ros.org/gencpp",
        "https://github.com/aliasrobotics/RVD/issues/635"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "cob_obstacle_distance",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-08-03 (14:15)",
        "reported-by": "developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/635",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ipa320/cob_control/pull/47",
        "repo": "https://github.com/ipa320/cob_control",
        "hash": "ca7b536390bcf76bf4ab6e62354c52bd51fb1ece",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "cob_control/cob_obstacle_distance/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2015-08-04 (13:09)"
    }
}
```
