### ISSUE TITLE
Topic names not consistent between hardware and simulation

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#636]
```yaml
{
    "id": 636,
    "title": "Topic names not consistent between hardware and simulation",
    "type": "weakness",
    "description": "In ROS it is possible to work equivalent with hardware and simulation(in Gazebo).  A camera can be simulated in Gazebo with a plugin. This plugin has parameters which can be set in the URDF or Xacro. One parameter is e.g. the topic-name on which it publishes the image.  The real robot uses topic-names which are defined in the driver-node for the camera.  Therefore, one has to make sure to use consistent naming conventions to assure the exchangability between hardware and simulation.  In the example the camera topics in simulation do not match the topic names on real hardware.  The problem is solved by introducing consistent naming.\n",
    "cwe": "inconsistent naming",
    "cve": "None",
    "keywords": [
        "xacro",
        "gazebo",
        "topic",
        "name",
        "inconsistency"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/xacro",
        "http://gazebosim.org/tutorials?tut=ros_gzplugins",
        "https://github.com/aliasrobotics/RVD/issues/636"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific",
        "application": "cob common",
        "subsystem": "robot description",
        "package": "cob_common",
        "languages": "xacro",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-11-04 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/636",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ipa320/cob_common/pull/179",
        "repo": "https://github.com/ipa320/cob_common",
        "hash": "43705f74847ce09edb971adb50d9e47",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "https://github.com/ipa320/cob_common/pull/179/commits/43705f74847ce09edb971adb50d9e47b14f944cf"
        ],
        "languages": [
            "xacro"
        ],
        "time": "2015-11-20 (00:00)"
    }
}
```
