### ISSUE TITLE
Include directory to header file missing

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#637]
```yaml
{
    "id": 637,
    "title": "Include directory to header file missing",
    "type": "weakness",
    "description": "CMakeList is essential for every ROS package and it contains the information of the packages, which is needed for the buildsystem. Prior to specifying targets, you need to specify where resources can be found for said targets, specifically header files and libraries. The argument to include_directories should be the *_INCLUDE_DIRS variables generated by your find_package calls and any additional directories that need to be included. In the example the include to the \"${catkin_INCLUDE_DIRS}\" was missing and thus, a header file, in this case \"ScriptAction.h\" could not be found in this case by Jenkins. The problem was solved by adding \"include_directories(${catkin_INCLUDE_DIRS})\" to the CMakeLists.\n",
    "cwe": "Missing Include / Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "include directories",
        "CMakeLists"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/CMakeLists.txt; 7.3",
        "https://github.com/aliasrobotics/RVD/issues/637"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "cob_teleop",
        "languages": "N/A",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-09-16 (14:58)",
        "reported-by": "developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/637",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ipa320/cob_command_tools/pull/127",
        "repo": "https://github.com/ipa320/cob_command_tools",
        "hash": "28c23cd13e5cbade9776b496518facc07cef59f2",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "cob_command_tools/cob_teleop/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2015-11-24 (19:36)"
    }
}
```
