### ISSUE TITLE
Install tags missing or wrong

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#638]
```yaml
{
    "id": 638,
    "title": "Install tags missing or wrong",
    "type": "weakness",
    "description": "CMakeList is essential for every ROS package and it contains the information of the packages, which is needed for the buildsystem. After build time, targets are placed into the devel space of the catkin workspace.  However, often we want to install targets to the system so that they can be used by others or for a system-level installation. Therefore, one needs to specify where targets should end up with the CMake install() function.  The argument \"DIRECTORY\" is used to install e.g. resources like launchfiles to the global path \"${CATKIN_PACKAGE_SHARE_DESTINATION}\".  Therefore, for compiling/installing a package it makes a difference if catkin_make or catkin_make install is used. For example if the programm/packages works fine for catkin_make this does not mean that also catkin_make install works. For catkin_make install one has to particularly name every resources that should get into the install space and so it is easy to make errors. Also, if a packages gets updated one has to update the install tragets accordingly. In the example a file- and also a folder-name inside a package has changed but the install targets have not been updated. Consequently, the installation of the the package would be incomplete. The problem was solved by updating the names of the install targets accordingly.\n",
    "cwe": "Missing Installation Dependencies (no CWE) #EVOLUTION: CWE-439",
    "cve": "None",
    "keywords": [
        "install targets",
        "CMakeLists"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/CMakeLists.txt; 11",
        "https://github.com/aliasrobotics/RVD/issues/638"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "cob_android",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-08-03 (10:09)",
        "reported-by": "developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/638",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ipa320/cob_android/pull/8",
        "repo": "https://github.com/ipa320/cob_android",
        "hash": "79867c88acc64342f061e6324ed6b84ca7e0773d",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "cob_android/cob_android_msgs/CMakeLists.txt",
            "cob_android/cob_android_script_server/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2015-08-04 (16:26)"
    }
}
```
