### ISSUE TITLE
Hardcoded namespace because name is defined global

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#639]
```yaml
{
    "id": 639,
    "title": "Hardcoded namespace because name is defined global",
    "type": "weakness",
    "description": "Parameter-names are hardcoded. In the example a parameter is named \"/sound_controller/mode\".  There are four types of Graph Resource Names in ROS: base, relative, global, and private. Names that start with a \"/\" are global -- they are considered fully resolved. Global names should be avoided as much as possible as they limit code portability. An error might occure due to the following scenario: The node, which was the global namespace is used within a group tag in a roslaunch file. The group-name is written before every path-name, but not if the path-name is defined globally. This could cause a mismatch of names if not handled correctly.\n",
    "cwe": "Use of Global Names (no CWE)",
    "cve": "None",
    "keywords": [
        "namespace",
        "hardcoded",
        "parameter",
        "global"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/Names",
        "http://wiki.ros.org/roslaunch/XML/group",
        "https://github.com/aliasrobotics/RVD/issues/639"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "cob drivers",
        "subsystem": "driver",
        "package": "cob_drivers",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-04-07 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/639",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ipa320/cob_driver/pull/274",
        "repo": "https://github.com/ipa320/cob_driver",
        "hash": "151897840540e8dd662cf6c8c77e5613c84e3424",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "https://github.com/ipa-fxm/cob_driver/blob/151897840540e8dd662cf6c8c77e5613c84e3424/cob_sound/ros/src/sound.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2016-04-07 (00:00)"
    }
}
```
