### ISSUE TITLE
Missing dependencies to an external library

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#640]
```yaml
{
    "id": 640,
    "title": "Missing dependencies to an external library",
    "type": "weakness",
    "description": "The file package.xml is essential for every ROS package and it contains among others the dependencies of the packages.  In this example the dependency on \"pynotify\" is missing in the rosdep list and thus, there is an error by installing the package from apt-get install.  This could be solved by removing the dependencies inside the python script, which was using the library, since it was not required anymore. Otherwise, one would have needed to add the dependency to the package.xml.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing",
        "dependencies",
        "library",
        "package.xml"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/package.xml",
        "https://github.com/aliasrobotics/RVD/issues/640"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "cob_command_gui",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2015-01-14 (15:17)",
        "reported-by": "developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/640",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ipa320/cob_command_tools/pull/84",
        "repo": "https://github.com/ipa320/cob_command_tools",
        "hash": "c8091b68c69eeae0bb7777ad6fa44d644c20f96c",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "cob_command_tools/cob_command_gui/src/knoeppkes.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2015-03-13 (16:21)"
    }
}
```
