### ISSUE TITLE
Individual ROS-packages of Metapackage are outdated on local system

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#641]
```yaml
{
    "id": 641,
    "title": "Individual ROS-packages of Metapackage are outdated on local system",
    "type": "weakness",
    "description": "The motor for the tray of CoB-3 is not moving. The reason for the error is that certain ROS packages are outdated on the local system. This happened since updating the metapackage does not update the individual packages. Metapackages are specialized Packages in ROS (and catkin). They do not install files (other than their package.xml manifest) and they do not contain any files usually found in packages. A metapackage simply references one or more related packages which are loosely grouped together. In this example the metapackage used is \"ros_control\" and the outdated packages are \"controller_manager\" and \"hardware_interface\".  This error could be fixed by updating the outdated ROS packages.\n",
    "cwe": "Wrong behavior (no CWE) #EVOLUTION CWE-439 #PHYSICAL",
    "cve": "None",
    "keywords": [
        "metapackage",
        "package",
        "update",
        "outdated"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/Metapackages",
        "https://github.com/ros-controls/ros_control",
        "https://github.com/aliasrobotics/RVD/issues/641"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "ros control",
        "subsystem": "motion",
        "package": "ros_control",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-04-18 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/641",
        "reproducibility": "rare",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/ipa320/cob_robots/tree/indigo_dev/cob_bringup",
        "hash": null,
        "license": [
            "LGPL"
        ],
        "fix-in": [],
        "languages": [],
        "time": "unfixed"
    }
}
```
