### ISSUE TITLE
Missing dependencies to gencpp, which is important for ROS messages and services

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#642]
```yaml
{
    "id": 642,
    "title": "Missing dependencies to gencpp, which is important for ROS messages and services",
    "type": "weakness",
    "description": "CMakeList is essential for every ROS package and it contains the information of the packages, which is needed for the buildsystem. If you have a target which depends on some other target you need to add an explicit dependency so that they are built in the correct order. In the example the node \"output_publisher\" depends on \"cob_srvsgencpp\", but the dependency was missing.  Gencpp is apparently a helper when adding some msgs as dependencies to a target node.  This could be solved by naming the dependency \"cob_srvs_gencpp\". Even better would be to name it \"${PROJECT_NAME}_gencpp\". The \"PROJECT_NAME\" corresponds to the package name and thus, one can have a generic name, which is independent of the package name.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "missing",
        "dependencies",
        "gencpp",
        "project_name",
        "CMakeLists"
    ],
    "system": "care-o-bot",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/CMakeLists.txt",
        "http://wiki.ros.org/gencpp",
        "https://github.com/aliasrobotics/RVD/issues/642"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "N/A",
        "subsystem": "specific application component",
        "package": "cob_twist_controller",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-07-22 (15:37)",
        "reported-by": "developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/642",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/thiagodefreitas/cob_control/commit/105dc16ffe0b9dba294aabea0c18052cd281bde0",
        "repo": "https://github.com/ipa320/cob_control",
        "hash": "105dc16ffe0b9dba294aabea0c18052cd281bde0",
        "license": [
            "LGPL"
        ],
        "fix-in": [
            "cob_control/cob_twist_controller/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2014-11-21 (12:57)"
    }
}
```
