### ISSUE TITLE
Motoman robot can move after estop release

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#643]
```yaml
{
    "id": 643,
    "title": "Motoman robot can move after estop release",
    "type": "weakness",
    "description": "The problem occurs in the following scenario: Running the Motoman ROS-Init program and starting a process that sends a trajectory to the Motoman driver and move the robot. Estop the robot on the teach pendant. Pull up the estop. Send a new trajectory. The robot will turn on and move.  This is very unsafe and dangerous.\n",
    "cwe": "Dangerous behavior: move after stop (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "driver",
        "motoman"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/643"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific code",
        "application": "industrial robot arm",
        "subsystem": "motion",
        "package": "ros-industrial/motoman/motoman_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2017-03-15 (08:02)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/643",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 155,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_driver/include/motoman_driver/joint_trajectory_streamer.h",
            "motoman_driver/src/joint_trajectory_streamer.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-03-21 (02:46)"
    }
}
```
