### ISSUE TITLE
Missing dependency to catkin

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#644]
```yaml
{
    "id": 644,
    "title": "Missing dependency to catkin",
    "type": "weakness",
    "description": "The package.xml describes the build, run-time and buildtools dependencies to a package. In the Motoman Metapackage there is a missing buildtool depenency to catkin, the ROS buildtool.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "catkin",
        "buildtool",
        "dependency"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/644"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "industrial N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman",
        "languages": [
            "XML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-01 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/644",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 3,
        "repo": "https://github.com/ros-industrial/motoman/",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman/package.xml"
        ],
        "languages": [
            "XML"
        ],
        "time": "2013-08-07 (20:49)"
    }
}
```
