### ISSUE TITLE
ASCII STL file beginning with characters "solid"

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#645]
```yaml
{
    "id": 645,
    "title": "ASCII STL file beginning with characters \"solid\"",
    "type": "weakness",
    "description": "ASCII STL files are supposed to be designated by the first 5 lines reading \"solid\" in ASCII. The following binary STL files start with \"solid\" and they shouldn't.\n",
    "cwe": "CWE-172: Encoding Error",
    "cve": "None",
    "keywords": [
        "STL",
        "robot description"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/645"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman | ros-industrial/motoman/motoman_mh5_support",
        "languages": [
            "ASCII STL"
        ],
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2015-04-03 (06:24)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/645",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 77,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_mh5_support/meshes/mh5/visual/MH5_BASE_AXIS.stl",
            "motoman_mh5_support/meshes/mh5/visual/MH5_B_AXIS.stl",
            "motoman_mh5_support/meshes/mh5/visual/MH5_L_AXIS.stl",
            "motoman_mh5_support/meshes/mh5/visual/MH5_R_AXIS.stl",
            "motoman_mh5_support/meshes/mh5/visual/MH5_S_AXIS.stl",
            "motoman_mh5_support/meshes/mh5/visual/MH5_T_AXIS.stl",
            "motoman_mh5_support/meshes/mh5/visual/MH5_U_AXIS.stl"
        ],
        "languages": [
            "ASCII STL"
        ],
        "time": "2016-01-23 (00:00)"
    }
}
```
