### ISSUE TITLE
Python script not included in debian build

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#646]
```yaml
{
    "id": 646,
    "title": "Python script not included in debian build",
    "type": "weakness",
    "description": "The file 'move_to_joint.py' is available when building the motoman package from source, but it's missing when installing the package as a binary install.\n",
    "cwe": "Missing Installation Dependencies (no CWE)",
    "cve": "None",
    "keywords": [
        "CMakeLists.txt",
        "Debian"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/646"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman/",
        "languages": "None",
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2016-09-06 (17:48)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/646",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/gavanderhoorn/motoman",
        "hash": "5a10873b8d0ee01f457996840dde8d2d2daaf24f",
        "license": null,
        "fix-in": [
            "motoman_driver/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2016-09-06 (18:10)"
    }
}
```
