### ISSUE TITLE
Missing dependency on Motoman Messages

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#648]
```yaml
{
    "id": 648,
    "title": "Missing dependency on Motoman Messages",
    "type": "weakness",
    "description": "The motoman driver package depends on its own special message type: 'motoman_msgs'.  The dependencies to this message type is missing for the motoman package.\n",
    "cwe": "Missing Include / Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "dependencies",
        "motoman",
        "messages"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/648"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman | ros-industrial/motoman/motoman_driver",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "2015-04-14 (01:37)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/648",
        "reproducibility": "always",
        "trace": "N/A",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 63,
        "repo": "https://github.com/JeremyZoss/motoman | https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_driver/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2015-04-14 (01:48)"
    }
}
```
