### ISSUE TITLE
SDA10f model meshes are malformed

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#649]
```yaml
{
    "id": 649,
    "title": "SDA10f model meshes are malformed",
    "type": "weakness",
    "description": "When loading the SDA10F robot model in rviz, it shows the warning that the single meshes are 'malformed', because they start with the word 'solid' to indicate it is an ASCII file, but it does not contain the word 'endsolid'.\n",
    "cwe": "CWE-172: Encoding Error",
    "cve": "None",
    "keywords": [
        "SDA10F",
        "mesh",
        "visualization"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/649"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "visualization",
        "package": "ros-industrial/motoman/motoman_sda10f_support",
        "languages": "None",
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2016-08-24 (20:28)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/649",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/gavanderhoorn/motoman",
        "hash": "57b7a995dfdcf025d6394123eb87896853a6aadf",
        "license": null,
        "fix-in": [
            "motoman_sda10f_support/meshes/sda10f/visual/motoman_axis_b1.stl",
            "motoman_sda10f_support/meshes/sda10f/visual/motoman_base.stl"
        ],
        "languages": null,
        "time": "2016-08-29 (13:15)"
    }
}
```
