### ISSUE TITLE
Incorrect values for joint limits in sia20d package

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#650]
```yaml
{
    "id": 650,
    "title": "Incorrect values for joint limits in sia20d package",
    "type": "weakness",
    "description": "The position limits for the joints joint_s, joint_r and joint_t for the SIA20 are set to exactly 3.1416 or -3.1416, but from the data sheet the limits for these joints are exactly Pi. The values appear to be rounded up, which gives the possibility for the robot to try to reach positions, which are physically not reachable.\n",
    "cwe": "Wrong constant (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "robot arm",
        "joint limits",
        "robot description"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://www.motoman.com/industrial-robots/sia20d",
        "https://github.com/aliasrobotics/RVD/issues/650"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "industrial robot arm",
        "subsystem": "motion",
        "package": "ros-industrial/motoman | ros-industrial/motoman/sia20d_support | ros-industrial/motoman/sia10d_support | ros-industrial/motoman/sia10f_support",
        "languages": [
            "XML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-06-13 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/650",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/gavanderhoorn/motoman",
        "hash": "93a9abae92b51ed79b6909397940e26d379eaa94",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_sia20d_support/urdf/sia20d.urdf",
            "motoman_sia20d_support/urdf/sia20d_macro.xacro"
        ],
        "languages": [
            "urdf",
            "xacro"
        ],
        "time": "2016-06-19 (00:00)"
    }
}
```
