### ISSUE TITLE
Motoman starts next command after pausing it

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#651]
```yaml
{
    "id": 651,
    "title": "Motoman starts next command after pausing it",
    "type": "weakness",
    "description": "A stop_motion command or an empty trajectory command will make the robot stop. But if another message comes in afterwards, the robot will simply execute this next command.  There is no way to 'pause' the robot and wait for a 'go' again.\n",
    "cwe": "Dangerous behavior: resume from paused state (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "driver",
        "motoman"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/651"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman/motoman_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2017-03-06 (21:43)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/651",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 153,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_driver/include/motoman_driver/industrial_robot_client/joint_trajectory_action.h",
            "motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "2017-03-07 (16:28)"
    }
}
```
