### ISSUE TITLE
Directory names with mixed case

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#652]
```yaml
{
    "id": 652,
    "title": "Directory names with mixed case",
    "type": "weakness",
    "description": "The directories Inform and MotoPlus are mixed case, all other directories are lowercase. The dx100 package has directories with the same names, but in all lowercase.\n",
    "cwe": "inconsistent naming",
    "cve": "None",
    "keywords": [
        "mixed case",
        "naming convention",
        "lowercase"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/652"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman | ros-industrial/motoman/motoman_mh5_support | ros-industrial/motoman/motoman_sda10f_support | ros_industrial/motoman/motoman_sia10d_support | ros-industrial/motoman/motoman_sia20d_support | ros-industrial/motoman/motoman_sia5d_support",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-26 (12:01)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/652",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 12,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ros-industrial/motoman",
            "ros-industrial/motoman/motoman_mh5_support",
            "ros-industrial/motoman/motoman_sda10f_support",
            "ros_industrial/motoman/motoman_sia10d_support",
            "ros-industrial/motoman/motoman_sia20d_support",
            "ros-industrial/motoman/motoman_sia5d_support"
        ],
        "languages": null,
        "time": "2014-09-02 (11:31)"
    }
}
```
