### ISSUE TITLE
Wrong transform in MH5

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#653]
```yaml
{
    "id": 653,
    "title": "Wrong transform in MH5",
    "type": "weakness",
    "description": "Visualizing the Robot Model described in the xacro and overlaying the TF frames, it looks like the position from the last link - link_t - is set to a wrong position.\n",
    "cwe": "Wrong constant (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "mh5",
        "tf"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/653"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman/motoman_mh5_support",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-08-24 (16:20)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/653",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 175,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": null,
        "fix-in": [
            "motoman_mh5_support/urdf/mh5_macro.xacros"
        ],
        "languages": [
            "xacro"
        ],
        "time": "2017-05-23 (22:15)"
    }
}
```
