### ISSUE TITLE
Missing install targets

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#654]
```yaml
{
    "id": 654,
    "title": "Missing install targets",
    "type": "weakness",
    "description": "The CMakeLists.txt of the dx100, fs100 and motoman_driver packages are missing install targets. This makes it impossible to use them in a install space.\n",
    "cwe": "Missing Installation Dependencies (no CWE)",
    "cve": "None",
    "keywords": [
        "CMake",
        "install targets"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/654"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman | ros-industrial/motoman/motoman_driver",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-24 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/654",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "10 | 11 | 14",
        "repo": "https://github.com/ros-industrial/motoman/",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "158 files due to a complete update of the driver package."
        ],
        "languages": null,
        "time": "2013-09-05 (18:20)"
    }
}
```
