### ISSUE TITLE
Incorrect values for frame transform between two robot links

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#655]
```yaml
{
    "id": 655,
    "title": "Incorrect values for frame transform between two robot links",
    "type": "weakness",
    "description": "The transform from link_t to tool0 in sia20 package is in reality -pi.  In the robot description file it is rounded to -3.1416, which leads to an offset of 3 degree difference from the real robot to the description.\n",
    "cwe": "Wrong constant (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "robot arm",
        "transforms",
        "robot description"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://www.motoman.com/industrial-robots/sia20d",
        "https://github.com/aliasrobotics/RVD/issues/655"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "application-specific code",
        "application": "industrial robot arm",
        "subsystem": "motion",
        "package": "ros-industrial/motoman/sia20d_support | ros-industrial/motoman/sia10f_support",
        "languages": [
            "XML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-06-18 (12:32)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/655",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 110,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_sia20d_support/urdf/sia20d_macro.xacro",
            "motoman_sia10f_support/urdf/sia10f_macro.xacro"
        ],
        "languages": [
            "xacro"
        ],
        "time": "2016-08-28 (04:00)"
    }
}
```
