### ISSUE TITLE
Deprecated reference to files in sia5d package

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#656]
```yaml
{
    "id": 656,
    "title": "Deprecated reference to files in sia5d package",
    "type": "weakness",
    "description": "The sia5d_support packages makes use of mesh files for robot visualization.  The meshes used in the robot description file sia5d_macro.xacro refers to the motoman_config package for this mesh files, which is deprecated.\n",
    "cwe": "CWE-477: Use of Obsolete Functions #EVOLUTION",
    "cve": "None",
    "keywords": [
        "xacro macro",
        "mesh",
        "robot description"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/656"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "general-issue",
        "architectural-location": "application-specific",
        "application": "industrial robot arm",
        "subsystem": "visualization",
        "package": "ros-industrial/motoman | ros-industrial/motoman/sia5d_support",
        "languages": [
            "XML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-02-15 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/656",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 94,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_sia5d_support/urdf/sia5d.urdf",
            "motoman_sia5d_support/urdf/sia5d_macro.xacro"
        ],
        "languages": [
            "xacro",
            "urdf"
        ],
        "time": "2016-06-25 (00:00)"
    }
}
```
