### ISSUE TITLE
Variable is assigned but never used

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#657]
```yaml
{
    "id": 657,
    "title": "Variable is assigned but never used",
    "type": "weakness",
    "description": "In the Motoman driver a variable 'bHasPreviousData' is set to different values, but it is never used in any case later.  It is used just in a line, which is at that moment in a commit.\n",
    "cwe": "CWE-563: Assignment to Variable without Use (Unused Variable)",
    "cve": "None",
    "keywords": [
        "driver",
        "motoman"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/657"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman/motoman_driver",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-12-21 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/657",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 140,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_driver/MotoPlus/Controller.c",
            "motoman_driver/MotoPlus/Controller.h",
            "motoman_driver/MotoPlus/MotionServer.c",
            "motoman_driver/MotoPlus/MpRosAllControllers.VC.db",
            "motoman_driver/MotoPlus/MpRosAllControllers.vcxproj.filters",
            "motoman_driver/MotoPlus/RosSetupValidation.dnLib",
            "motoman_driver/MotoPlus/RosSetupValidation.fsLib",
            "motoman_driver/MotoPlus/RosSetupValidation.h",
            "motoman_driver/MotoPlus/RosSetupValidation.mpLib",
            "motoman_driver/MotoPlus/_buildLog/MotoROSDX100.log",
            "motoman_driver/MotoPlus/mpMain.c",
            "motoman_driver/MotoPlus/output/DX100/MotoRosDX100/MotoRosDX100.out",
            "motoman_driver/MotoPlus/output/DX200/MotoRosDX200/MotoRosDX200.out",
            "motoman_driver/MotoPlus/output/FS100/MotoRosFS100/MotoRosFS100.out"
        ],
        "languages": null,
        "time": "2016-12-30 (18:48)"
    }
}
```
