### ISSUE TITLE
Missing dependency to Industrial Robot Simulation package

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#658]
```yaml
{
    "id": 658,
    "title": "Missing dependency to Industrial Robot Simulation package",
    "type": "weakness",
    "description": "The Motoman uses MoveIt for Dynamic Path Planning. The MoveIt configuration (moveit_cfgs) used for Simulation depends on Industrial Robot Simulation. This dependency is missing for runtime.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "MoveIt",
        "dependency",
        "motoman"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/658"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman | ros-industrial/motoman/motoman_sda10f_support | ros_industrial/motoman/motoman_sia10d_support | ros-industrial/motoman/motoman_sia20d_support | ros-industrial/motoman/motoman_sia5d_support",
        "languages": [
            "XML"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-02-10 (12:12)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/658",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 35,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_sia20d_moveit_config/package.xml"
        ],
        "languages": [
            "XML"
        ],
        "time": "2014-03-28 (11:36)"
    }
}
```
