### ISSUE TITLE
Library linking error

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#659]
```yaml
{
    "id": 659,
    "title": "Library linking error",
    "type": "weakness",
    "description": "In the CMakeLists.txt from the motoman_driver package, this package is not linked against the catkin_LIBRARIES. This results in an error, when compiling with catkin\n",
    "cwe": "Linking error (no CWE)",
    "cve": "None",
    "keywords": [
        "linking",
        "CMakeLists",
        "catkin"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/659"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "error",
        "architectural-location": "ROS-specific",
        "application": "platform code",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman | ros-industrial/motoman/motoman_driver",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-01-27 (12:08)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/659",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 25,
        "repo": "https://github.com/ros-industrial/motoman/",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_driver/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2014-01-28 (03:47)"
    }
}
```
