### ISSUE TITLE
SIA5D model can not be moved

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#660]
```yaml
{
    "id": 660,
    "title": "SIA5D model can not be moved",
    "type": "weakness",
    "description": "SIA5D URDF does not have moveable joints. This is caused by safety controller parameter limits in the URDF set all to 0.\n",
    "cwe": "Wrong behavior (no CWE)",
    "cve": "None",
    "keywords": [
        "URDF",
        "motoman",
        "joints"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/660"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "application-specific",
        "application": "industrial robot arm",
        "subsystem": "robot description",
        "package": "ros-industrial/motoman/motoman_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-02-04 (00:06)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/660",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 30,
        "repo": "https://github.com/ros-industrial/motoman/",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_sia5d_support/urdf/sia5d.urdf",
            "motoman_sia5d_support/urdf/sia5d_macro.xacro"
        ],
        "languages": [
            "urdf",
            "xacro"
        ],
        "time": "2014-02-08 (03:51)"
    }
}
```
