### ISSUE TITLE
Incorrect response from FS100 to a control request

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#661]
```yaml
{
    "id": 661,
    "title": "Incorrect response from FS100 to a control request",
    "type": "weakness",
    "description": "The FS100 is one of the robot controllers by Motoman that are open to be used with ROS. From ROS side one can send a request for a motion and the controller will respond within a MOTO_MOTION_CTRL message. In some cases the field robot_id and sequence are set to -1. This is from the controller interpreted as unsigned leading to response as 0xFFFFFFFF.\n",
    "cwe": "CWE-704: Incorrect Type Conversion or Cast",
    "cve": "None",
    "keywords": [
        "FS100 controller",
        "movement request",
        "motoman"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/661"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "application-specific",
        "application": "industrial robot arm",
        "subsystem": "motoplus pluging for the controller",
        "package": "ros-industrial/motoman",
        "languages": "C",
        "date-detected": "",
        "detected-by": "user | developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-06-12 (20:01)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/661",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/ros-industrial/motoman/",
        "hash": "292b5cc8a10a640a8b364a529e3eadffffc9b56b",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "fs100/MotoPlus/MotionServer.c",
            "fs100/MotoPlus/SimpleMessage.c",
            "fs100/MotoPlus/output/MPRosFS100.out"
        ],
        "languages": [
            "C"
        ],
        "time": "2013-06-18 (21:23)"
    }
}
```
