### ISSUE TITLE
Setup Validation for MotoROS logic wrong

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#662]
```yaml
{
    "id": 662,
    "title": "Setup Validation for MotoROS logic wrong",
    "type": "weakness",
    "description": "The installation of MotoROS for the Controller is checked by a validation file. This validation returns a warning to contact Yaskawa support after a couple of resets instead of showing them after the first reboot, if some parameters are wrong.\n",
    "cwe": "Wrong behavior (no CWE) #PHYSICAL",
    "cve": "None",
    "keywords": [
        "driver",
        "motoman"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/662"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman/motoman_driver",
        "languages": [
            "C"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-01-09 (14:44)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/662",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 148,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_driver/MotoPlus/Controller.h",
            "motoman_driver/MotoPlus/CtrlGroup.c",
            "motoman_driver/MotoPlus/MotionServer.c",
            "motoman_driver/MotoPlus/ParameterTypes.h",
            "motoman_driver/MotoPlus/RosSetupValidation.dnLib",
            "motoman_driver/MotoPlus/RosSetupValidation.fsLib",
            "motoman_driver/MotoPlus/RosSetupValidation.mpLib",
            "motoman_driver/MotoPlus/_buildLog/MotoROSDX100.log",
            "motoman_driver/MotoPlus/output/DX100/MotoRosDX100/MotoRosDX100.out",
            "motoman_driver/MotoPlus/output/DX200/MotoRosDX200/MotoRosDX200.out",
            "motoman_driver/MotoPlus/output/FS100/MotoRosFS100/MotoRosFS100.out"
        ],
        "languages": [
            "C"
        ],
        "time": "2017-01-09 (21:09)"
    }
}
```
