### ISSUE TITLE
SDA10f incorrect macro usage in top-level xacro

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#663]
```yaml
{
    "id": 663,
    "title": "SDA10f incorrect macro usage in top-level xacro",
    "type": "weakness",
    "description": "The sda10f.xacro tries to instantiate a macro called motoman_sda10f', but that does not exist. So roslaunch tests for that top-level xacro fail.\n",
    "cwe": "Undeclared Identifier (no CWE)",
    "cve": "None",
    "keywords": [
        "robot description",
        "motoman",
        "SDA10f"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/663"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman/motoman_driver",
        "languages": "launch XML",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2017-04-05 (10:04)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/663",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 169,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            ".travis.yml",
            "motoman_sda10f_support/test/launch_test.xml",
            "motoman_sda10f_support/test/sda10f_test.xacro",
            "motoman_sda10f_support/urdf/arm_macro.xacro",
            "motoman_sda10f_support/urdf/common_torso_macro.xacro",
            "motoman_sda10f_support/urdf/sda10f_macro.xacro"
        ],
        "languages": [
            "launch XML",
            "xacro"
        ],
        "time": "2017-04-10 (06:55)"
    }
}
```
