### ISSUE TITLE
Error message when installing Inform Code in DX200

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#664]
```yaml
{
    "id": 664,
    "title": "Error message when installing Inform Code in DX200",
    "type": "weakness",
    "description": "The Motoman controller has to be prepared for use with ROS. For this, you have to first install MotoPlus on the controller and afterwards a special INFORM Code. The motoman driver specifies a required handshake between the native INFORM robot code and the MotoRos layer. The MotoRos code will automatically run an INFORM job called INIT_ROS at the start of a motion command, which will provide the required handshaking.  When installing the INFORM Code to a DX200, it shows an error: L:****) ERROR 3200 : NOP or END instruction not found (J:INIT_ROS\n",
    "cwe": "CWE-172: Encoding Error (Unix vs Windows line breaks)",
    "cve": "None",
    "keywords": [
        "driver",
        "motoman"
    ],
    "system": "motoman",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/motoman_driver/Tutorials/indigo/InstallServer",
        "https://github.com/aliasrobotics/RVD/issues/664"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "ros-industrial/motoman/motoman_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "user",
        "detected-by-method": "N/A",
        "date-reported": "2017-01-08 (12:42)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/664",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": 147,
        "repo": "https://github.com/ros-industrial/motoman",
        "hash": null,
        "license": [
            "BSD"
        ],
        "fix-in": [
            "motoman_driver/Inform/.gitattributes"
        ],
        "languages": null,
        "time": "2017-01-09 (21:09)"
    }
}
```
