### ISSUE TITLE
The installation of the TF2 library is not a dependency of the devel build

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#665]
```yaml
{
    "id": 665,
    "title": "The installation of the TF2 library is not a dependency of the devel build",
    "type": "weakness",
    "description": "Due to a typing mistake (likely a copy-paste) the tf2 library is not included in the build of the devel target The target that is used as a dependency of software packages that depend on this library.  This causes build errors. The bug was detected by a jenkins build whose output is no longer available. Such bugs can appear in building other dependent packages, but in this case it appears that it was detecte when building the tf2 package itself.\n",
    "cwe": "Missing Dependency (no CWE)",
    "cve": "None",
    "keywords": [
        "build",
        "depency",
        "devel"
    ],
    "system": "core component",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/665"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "generic task component",
        "package": "ros/geometry2/tf2_ros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "build system",
        "detected-by-method": "N/A",
        "date-reported": "Feb 14, 2013, 9:39 AM GMT+1",
        "reported-by": "automatic",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/665",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "repo": "https://github.com/ros/geometry2",
        "hash": "a723ecb68f72d52e538f9e9bdbca3e66f7a69444",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "tf2/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "Feb 15, 2013, 12:37 GMT +1"
    }
}
```
