### ISSUE TITLE
Race conditions in startup code of TF2

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#668]
```yaml
{
    "id": 668,
    "title": "Race conditions in startup code of TF2",
    "type": "weakness",
    "description": "A buffer server node is being start with an autostart parameter (which is picked up due to a default value of the autostart parameter).  Unfortunately, this supposedly causes race conditions in initialization code. A warning is produced that this may happen. The fix removes the autostart, and starts the server manually.  There is some understanding, that this is a minor problem, as the race condition should not have any serious effect on this module.\n",
    "cwe": "CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition') #RESOURCE",
    "cve": "None",
    "keywords": [
        "race condition",
        "concurrency"
    ],
    "system": "core component",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/ros/geometry2/issues/15 (another issue that seems to be reporting the same)",
        "https://github.com/aliasrobotics/RVD/issues/668"
    ],
    "flaw": {
        "phase": "runtime",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "generic task component",
        "package": "ros/geometry2/tf2_ros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "Jun 27, 2013, 8:41 PM GMT+2",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/668",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros/geometry2/pull/10",
        "repo": "https://github.com/ros/geometry2",
        "hash": "https://github.com/ros/geometry2/commit/15b2e3c52152ee4fc19c55ec76f049e990c05809",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "tf2_ros/include/tf2_ros/buffer_server.h",
            "tf2_ros/src/buffer_server_main.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "Jul 10, 2013, 8:48 AM GMT+2"
    }
}
```
