### ISSUE TITLE
Wrong logical condition for selecting targets of a message

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#669]
```yaml
{
    "id": 669,
    "title": "Wrong logical condition for selecting targets of a message",
    "type": "weakness",
    "description": "Static Transform Broadcaster uses a wrong condition in selecting messages to be send to notes (the condition is supposed to filter out duplicates).  This is a typical bug in logic of the program that does not really appear fixable/detectable without specification (for instance tests).  The developer producing the fix has also included a regression test.\n",
    "cwe": "Wrong behavior (no CWE)",
    "cve": "None",
    "keywords": [
        "condition error"
    ],
    "system": "core component",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/669"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "generic task component",
        "package": "ros/geometry2/tf2_ros",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "Oct 13, 2013, 10:56 PM GMT+2",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/669",
        "reproducibility": "always",
        "trace": "FIXME: there is a test case added in the fixing commit.\n",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros/geometry2/pull/29",
        "repo": "https://github.com/ros/geometry2",
        "hash": "c81fa7213ec2ca6512c8015b13a5bbade2b690f7",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "tf2_ros/src/static_transform_broadcaster.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "Oct 15, 2013, 3:04 AM GMT+2"
    }
}
```
