### ISSUE TITLE
Driver locks without discovering that a trajectory has been realized or failed

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#677]
```yaml
{
    "id": 677,
    "title": "Driver locks without discovering that a trajectory has been realized or failed",
    "type": "weakness",
    "description": "The python driver is not detecting that a robot arm has reached a goal point of a trajectory planned.  It never sends an information that the final point has been reached and locks. The fix relies on distinguishing two situations: whether the robot got stuck due to planning errors, or whether it has reached the final destination (and the final location has been communicated). The deadlocks are intermittent, probably dependent on numerical proximity of the goal and the present position, or on timing.\n",
    "cwe": "CWE-440: Expected Behavior Violation #PHYSICAL\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "trajectory",
        "ur",
        "driver",
        "locked",
        "planning"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/677"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "platform-code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2014-02-03 (23:23)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/677",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/37",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "bd1fce5b225aecc4862e824b674eebb4c40be255",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_driver/src/ur_driver/driver.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2014-02-08 (03:30)"
    }
}
```
