### ISSUE TITLE
Syntax error in a robot script

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#678]
```yaml
{
    "id": 678,
    "title": "Syntax error in a robot script",
    "type": "weakness",
    "description": "The bug occurs in the code running on the robot that is uploaded there by ROS.  This code is written in a prioprietary language URScript. The entire program (ur_driver/prog) consists of one top-level function 'driverProg'.  After this program, there was one toplevel call to this function, which was not required (indeed not allowed) by the syntax of URScript.  The language's semantics by default performs this call to the only existing function upon function definition. The parser for URScript produces a parsing error, but the language is permissive and the program continuous to execute as if the line was not there.  Thus the impact on the execution of the robot is negligible (just a message). This is an encoding error in the sense that the program sent to UR robot is incorrect sytnactically (so this is analogous to sending any other malformed message), but note that this program is not synthesized by the driver, but coded statically. Malformed script execution in a dynamic interpreted language is a general software defect that could appear in many other languages.\n",
    "cwe": "CWE-172: Encoding Error\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "URScript",
        "syntax error"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/678"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_driver",
        "languages": [
            "URScript"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "None",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/678",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/165",
        "repo": "https://github.com/ros-industrial/universal_robot/",
        "hash": "1e0904c38934fe09c9647825caf3b58dda2636f9",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_driver/prog"
        ],
        "languages": [
            "URScript"
        ],
        "time": "2015-02-20 (11:24)"
    }
}
```
