### ISSUE TITLE
xacro namespace warnings

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#679]
```yaml
{
    "id": 679,
    "title": "xacro namespace warnings",
    "type": "weakness",
    "description": "URDF is an XML-based modeling language in which robot physical models are described. As robots are often produced in families of similar devices, it is convenient to parameterize this models. ROS uses the XACRO language to write parameterized models.  XACRO files are preprocessed to generate instantiated URDF files. The domain specific language (xacro) used in ROS has evolved, and now the files in this language need to be appropriately updated. This is somewhat similar to API evolution.  XACRO detects these problems, flags them as warnings and even displays a sed script that would fix them. find . -iname \"*.xacro\" | xargs sed -i 's#<\\([/]\\?\\)\\(if\\|unless\\|include\\|arg\\|property\\|macro\\|insert_block\\)#<\\1xacro:\\2#g' The patches in the commit are likely generated automatically by using this (or a similar script). The issue is minor as it has no effect on the build (otherwise than producing a warning) and no effect on the robot functionality.  However, it might become serious if XACRO stops accepting the old naming convention. The commit also fixes other, seemingly unrelated issues in launch files. Language evolution problems are common, however this issue appears in a ROS-specific DSL in ROS-specific tooling.  The case might be pertinent to work on XML language evolution (as XACRO and URDF are both XML languages). Under links you can find an issue that was (independently) filed after the fix has been suggested.\n",
    "cwe": "CWE-477: Use of Obsolete Functions #EVOLUTION\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "xacro",
        "xml",
        "namespace",
        "urdf"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/xacro",
        "https://github.com/ros-industrial/universal_robot/issues/263",
        "https://github.com/aliasrobotics/RVD/issues/679"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_description",
        "languages": [
            "xacro"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "unreported",
        "reported-by": "unreported",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/679",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/251",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "fa64ec6585745c60fa02cf3be13b6d78bf449d8d",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_description/urdf/ur10.urdf.xacro",
            "ur_description/urdf/ur3.urdf.xacro",
            "ur_description/urdf/ur5.urdf.xacro"
        ],
        "languages": [
            "xacro",
            "xml"
        ],
        "time": "2016-12-29 (20:59)"
    }
}
```
