### ISSUE TITLE
An attempt to read a flag beyond 32-bits

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#680]
```yaml
{
    "id": 680,
    "title": "An attempt to read a flag beyond 32-bits",
    "type": "weakness",
    "description": "The universal_robot driver controls the rebots with help of scritps (prog) written in a proprietary lanugage developed by Universal Robots (URScript). The prog script used in the driver reads flags consecutively to send them forwards starting with 0 to 32. However the vector of flags has only 32 bits, so the last flag does not exist.  This causes the simulator of the universal robot to complain with a warning.  The actual robot does not appear to be affected. The issue is general. It is a typical overflow/one-off error when accessing an indexed resource. It appears in a language that is specific to the robot in question, and entirely independent of ROS.\n",
    "cwe": "CWE-193: Off-by-one Error\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "urscript",
        "flags",
        "overflow"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/680"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "platform-code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_driver",
        "languages": [
            "URScript"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2014-09-12 (17:15)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/680",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/110",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "b2abe31a90a92b5ebd26cd2e39c260d6151d0daa",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_driver/prog"
        ],
        "languages": [
            "URScript"
        ],
        "time": "2014-10-10 (11:26)"
    }
}
```
