### ISSUE TITLE
parameter moved into namespace

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#681]
```yaml
{
    "id": 681,
    "title": "parameter moved into namespace",
    "type": "weakness",
    "description": "MoveIt parameters have been reorganized. The parameters 'allowed_execution_duration_scaling' and 'allowed_goal_duration_margin' have been moved down in the hierarchy, under 'trajectory_execution'. This now produces warning during execution of launch files (so files that start ROS nodes), as assigned parameters no longer exist at top level.  The framework still assigns them but produces a warning, presumably because it will become less forgiving at some point. This is a bug that was caused by evolution of a data schema / language outside of the UR driver code.  Since the driver depends on this code, it needs to be updated to the new schema.  This is a fairly generic problem in software engineering, especially for XML-based languages, yet here it appears in a ROS-specific language (launch XML).\n",
    "cwe": "Undeclared Identifier (no CWE) #EVOLUTION\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "launch",
        "language evolution"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/681"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform-code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-planning/moveit_ros/planning",
        "languages": [
            "launch XML"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "unreported",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/681",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/285",
        "repo": "https://github.com/ros-industrial/universal_robot/",
        "hash": "778c1acda6dc3e194b50328259936c3f058bcb7",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur10_moveit_config/launch/trajectory_execution.launch.xml",
            "ur3_moveit_config/launch/trajectory_execution.launch.xml",
            "ur5_moveit_config/launch/trajectory_execution.launch.xml"
        ],
        "languages": [
            "launch XML"
        ],
        "time": "2017-01-05 (05:58)"
    }
}
```
