### ISSUE TITLE
Using a Boost type instead of a C++11 type

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#687]
```yaml
{
    "id": 687,
    "title": "Using a Boost type instead of a C++11 type",
    "type": "weakness",
    "description": "The urdf_model package started to use C++11 features, more precisely the shared pointer type that clashes with a similar type in the Boost library. The (single) call to this package needs to be updated from boost::shared_ptr to std::shared_ptr as otherwise the compiler fails with a type error. This issue is caused by the dependent upon packages switching to a newer programmin language version.  This issue could appear in any complex projects which mixes versions of the programming language (here C++). (At the time of analysis of this bug, the fix was not merged.)\n",
    "cwe": "Type error (no CWE) #EVOLUTION: CWE-439\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "C++11",
        "boost",
        "pointer"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "see also bug 94927ae",
        "https://github.com/aliasrobotics/RVD/issues/687"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_kinematics",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compile-time",
        "detected-by-method": "N/A",
        "date-reported": "None",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/687",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/303",
        "repo": "https://github.com/ros-industrial/universal_robot/",
        "hash": "c4e118757123ef243d0f3c2e14a6c3d63549f20d",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_kinematics/src/ur_moveit_plugin.cpp"
        ],
        "languages": [
            "C++"
        ],
        "time": "unfixed"
    }
}
```
