### ISSUE TITLE
Specifications of dimensions of a robot arm are not reflecting real dimensions

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#689]
```yaml
{
    "id": 689,
    "title": "Specifications of dimensions of a robot arm are not reflecting real dimensions",
    "type": "weakness",
    "description": "URDF is an XML-based modeling language in which robot physical models are described. As robots are often produced in families of similar devices, it is convenient to parameterize this models. ROS uses the XACRO language to write parameterized models.  XACRO files are preprocessed to generate instantiated URDF files. In this particular case, a XACRO file contained physical dimensions of the UR10 robots that were inconsistent with those stored in the native software of Universal Robots (and also inconsistent with the documentation data). This means that the robot visualized in the visualization tool Rviz and used in simulation behaved differently than the real robot.  This poses an issue for testing and quality assurance. The issue is specific to ROS as it occurs in a ROS specific modeling language (URDF/XACRO).  However the same problem would naturally appear in any robotics framework, just in a different language. The discussion has started on the mailing list, and then have been promoted to the issue tracker, and referred from a larger pull requests that also improves other visual issues with URDF files, and reorganizes the files, so many aspects of the linked commit do not pertain to this bug. The same patch also fixes some potentially interesting issues with mass and inertia of the robot elements.\n",
    "cwe": "Wrong Robot Model (no CWE) #PHYSICAL\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "urdf",
        "xacro",
        "rviz",
        "driver"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/1e3A_1BTQWQ",
        "https://github.com/aliasrobotics/RVD/issues/689"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_description",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-05-27 (15:40)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/689",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/82",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "21b86f63408a99aff35cd82ca6ac180a99566ee5",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_description/urdf/ur10.urdf.xacro"
        ],
        "languages": [
            "xacro"
        ],
        "time": "2014-08-06 (13:00)"
    }
}
```
