### ISSUE TITLE
Missing specifications for installation of UR packages

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#690]
```yaml
{
    "id": 690,
    "title": "Missing specifications for installation of UR packages",
    "type": "weakness",
    "description": "The build specification for five ur packages (ur_bringup, ur_description, ur_driver, ur_gazebo, ur_kinematics) are missing declaration of target directories for installation.  As an effect installation using catkin is not possible The Groovy version of ROS introduced a new build system (catkin) over the legacy rosbuild used before.  This is why the errors are only reported for groovy-dev --- these are errors in the newly created build files. This is reported as one bug, but technically these are five almost identical problems in five packages of the universal_robot repository. Apparently due to git mishandling PR14, linked below, was not merged, but an identical PR19 was merged directly later on. This issue is specific to catkin, which is the build system used only in ROS.  It is based on CMake, used somewhat more widely, though.  However, lack of deployment specification is a general software engineering issue.\n",
    "cwe": "Missing Installation Dependencies (no CWE)\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "catkin",
        "installation"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://docs.ros.org/api/catkin/html/user_guide/variables.html (the link to variables docs in the CMakeLists.txt file is broken)",
        "http://docs.ros.org/kinetic/api/catkin/html/howto/format2/building_executables.html (documentation of the install directives used in the fix, in the bottom of this page)",
        "http://docs.ros.org/kinetic/api/catkin/html/user_guide/setup_dot_py.html (a small explanation of what catkin_python_setup() does, added to ur_driver/CMakeLists.txt)",
        {
            "ROS Groovy release notes presenting introduction of catkin": "http://wiki.ros.org/groovy#New_Build_System_-_catkin"
        },
        "https://github.com/aliasrobotics/RVD/issues/690"
    ],
    "flaw": {
        "phase": "deployment-time",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_bringup | ros-industrial/universal_robot/ur_description | ros-industrial/universal_robot/ur_driver | ros-industrial/universal_robot/ur_gazebo | ros-industrial/universal_robot/ur_kinematics",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-24 (15:39)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/690",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/14 | https://github.com/ros-industrial/universal_robot/pull/19",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "56cf07f62fcdd3927ebff216da281d3b975adefc",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_bringup/CMakeLists.txt",
            "ur_description/CMakeLists.txt",
            "ur_driver/CMakeLists.txt",
            "ur_gazebo/CMakeLists.txt",
            "ur_kinematics/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2013-10-01 (21:20)"
    }
}
```
