### ISSUE TITLE
Missing runtime dependency on message definitions

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#692]
```yaml
{
    "id": 692,
    "title": "Missing runtime dependency on message definitions",
    "type": "weakness",
    "description": "ROS uses channels (known as 'topics') for communication.  Each topic is typed by a format of the messages it can carry. Messages are defined in a .msg file (.msg is essentially a super simple data-definition-langage (DDL)).  Implementations of messages are generated from msg files at compile time and then used at runtime to serialize and deserialize messages for communication. Meta-packages in ROS are used to install a number of packages working together (and having actual contents) to be conveniently installed together, while tracking all dependencies. The definition of runtime dependencies in the manifest (package.xml) file of universal_robot meta-package misses the runtime dependency on the ur_msgs package, which means that python programs trying to send or receive messages will crash. The issue is ROS-specific as it appears in ROS-specific package.xml files.  However, the issue of missing runtime dependencies overall, is a general software-engineering issue. The first pull request linked has not been merged, but a larger pull request has been merged that contain the fix. This is why we link two PRs. This bug also affects statically compiled languages (not only python), because format 1 of package.xml uses runtime dependencies both to specify actual runtime dependencies and dependencies that are needed to build the referring package (build dependencies are reserved for dependencies needed to build the referred package). This is explained in the REP, in the second link below.\n",
    "cwe": "run-time dependency issue (no CWE) internal classification (cause): internal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "package.xml",
        "catkin"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/package.xml",
        "http://www.ros.org/reps/rep-0140.html#rationale",
        "https://github.com/aliasrobotics/RVD/issues/692"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/universal_robot",
        "languages": [
            "python"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "unreported",
        "reported-by": "unreported",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/692",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/100 | https://github.com/ros-industrial/universal_robot/pull/130",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "082dcf1551d84a9a874443adc39627f67272ac4c",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "package.xml"
        ],
        "languages": [
            "package.xml"
        ],
        "time": "2014-09-04 (17:57)"
    }
}
```
