### ISSUE TITLE
Controller reads too many bytes for IO message

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#695]
```yaml
{
    "id": 695,
    "title": "Controller reads too many bytes for IO message",
    "type": "weakness",
    "description": "The controller reads more from the socket than the size of the message. This is not always a problem, as often messages are processed one a time, and there is nothing more available to read.  However in many-message scenarios (like executing a trajectory) this leads to errors, as remaining messages are read with an offset (incomplete gibberish). The bug occurs in the code running on the robot that is uploaded there by ROS.  This code is written in a prioprietary language URScript. The bug appears in universal-robot-specific language, but overreading is a standard issue, that could be seen in many software systems. The first pull request was closed without merging, but a large (the second) pull request included the same change.\n",
    "cwe": "CWE-805: Buffer Access with Incorrect Length Value\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "socket",
        "message",
        "urscript"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/695"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "general-issue",
        "architectural-location": "platform-code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_driver",
        "languages": [
            "URScript"
        ],
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2014-09-12 (12:16)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/695",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/115 | https://github.com/ros-industrial/universal_robot/pull/117",
        "repo": "https://github.com/ros-industrial/universal_robot/",
        "hash": "359a2e9d0c21b37c4fc077e08dbb56de771734cb",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_driver/prog"
        ],
        "languages": [
            "URScript"
        ],
        "time": "2014-10-10 (11:52)"
    }
}
```
