### ISSUE TITLE
Robot jumps to the first point of the new trajectory

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#696]
```yaml
{
    "id": 696,
    "title": "Robot jumps to the first point of the new trajectory",
    "type": "weakness",
    "description": "The problem was caused by using absolute, instead of relative time, when resetting the old trajectory to a new goal.  On_goal() function of the trajectory action server in the ur_driver driver.py file, the sample_traj() function was not being called correctly. It used the absolute time (from time.time()) instead of the offset into the previous trajectory which is used in every other call of this particular function. As a result the robot would attempt to perform an abrupt fast jump to a new trajectory. The bug is an improper contract fullfillment although it was not an 'abuse', as it was not intentional.  The problem can appear is any continous control or planning application, and as that it is not ROS-specific, but robotics-specific. The second pull request is a case of porting up of the same bug fix to a newer development branch (indigo).\n",
    "cwe": "Dangerous behavior: abrupt arm jump #PHYSICAL\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "planning",
        "trajectory",
        "absolute time",
        "relative time"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/696"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_driver",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "None",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/696",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/157 | https://github.com/ros-industrial/universal_robot/pull/189",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "b3c2c215b4fc46bb66ca61e6e693920540d0daef",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_driver/src/ur_driver/driver.py"
        ],
        "languages": [
            "Python"
        ],
        "time": "2015-03-12 (14:44)"
    }
}
```
