### ISSUE TITLE
Missing runtime dependency to run UR robots Gazebo simulation

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#698]
```yaml
{
    "id": 698,
    "title": "Missing runtime dependency to run UR robots Gazebo simulation",
    "type": "weakness",
    "description": "The moveit_simple_controller_manager package is not installed due to missing runtime dependencies in MoveIt configuration files for ur robots. The issue has been reported by the universal_robot driver user who merely tried to follow the readme instructions how to start up gazebo-based simulation.  Starting the simulation results in a runtime exception from python about a missing module.  This kind of problems are hard to track for developers who often have all the dependencies installed.  However a continuous integration setup would usually build from scratch detecting most of such. The issue is ROS-specific as it appears in ROS-specific package.xml files.  However, the issue of missing runtime dependencies overall, is a general software-engineering issue.\n",
    "cwe": "run-time dependency issue (no CWE)\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "gazebo",
        "simulation",
        "dependency",
        "package.xml"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/catkin/package.xml",
        "https://github.com/aliasrobotics/RVD/issues/698"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform-code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ur10_moveit_config | ur3_moveit_config | ur5_moveit_config",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2015-12-02 (23:24)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/698",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/236",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "e122ccc26d8b96f1534a51fc3f0f34638f63c657",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur10_moveit_config/package.xml",
            "ur3_moveit_config/package.xml",
            "ur5_moveit_config/package.xml"
        ],
        "languages": [
            "package.xml"
        ],
        "time": "2016-04-01 (15:59)"
    }
}
```
