### ISSUE TITLE
Self-collisions break planning when full joint space is used

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#699]
```yaml
{
    "id": 699,
    "title": "Self-collisions break planning when full joint space is used",
    "type": "weakness",
    "description": "The state space of the elbow joint of UR5 and UR10 is set to be [2pi;+2pi] in accordance with manufacturers documentation. However the if the joint is close to Pi or -Pi then the robot enters a self-collision due to a design limitation.  This causes problems with planning as either the robots stops during some plans, or the planning mechanism detects a self collision and stops. The proposed solution is to limit the elbow joint to (-pi,pi) so that the plans cannot cross through the collision zone. The linked issue shows diagrams and pictures explaining the problem. The issue has not been fixed to the best of our knowledge (on the date of collecting the data, the pull request is not merged; although it has rather many supporters, the maintainer is hesitant). This is a robot modeling issue, that could appear in any robotics project with planning; not particularly ROS-specific.\n",
    "cwe": "Dangerous behavior: Self-collision (no CWE) #PHYSICAL\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "moveit",
        "kinematics",
        "urdf",
        "xacro",
        "driver"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/699"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "robotics-specific",
        "architectural-location": "platform-code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "error reported by a planner but unclear by which package",
        "languages": "None",
        "date-detected": "",
        "detected-by": "developer",
        "detected-by-method": "N/A",
        "date-reported": "2016-10-11 (05:02)",
        "reported-by": "guest user",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/699",
        "reproducibility": "sometimes",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/268 | https://github.com/ros-industrial/universal_robot/pull/302",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "89145c420d9b6bbfb4d385d43205708d45cc9449",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_description/urdf/ur10.urdf.xacro",
            "ur_description/urdf/ur5.urdf.xacro"
        ],
        "languages": [
            "xacro"
        ],
        "time": "unfixed"
    }
}
```
