### ISSUE TITLE
Missing Runtime Dependency on MoveIt config

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#707]
```yaml
{
    "id": 707,
    "title": "Missing Runtime Dependency on MoveIt config",
    "type": "weakness",
    "description": "The universal_robot package misses a runtime dependency in the manifest file package.xml.  This has prevented the driver to pass continuous integration tests.\n",
    "cwe": "Run-time dependency issue (no CWE)\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "dependencies",
        "runtime",
        "launch",
        "package.xml"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/707"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform-code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/package.xml",
        "languages": "(presumably) python",
        "date-detected": "",
        "detected-by": "runtime crash",
        "detected-by-method": "N/A",
        "date-reported": "2014-03-31 (15:19)",
        "reported-by": "contributor",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/707",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/53",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "dda2f607be5f6650f7ce32b64d2cc413a8938c15",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ros_industrial/universal_robot/package.xml"
        ],
        "languages": [
            "package.xml"
        ],
        "time": "2014-03-31 (15:52)"
    }
}
```
