### ISSUE TITLE
required C++11 compiler

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#709]
```yaml
{
    "id": 709,
    "title": "required C++11 compiler",
    "type": "weakness",
    "description": "The geometric_shapes package (from moveit) started to use C++11 features, more precisely the shared pointer type that clashes with a similar type in the Boost library.  The geometry shapes headers were updated to include a check if a C++11 compiler is used, and fail with an error otherwise. This issue could appear in any complex projects which mixes versions of the programming language (here C++).\n",
    "cwe": "Type error (no CWE) #EVOLUTION: CWE-439\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "C++11",
        "boost",
        "pointer",
        "header file"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/ros-industrial/universal_robot/pull/254",
        "https://github.com/ros-planning/geometric_shapes/blob/kinetic-devel/include/geometric_shapes/shapes.h",
        "https://discourse.ros.org/t/std-shared-ptr-in-the-geometric-shapes-public-api/395/10",
        "https://github.com/aliasrobotics/RVD/issues/709"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_kinematics",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compile-time",
        "detected-by-method": "N/A",
        "date-reported": "None",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/709",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/286",
        "repo": "https://github.com/ros-industrial/universal_robot/",
        "hash": "c7794329bf632592bf1d345d1290ff4b8d13580a",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_kinematics/CMakeLists.txt",
            "ur_kinematics/include/ur_kinematics/ur_moveit_plugin.h"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2017-01-06 (12:29)"
    }
}
```
