### ISSUE TITLE
Missing encryption of sensitive data on Rovio

### ISSUE THREAD

**Issue by aliasbot** [aliasrobotics/RVD#71]
```yaml
{
    "id": 71,
    "title": "Missing encryption of sensitive data on Rovio",
    "type": "vulnerability",
    "description": "Intercept the RTSP audiovisual stream being transmitted to the user. The username and password are sent as unencrypted base-64 encoded values during authentication. Applying wireshark and VLC to the RTSP audio-video stream, researchers learned that the audio uses unencrypted G.711 uncompressed audio and the video uses unencrypted MPEG4 or MJPEG encoding. They were able to capture a wireless trace from the Rovio's RTSP stream via Wireshark, reconstruct the video from that trace, and then view the video in VLC.\r\n  Credits to: Tamara Denning, Cynthia Matuszek, Karl Koscher, Joshua R. Smith, and Tadayoshi Kohno",
    "cwe": "CWE-Missing Encryption of Sensitive Data (CWE-311)",
    "cve": "None",
    "keywords": [
        "malformed",
        "robot",
        "robot: Rovio",
        "severity: high",
        "state: new",
        "vendor: WowWee",
        "vulnerability"
    ],
    "system": "Rovio",
    "vendor": "WowWee",
    "severity": {
        "rvss-score": 7.0,
        "rvss-vector": "RVSS:1.0/AV:RN/AC:H/PR:N/UI:N/Y:M/S:U/C:H/I:N/A:N/H:N",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/71"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2009-09-30",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2009-09-30",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/71",
        "reproducibility": "",
        "trace": null,
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
