### ISSUE TITLE
Missing runtime dependency on another package (industrial robot simulator)

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#710]
```yaml
{
    "id": 710,
    "title": "Missing runtime dependency on another package (industrial robot simulator)",
    "type": "weakness",
    "description": "The universal robot planner (moveit) module lacks a runtime dependency on the industrial robot simulator.  This leads to a runtime error (presumably). This bug has been repeated in multiple drivers. All industrial moveit_config packages use the industrial_robot_simulator, but don't declare a runtime dependency on it.  Affected robots include ABB, Fanuc, Motoman, Universal Robot.\n",
    "cwe": "run-time dependency issue (no CWE)\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "package.xml"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://wiki.ros.org/industrial_robot_simulator",
        "https://github.com/aliasrobotics/RVD/issues/710"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur5_moveit_config/",
        "languages": [
            "Python"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2014-02-10 (12:19)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/710",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/42",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "cd273dd7fdc767c6cc8f4e7f60a165577af0e6c0",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur5_moveit_config/package.xml"
        ],
        "languages": [
            "package.xml"
        ],
        "time": "2014-03-21 (02:53)"
    }
}
```
