### ISSUE TITLE
An exported library is not installed

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#711]
```yaml
{
    "id": 711,
    "title": "An exported library is not installed",
    "type": "weakness",
    "description": "The ur_kinematics package exports two libraries (ur5_moveit_plugin, ur10_moveit_plugin) to be used in depending packages.  This will work well if the packages using ur_kinematics are in the same workspace (devel space).  Since the installation script is missing for these two libraries, they will not be properly installed by the catkin build system, and if the libraries are not otherwise available in the system, this leads to a build failure for depending packages. The bug was detected by catkin_lint, a ROS-specific build system scanning tool.  The first link on to documentation of catkin_lint provides a definition of this alarm. The bug appears in ROS-specific build system. However, the dependency issue is a general issue in software engineering. The original commit also made unrelated changes to package.xml.\n",
    "cwe": "Missing Build Dependency (no CWE) internal classification (cause): internal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "catkin",
        "catkin_lint",
        "install",
        "dependencies"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/fkie/catkin_lint/blob/master/gh-pages/docs/messages.md#exported-library-target-is-not-installed",
        "https://github.com/aliasrobotics/RVD/issues/711"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_kinematics",
        "languages": [
            "CMake"
        ],
        "date-detected": "",
        "detected-by": "code scanning tool",
        "detected-by-method": "N/A",
        "date-reported": "2014-09-21 (08:17)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/711",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/114",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "040fd110f9281875d87b8e6aaba0c1c8f2d7d6fd",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_kinematics/CMakeLists.txt"
        ],
        "languages": [
            "CMake"
        ],
        "time": "2014-10-10 (11:29)"
    }
}
```
