### ISSUE TITLE
package ur_kinematics fails to build

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#713]
```yaml
{
    "id": 713,
    "title": "package ur_kinematics fails to build",
    "type": "weakness",
    "description": "The moveit sub-project has factored out kinematics solvers to a separate package moveit_kinematics. This cuased the current version of ur_kinmaitics to fail at compile time, as it did not depend on the new package.  Concretely, a header file was now missing (not installed) to complete C++ compilation. The bug is general -- a missing header file. Could appear in any C/C++ codebase. The fix is ROS-specific, as it is addressed in a ROS-specific build system. The bug was found by ROS build farm, and reported by one of the member developers overseeing the build farm. In TOS the actual creation of an issue is made by a human.\n",
    "cwe": "Missing Build Dependency (no CWE) #EVOLUTION\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "catkin",
        "moveit",
        "dependencies",
        "package.xml"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/ros-planning/moveit/pull/247",
        "https://github.com/aliasrobotics/RVD/issues/713"
    ],
    "flaw": {
        "phase": "compile-time",
        "specificity": "general issue",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_kinematics",
        "languages": [
            "C++"
        ],
        "date-detected": "",
        "detected-by": "compiler",
        "detected-by-method": "N/A",
        "date-reported": "2016-12-29 (14:09)",
        "reported-by": "automatic",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/713",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/275",
        "repo": "https://github.com/ros-industrial/universal_robot/",
        "hash": "f8d175b09ea955ebe83aecbe19105c28f0225524",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_kinematics/CMakeLists.txt",
            "ur_kinematics/package.xml"
        ],
        "languages": [
            "CMake",
            "package.xml"
        ],
        "time": "2016-12-29 (20:34)"
    }
}
```
