### ISSUE TITLE
Runtime dependencies missing in a Python driver module

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#716]
```yaml
{
    "id": 716,
    "title": "Runtime dependencies missing in a Python driver module",
    "type": "weakness",
    "description": "The ur_driver package manifest (package.xml) lacks a runtime dependency on the python parser beatifulsoup.  As an effect the build and installation procedure does not install/require the right python package.  Since package loading is dynamic in python the dependency is only reported when one attempts to start the ur5 driver node. The package manifest is an XML file called package.xml that must be included with any catkin-compliant package's root folder. This file defines properties about the package such as the package name, version numbers, authors, maintainers, and dependencies on other catkin packages. (from ROS wiki) The patch contains also fix for build-time and run-time dependencies on trajectory_msgs package, which were also missing. The issue is ROS-specific as it appears in ROS-specific package.xml files.  However, the issue of missing runtime dependencies overall, is a general software-engineering issue.\n",
    "cwe": "run-time dependency issue (no CWE)\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "catkin",
        "package.xml"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://answers.ros.org/question/103191/in-ur5_driverdriverpy-importerror-no-module-named-beautifulsoup/",
        "http://www.pythonforbeginners.com/beautifulsoup/beautifulsoup-4-python",
        "http://wiki.ros.org/catkin/package.xml",
        "https://github.com/aliasrobotics/RVD/issues/716"
    ],
    "flaw": {
        "phase": "runtime-initialization",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_description",
        "languages": [
            "python"
        ],
        "date-detected": "",
        "detected-by": "runtime detection",
        "detected-by-method": "N/A",
        "date-reported": "2013-11-20 (00:00)",
        "reported-by": "member developer",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/716",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/30",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "58790baa5bf6601f73bc821b5ebd9a24c0a613b4",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "package.xml"
        ],
        "languages": [
            "package.xml"
        ],
        "time": "2013-11-26 (00:00)"
    }
}
```
