### ISSUE TITLE
ur_gazebo depends on gazebo_ros_pkgs meta-package

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#718]
```yaml
{
    "id": 718,
    "title": "ur_gazebo depends on gazebo_ros_pkgs meta-package",
    "type": "weakness",
    "description": "The ur_gazebo package, which is a proper package depends on a meta-package (just a grouping package) gazebo_ros_pkgs, which is not allowed by ROS packaging standards.  Instead it should depend on concrete packages that it actually uses.  See REP-127 linked below; \"Catkin packages must depend directly on the packages they use, not on any metapackages.\" (section <metapackage/>). This causes the build error with the current version of catkin that enforces this rule. The bug is fixed by removing the runtime dependency on gazebo_ros_pkgs and replacing it with a dependency on controller_manager, which seems tot be the actual package needed. Meta-packages in ROS are used to install a number of packages working together (and having actual contents) to be conveniently installed together, while tracking all dependencies.  They cannot export dependencies further, so they should only be used to install groups of packages together by a package manager, not by other packages to depend on them. The issue is ROS-specific as it appears in ROS-specific package.xml files.  Moreover it arises due to the enforcement of a ROS-specific packaging decision.\n",
    "cwe": "run-time dependency issue (no CWE)\ninternal classification (cause):\ninternal classification (effect):\n",
    "cve": "None",
    "keywords": [
        "meta-package",
        "catkin"
    ],
    "system": "universal_robot",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "http://www.ros.org/reps/rep-0127.html",
        "https://github.com/catkin/catkin_tools/issues/370#issuecomment-219157118",
        "https://github.com/aliasrobotics/RVD/issues/718"
    ],
    "flaw": {
        "phase": "build-time",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "driver",
        "package": "ros-industrial/universal_robot/ur_gazebo",
        "languages": [
            "package.xml"
        ],
        "date-detected": "",
        "detected-by": "build system",
        "detected-by-method": "N/A",
        "date-reported": "unreported",
        "reported-by": "unreported",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/718",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ros-industrial/universal_robot/pull/255",
        "repo": "https://github.com/ros-industrial/universal_robot",
        "hash": "0c34123c779d4076a75acf892571f8ec4aa018cc",
        "license": [
            "BSD"
        ],
        "fix-in": [
            "ur_gazebo/package.xml"
        ],
        "languages": [
            "package.xml"
        ],
        "time": "2016-08-22 (18:38)"
    }
}
```
