### ISSUE TITLE
buffer overflow via a large rxpacket

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#724]
```yaml
{
    "id": 724,
    "title": "buffer overflow via a large rxpacket",
    "type": "bug",
    "description": "ROBOTIS Dynamixel SDK through 3.7.11 has a buffer overflow via a large rxpacket.",
    "cwe": "CWE-119",
    "cve": "CVE-2019-15786",
    "keywords": "['vendor: Robotis', 'robot component: Dynamixel', 'robot component: DynamixelSDK']",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "https://github.com/ROBOTIS-GIT/DynamixelSDK/pull/339",
        "https://github.com/aliasrobotics/RVD/issues/724"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "actuation:servo motor",
        "package": "N/A",
        "languages": "['C', 'C++']",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-08-29",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/724",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "https://github.com/ROBOTIS-GIT/DynamixelSDK/pull/339"
    }
}
```
