### ISSUE TITLE
Arbitrary code execution via crafted input data via stack-based buffer overflows

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#726]
```yaml
{
    "id": 726,
    "title": "Arbitrary code execution via crafted input data via stack-based buffer overflows",
    "type": "bug",
    "description": "Multiple stack-based buffer overflows in (1) COM and (2) ActiveX controls in ABB WebWare Server, WebWare SDK, Interlink Module, S4 OPC Server, QuickTeach, RobotStudio S4, and RobotStudio Lite allow remote attackers to execute arbitrary code via crafted input data.",
    "cwe": "CWE-119",
    "cve": "CVE-2012-1801",
    "keywords": "['robot component: ABB WebWare Server', 'robot component: WebWare SDK', 'robot component: Interlink Module', 'robot component: S4 OPC Server', 'robot component: QuickTeach', 'robot component: RobotStudio S4', 'robot component: RobotStudio Lite']",
    "system": "ABB WebWare Server 4.91, ABB WebWare Server 4.6, ABB WebWare Server 4.0, ABB WebWare Server 0, ABB WebWare SDK 4.9, ABB WebWare SDK 4.6, ABB WebWare SDK 0, ABB S4 OPC Server 0, ABB RobotStudio S4 0, ABB RobotStudio Lite 0, ABB RobotStudio 5.14.02, ABB RobotStudio 5.14.01, ABB QuickTeach 0, ABB Interlink Module 4.9, ABB Interlink Module 4.6, ABB Interlink Module 0",
    "vendor": "ABB",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 7.7,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:S/C:C/I:C/A:C"
    },
    "links": [
        "http://secunia.com/advisories/48693",
        "http://www.securityfocus.com/bid/52888",
        "http://www.us-cert.gov/control_systems/pdf/ICSA-12-095-01A.pdf",
        "http://www05.abb.com/global/scot/scot348.nsf/veritydisplay/35df9dc4a94ae83ac12579ca0043acc1/$file/SI10231A2%20rev%200.pdf",
        "https://github.com/aliasrobotics/RVD/issues/726"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "subject-specific",
        "architectural-location": "platform code",
        "application": "Manipulation",
        "subsystem": "cognition:control",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "Terry McCorkle and Billy Rios ",
        "detected-by-method": "N/A",
        "date-reported": "2012-04-18",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/726",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
