### ISSUE TITLE
Untrusted search path vulnerability in ABB RobotStudio

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#727]
```yaml
{
    "id": 727,
    "title": "Untrusted search path vulnerability in ABB RobotStudio",
    "type": "vulnerability",
    "description": "Untrusted search path vulnerability in ABB RobotStudio 5.6x before 5.61.02 and Test Signal Viewer 1.5 allows local users to gain privileges via a Trojan horse DLL that is accessed as a result of incorrect DLL configuration by an optional installation program.",
    "cwe": "CWE-427 (Uncontrolled Search Path Element)",
    "cve": "CVE-2014-5430",
    "keywords": "['robot component: ABB RobotStudio 5.6x', 'robot component: Test Signal Viewer 1.5']",
    "system": "ABB RobotStudio 5.6x before 5.61.02 and Test Signal Viewer 1.5",
    "vendor": "ABB",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 6.9,
        "cvss-vector": "CVSS:3.0/AV:L/AC:M/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "https://ics-cert.us-cert.gov/advisories/ICSA-14-308-01",
        "https://github.com/aliasrobotics/RVD/issues/727",
        "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-5430",
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2014-08-22",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/727",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "Fixed according to this advisory https://www.us-cert.gov/ics/advisories/ICSA-14-308-01",
        "pull-request": "N/A",
        "date-mitigation": "2014-11-04",
    }
}
```
