### ISSUE TITLE
The product CMS-770 (Software Versions 1.7.1 and prior)is vulnera

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#729]
```yaml
{
    "id": 1,
    "title": "The product CMS-770 (Software Versions 1.7.1 and prior)is vulnera",
    "type": "bug",
    "description": "The product CMS-770 (Software Versions 1.7.1 and prior)is vulnerable that an attacker can read sensitive configuration files by bypassing the user authentication mechanism.",
    "cwe": "CWE-287",
    "cve": "CVE-2018-17928",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 3.3,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "http://www.securityfocus.com/bid/106244",
        "https://ics-cert.us-cert.gov/advisories/ICSA-18-352-06"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-01-31",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
