### ISSUE TITLE
potential arbitrary code execution via a vulnerability in the file parser of the Text Editor

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#731]
```yaml
{
    "id": 731,
    "title": "potential arbitrary code execution via a vulnerability in the file parser of the Text Editor",
    "type": "vulnerability",
    "description": "The TextEditor 2.0 in ABB CP400 Panel Builder versions 2.0.7.05 and earlier contain a vulnerability in the file parser of the Text Editor wherein the application doesn't properly prevent the insertion of specially crafted files which could allow arbitrary code execution.",
    "cwe": "CWE-20",
    "cve": "CVE-2018-19008",
    "keywords": "",
    "system": "",
    "vendor": "ABB",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 6.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "http://www.securityfocus.com/bid/106658",
        "https://ics-cert.us-cert.gov/advisories/ICSA-19-017-02",
        "https://github.com/aliasrobotics/RVD/issues/731"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-02-13",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/731",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
