### ISSUE TITLE
The ABB HMI components implement hidden administrative accounts t

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#763]
```yaml
{
    "id": 763,
    "title": "The ABB HMI components implement hidden administrative accounts t",
    "type": "bug",
    "description": "The ABB HMI components implement hidden administrative accounts that are used during the provisioning phase of the HMI interface. These credentials allow the provisioning tool \"Panel Builder 600\" to flash a new interface and Tags (MODBUS coils) mapping to the HMI. These credentials are the idal123 password for the IdalMaster account, and the exor password for the exor account. These credentials are used over both HTTP(S) and FTP. There is no option to disable or change these undocumented credentials. An attacker can use these credentials to login to ABB HMI to read/write HMI configuration files and also to reset the device. This affects ABB CP635 HMI, CP600 HMIClient, Panel Builder 600, IDAL FTP server, IDAL HTTP server, and multiple other HMI components.",
    "cwe": "CWE-798",
    "cve": "CVE-2019-7225",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.8,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "http://packetstormsecurity.com/files/153397/ABB-HMI-Hardcoded-Credentials.html",
        "http://seclists.org/fulldisclosure/2019/Jun/38",
        "http://www.securityfocus.com/bid/108922",
        "https://www.darkmatter.ae/xen1thlabs/abb-hmi-hardcoded-credentials-vulnerability-xl-19-009/",
        "https://github.com/aliasrobotics/RVD/issues/763"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-27",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/763",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
