### ISSUE TITLE
Multiple absolute path traversal vulnerabilities in National Instruments cwui.ocx

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#777]
```yaml
{
    "id": 777,
    "title": "Multiple absolute path traversal vulnerabilities in National Instruments cwui.ocx",
    "type": "vulnerability",
    "description": "Multiple absolute path traversal vulnerabilities in National Instruments cwui.ocx, as used in National Instruments LabWindows/CVI 2012 SP1 and earlier, National Instruments LabVIEW 2012 SP1 and earlier, the Data Analysis component in ABB DataManager 1 through 6.3.6, and other products allow remote attackers to create and execute arbitrary files via a full pathname in an argument to the ExportStyle method in the (1) CWNumEdit, (2) CWGraph, (3) CWBoolean, (4) CWSlide, or (5) CWKnob ActiveX control, in conjunction with file content in the (a) Caption or (b) FormatString property value.",
    "cwe": "CWE-22",
    "cve": "CVE-2013-5021",
    "keywords": "",
    "system": "",
    "vendor": "ABB",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 9.3,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "http://digital.ni.com/public.nsf/allkb/04B876608790082C86257BD1000CC950?OpenDocument",
        "http://digital.ni.com/public.nsf/websearch/507DEC9DA57A708186257B3600512623?OpenDocument",
        "http://www05.abb.com/global/scot/scot203.nsf/veritydisplay/5975a8a86c82eec2c125798e00551522/$file/SECURITY_BULLETIN_-_ABBVU-PACT-3BSE072617_DataManager_Vulnerability.pdf",
        "http://zerodayinitiative.com/advisories/ZDI-13-120/",
        "https://github.com/aliasrobotics/RVD/issues/777"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2013-08-06",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/777",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
