### ISSUE TITLE
An Unprotected Transport of Credentials issue was discovered in A

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#778]
```yaml
{
    "id": 1,
    "title": "An Unprotected Transport of Credentials issue was discovered in A",
    "type": "bug",
    "description": "An Unprotected Transport of Credentials issue was discovered in ABB Ellipse 8.3 through Ellipse 8.9 released prior to December 2017 (including Ellipse Select). A vulnerability exists in the authentication of Ellipse to LDAP/AD using the LDAP protocol. An attacker could exploit the vulnerability by sniffing local network traffic, allowing the discovery of authentication credentials.",
    "cwe": "CWE-522",
    "cve": "CVE-2017-16731",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 2.9,
        "cvss-vector": "CVSS:3.0/AV:A/AC:M/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "https://ics-cert.us-cert.gov/advisories/ICSA-17-353-01"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2017-12-20",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
