### ISSUE TITLE
An Improper Input Validation issue was discovered in ABB FOX515T 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#783]
```yaml
{
    "id": 783,
    "title": "An Improper Input Validation issue was discovered in ABB FOX515T ",
    "type": "bug",
    "description": "An Improper Input Validation issue was discovered in ABB FOX515T release 1.0. An improper input validation vulnerability has been identified, allowing a local attacker to provide a malicious parameter to the script that is not validated by the application, This could enable the attacker to retrieve any file on the server.",
    "cwe": "CWE-20",
    "cve": "CVE-2017-14025",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 2.1,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "http://www.securityfocus.com/bid/101662",
        "https://ics-cert.us-cert.gov/advisories/ICSA-17-304-01",
        "https://github.com/aliasrobotics/RVD/issues/783"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2017-11-06",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/783",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
