### ISSUE TITLE
The embedded web server on ABB Fox515T 1.0 devices is vulnerable 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#784]
```yaml
{
    "id": 784,
    "title": "The embedded web server on ABB Fox515T 1.0 devices is vulnerable ",
    "type": "bug",
    "description": "The embedded web server on ABB Fox515T 1.0 devices is vulnerable to Local File Inclusion. It accepts a parameter that specifies a file for display or for use as a template. The filename is not validated; an attacker could retrieve any file.",
    "cwe": "CWE-200",
    "cve": "CVE-2017-15583",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "http://search-ext.abb.com/library/Download.aspx?DocumentID=1KHW028693&LanguageCode=en&DocumentPartId=&Action=Launch",
        "https://github.com/aliasrobotics/RVD/issues/784"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2017-10-18",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/784",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
