### ISSUE TITLE
Pluto Safety PLC Gateway Ethernet devices in ABB GATE-E1 and GATE

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#787]
```yaml
{
    "id": 1,
    "title": "Pluto Safety PLC Gateway Ethernet devices in ABB GATE-E1 and GATE",
    "type": "bug",
    "description": "Pluto Safety PLC Gateway Ethernet devices in ABB GATE-E1 and GATE-E2 all versions allows an unauthenticated attacker using the administrative web interface to insert an HTML/Javascript payload into any of the device properties, which may allow an attacker to display/execute the payload in a visitor browser.",
    "cwe": "CWE-79",
    "cve": "CVE-2018-18997",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 4.3,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:N/I:P/A:N"
    },
    "links": [
        "http://www.securityfocus.com/bid/106247",
        "https://ics-cert.us-cert.gov/advisories/ICSA-18-352-01"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-01-03",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
