### ISSUE TITLE
In ABB IP GATEWAY 3.39 and prior, some configuration files contai

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#801]
```yaml
{
    "id": 801,
    "title": "In ABB IP GATEWAY 3.39 and prior, some configuration files contai",
    "type": "bug",
    "description": "In ABB IP GATEWAY 3.39 and prior, some configuration files contain passwords stored in plain-text, which may allow an attacker to gain unauthorized access.",
    "cwe": "CWE-522",
    "cve": "CVE-2017-7933",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "http://www.securityfocus.com/bid/104388",
        "https://ics-cert.us-cert.gov/advisories/ICSA-18-156-01",
        "https://github.com/aliasrobotics/RVD/issues/801"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-06-06",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/801",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
