### ISSUE TITLE
The product M2M ETHERNET (FW Versions 2.22 and prior, ETH-FW Vers

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#803]
```yaml
{
    "id": 803,
    "title": "The product M2M ETHERNET (FW Versions 2.22 and prior, ETH-FW Vers",
    "type": "bug",
    "description": "The product M2M ETHERNET (FW Versions 2.22 and prior, ETH-FW Versions 1.01 and prior) is vulnerable in that an attacker can upload a malicious language file by bypassing the user authentication mechanism.",
    "cwe": "CWE-287",
    "cve": "CVE-2018-17926",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 3.3,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:N/C:N/I:P/A:N"
    },
    "links": [
        "http://www.securityfocus.com/bid/106243",
        "https://ics-cert.us-cert.gov/advisories/ICSA-18-352-07",
        "https://github.com/aliasrobotics/RVD/issues/803"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-01-31",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/803",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
