### ISSUE TITLE
ABB Panel Builder 800 all versions has an improper input validati

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#805]
```yaml
{
    "id": 1,
    "title": "ABB Panel Builder 800 all versions has an improper input validati",
    "type": "bug",
    "description": "ABB Panel Builder 800 all versions has an improper input validation vulnerability which may allow an attacker to insert and run arbitrary code on a computer where the affected product is used.",
    "cwe": "CWE-20",
    "cve": "CVE-2018-10616",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 9.3,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "http://search-ext.abb.com/library/Download.aspx?DocumentID=3BSE092089&Action=Launch",
        "http://www.securityfocus.com/bid/104882",
        "https://ics-cert.us-cert.gov/advisories/ICSA-18-198-01"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-07-18",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
