### ISSUE TITLE
The ABB IDAL HTTP server CGI interface contains a URL that allows

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#815]
```yaml
{
    "id": 815,
    "title": "The ABB IDAL HTTP server CGI interface contains a URL that allows",
    "type": "bug",
    "description": "The ABB IDAL HTTP server CGI interface contains a URL that allows an unauthenticated attacker to bypass authentication and gain access to privileged functions. Specifically, /cgi/loginDefaultUser creates a session in an authenticated state and returns the session ID along with what may be the username and cleartext password of the user. An attacker can then supply an IDALToken value in a cookie, which will allow them to perform privileged operations such as restarting the service with /cgi/restart. A GET request to /cgi/loginDefaultUser may result in \"1 #S_OK IDALToken=532c8632b86694f0232a68a0897a145c admin admin\" or a similar response.",
    "cwe": "CWE-287",
    "cve": "CVE-2019-7226",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.8,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "http://packetstormsecurity.com/files/153402/ABB-IDAL-HTTP-Server-Authentication-Bypass.html",
        "http://seclists.org/fulldisclosure/2019/Jun/39",
        "http://www.securityfocus.com/bid/108886",
        "https://www.darkmatter.ae/xen1thlabs/abb-idal-http-server-authentication-bypass-vulnerability-xl-19-010/",
        "https://github.com/aliasrobotics/RVD/issues/815"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-27",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/815",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
