### ISSUE TITLE
In the ABB IDAL FTP server, an authenticated attacker can travers

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#822]
```yaml
{
    "id": 822,
    "title": "In the ABB IDAL FTP server, an authenticated attacker can travers",
    "type": "bug",
    "description": "In the ABB IDAL FTP server, an authenticated attacker can traverse to arbitrary directories on the hard disk with \"CWD ../\" and then use the FTP server functionality to download and upload files. An unauthenticated attacker can take advantage of the hardcoded or default credential pair exor/exor to become an authenticated attacker.",
    "cwe": "CWE-22",
    "cve": "CVE-2019-7227",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 4.1,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:S/C:P/I:P/A:N"
    },
    "links": [
        "http://packetstormsecurity.com/files/153396/ABB-IDAL-FTP-Server-Path-Traversal.html",
        "http://seclists.org/fulldisclosure/2019/Jun/37",
        "http://www.securityfocus.com/bid/108886",
        "https://search.abb.com/library/Download.aspx?DocumentID=3ADR010377&LanguageCode=en&DocumentPartId=&Action=Launch",
        "https://www.darkmatter.ae/xen1thlabs/abb-idal-ftp-server-path-traversal-vulnerability-xl-19-008/",
        "https://github.com/aliasrobotics/RVD/issues/822"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-27",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/822",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
