### ISSUE TITLE
The ABB IDAL FTP server mishandles format strings in a username d

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#824]
```yaml
{
    "id": 824,
    "title": "The ABB IDAL FTP server mishandles format strings in a username d",
    "type": "bug",
    "description": "The ABB IDAL FTP server mishandles format strings in a username during the authentication process. Attempting to authenticate with the username %s%p%x%d will crash the server. Sending %08x.AAAA.%08x.%08x will log memory content from the stack.",
    "cwe": "CWE-287",
    "cve": "CVE-2019-7230",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.8,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "http://packetstormsecurity.com/files/153386/ABB-IDAL-FTP-Server-Uncontrolled-Format-String.html",
        "http://seclists.org/fulldisclosure/2019/Jun/33",
        "http://www.securityfocus.com/bid/108886",
        "https://search.abb.com/library/Download.aspx?DocumentID=3ADR010377&LanguageCode=en&DocumentPartId=&Action=Launch",
        "https://www.darkmatter.ae/xen1thlabs/published-advisories/",
        "https://github.com/aliasrobotics/RVD/issues/824"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-24",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/824",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
