### ISSUE TITLE
The ABB IDAL FTP server is vulnerable to a buffer overflow when a

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#825]
```yaml
{
    "id": 825,
    "title": "The ABB IDAL FTP server is vulnerable to a buffer overflow when a",
    "type": "bug",
    "description": "The ABB IDAL FTP server is vulnerable to a buffer overflow when a long string is sent by an authenticated attacker. This overflow is handled, but terminates the process. An authenticated attacker can send a FTP command string of 472 bytes or more to overflow a buffer, causing an exception that terminates the server.",
    "cwe": "CWE-119",
    "cve": "CVE-2019-7231",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 2.7,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:S/C:N/I:N/A:P"
    },
    "links": [
        "http://packetstormsecurity.com/files/153395/ABB-IDAL-FTP-Server-Buffer-Overflow.html",
        "http://seclists.org/fulldisclosure/2019/Jun/35",
        "http://www.securityfocus.com/bid/108886",
        "https://search.abb.com/library/Download.aspx?DocumentID=3ADR010377&LanguageCode=en&DocumentPartId=&Action=Launch",
        "https://www.darkmatter.ae/xen1thlabs/published-advisories/",
        "https://github.com/aliasrobotics/RVD/issues/825"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-24",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/825",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
