### ISSUE TITLE
Multiple stack-based buffer overflows in RobNetScanHost.exe in AB

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#827]
```yaml
{
    "id": 827,
    "title": "Multiple stack-based buffer overflows in RobNetScanHost.exe in AB",
    "type": "bug",
    "description": "Multiple stack-based buffer overflows in RobNetScanHost.exe in ABB Robot Communications Runtime before 5.14.02, as used in ABB Interlink Module, IRC5 OPC Server, PC SDK, PickMaster 3 and 5, RobView 5, RobotStudio, WebWare SDK, and WebWare Server, allow remote attackers to execute arbitrary code via a crafted (1) 0xA or (2) 0xE Netscan packet.",
    "cwe": "CWE-119",
    "cve": "CVE-2012-0245",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 10.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "http://archives.neohapsis.com/archives/bugtraq/2012-02/0125.html",
        "http://secunia.com/advisories/48090",
        "http://www.securityfocus.com/bid/52123",
        "http://www.us-cert.gov/control_systems/pdf/ICSA-12-059-01.pdf",
        "http://www.zerodayinitiative.com/advisories/ZDI-12-033/",
        "http://www05.abb.com/global/scot/scot348.nsf/veritydisplay/f261be074480dc24c12579a00049ecd5/$file/si10227a1%20vulnerability%20security%20advisory.pdf",
        "https://github.com/aliasrobotics/RVD/issues/827"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2012-03-09",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/827",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
