### ISSUE TITLE
ABB PCM600 before 2.7 uses an improper hash algorithm for the mai

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#828]
```yaml
{
    "id": 1,
    "title": "ABB PCM600 before 2.7 uses an improper hash algorithm for the mai",
    "type": "bug",
    "description": "ABB PCM600 before 2.7 uses an improper hash algorithm for the main application password, which makes it easier for local users to obtain sensitive cleartext information by leveraging read access to the ACTConfig configuration file.",
    "cwe": "CWE-310",
    "cve": "CVE-2016-4511",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 1.9,
        "cvss-vector": "CVSS:3.0/AV:L/AC:M/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "https://ics-cert.us-cert.gov/advisories/ICSA-16-152-02"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2016-06-10",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
