### ISSUE TITLE
ABB PCM600 before 2.7 improperly stores the main application pass

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#829]
```yaml
{
    "id": 1,
    "title": "ABB PCM600 before 2.7 improperly stores the main application pass",
    "type": "bug",
    "description": "ABB PCM600 before 2.7 improperly stores the main application password after a password change, which allows local users to obtain sensitive information via unspecified vectors.",
    "cwe": "CWE-200",
    "cve": "CVE-2016-4516",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 2.1,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "https://ics-cert.us-cert.gov/advisories/ICSA-16-152-02"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2016-06-10",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
