### ISSUE TITLE
Buffer overflow in x87 before 3.5.5 in ABB Process Communication 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#832]
```yaml
{
    "id": 1,
    "title": "Buffer overflow in x87 before 3.5.5 in ABB Process Communication ",
    "type": "bug",
    "description": "Buffer overflow in x87 before 3.5.5 in ABB Process Communication Unit 400 (PCU400) 4.4 through 4.6 allows remote attackers to execute arbitrary code via a crafted packet using the (1) IEC60870-5-101 or (2) IEC60870-5-104 communication protocol to the X87 web interface. This issue is corrected in version 3.5.5 of the x87 executable. To obtain a patch or upgrade software please contact your vendor. The x87 executable is considered obsolete in newer versions of the PCU 400 and should be replaced\r\nby the newer x88 or x89 executable where applicable.\r\n\r\nLink to contact information: http://www.abb.com/industries/db0003db004333/c12573e7003305cbc1257074003d0702.aspx?productLanguage=us&country=US&tabKey=Contacts",
    "cwe": "CWE-119",
    "cve": "CVE-2008-2474",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 10.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "http://secunia.com/advisories/32047",
        "http://securityreason.com/securityalert/4320",
        "http://www.kb.cert.org/vuls/id/343971",
        "http://www.kb.cert.org/vuls/id/CTAR-7JTNRX",
        "http://www.securityfocus.com/archive/1/496739/100/0/threaded",
        "http://www.securityfocus.com/bid/31391"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2008-09-29",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
