### ISSUE TITLE
ABB, Phoenix Contact, Schneider Electric, Siemens, WAGO - Program

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#836]
```yaml
{
    "id": 836,
    "title": "ABB, Phoenix Contact, Schneider Electric, Siemens, WAGO - Program",
    "type": "bug",
    "description": "ABB, Phoenix Contact, Schneider Electric, Siemens, WAGO - Programmable Logic Controllers, multiple versions. Researchers have found some controllers are susceptible to a denial-of-service attack due to a flood of network packets.",
    "cwe": "CWE-400",
    "cve": "CVE-2019-10953",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:N/I:N/A:P"
    },
    "links": [
        "http://www.securityfocus.com/bid/108413",
        "https://ics-cert.us-cert.gov/advisories/ICSA-19-106-03",
        "https://github.com/aliasrobotics/RVD/issues/836"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-04-17",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/836",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
