### ISSUE TITLE
Multiple stack-based buffer overflows in (1) COM and (2) ActiveX 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#837]
```yaml
{
    "id": 837,
    "title": "Multiple stack-based buffer overflows in (1) COM and (2) ActiveX ",
    "type": "bug",
    "description": "Multiple stack-based buffer overflows in (1) COM and (2) ActiveX controls in ABB WebWare Server, WebWare SDK, Interlink Module, S4 OPC Server, QuickTeach, RobotStudio S4, and RobotStudio Lite allow remote attackers to execute arbitrary code via crafted input data.",
    "cwe": "CWE-119",
    "cve": "CVE-2012-1801",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 7.7,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:S/C:C/I:C/A:C"
    },
    "links": [
        "http://secunia.com/advisories/48693",
        "http://www.securityfocus.com/bid/52888",
        "http://www.us-cert.gov/control_systems/pdf/ICSA-12-095-01A.pdf",
        "http://www05.abb.com/global/scot/scot348.nsf/veritydisplay/35df9dc4a94ae83ac12579ca0043acc1/$file/SI10231A2%20rev%200.pdf",
        "https://github.com/aliasrobotics/RVD/issues/837"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2012-04-18",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/837",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
