### ISSUE TITLE
In ABB SREA-01 revisions A, B, C: application versions up to 3.31

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#850]
```yaml
{
    "id": 850,
    "title": "In ABB SREA-01 revisions A, B, C: application versions up to 3.31",
    "type": "bug",
    "description": "In ABB SREA-01 revisions A, B, C: application versions up to 3.31.5, and SREA-50 revision A: application versions up to 3.32.8, an attacker may access internal files of ABB SREA-01 and SREA-50 legacy remote monitoring tools without any authorization over the network using a HTTP request which refers to files using ../../ relative paths. Once the internal password file is retrieved, the password hash can be identified using a brute force attack. There is also an exploit allowing running of commands after authorization.",
    "cwe": "CWE-22",
    "cve": "CVE-2017-9664",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "http://www.securityfocus.com/bid/100260",
        "https://ics-cert.us-cert.gov/advisories/ICSA-17-222-05",
        "https://github.com/aliasrobotics/RVD/issues/850"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-05-24",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/850",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
