### ISSUE TITLE
This vulnerability allows local attackers to escalate privileges 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#852]
```yaml
{
    "id": 1,
    "title": "This vulnerability allows local attackers to escalate privileges ",
    "type": "bug",
    "description": "This vulnerability allows local attackers to escalate privileges on vulnerable installations of ABB MicroSCADA 9.3 with FP 1-2-3. An attacker must first obtain the ability to execute low-privileged code on the target system in order to exploit this vulnerability. The specific flaw exists within the configuration of the access controls for the installed product files. The installation procedure leaves critical files open to manipulation by any authenticated user. An attacker can leverage this vulnerability to escalate privileges to SYSTEM. Was ZDI-CAN-5097.",
    "cwe": "CWE-732",
    "cve": "CVE-2018-1168",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 7.2,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "https://library.e.abb.com/public/7a88a74b12bb492ea138b1f2365d00f6/ABBVU-PGGA-33888_ABB_SoftwareVulnerabilityHandlingAdvisory_Rev_A.pdf?x-sign=MJfu9cHtRUUubpLAYzyWFTmW5W+mg3kZ/nm7F/Jw5HlFTQf4eNyfLAgE8HozRJEC",
        "https://zerodayinitiative.com/advisories/ZDI-18-141"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-02-21",
        "reported-by": "cve@mitre.org",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
