### ISSUE TITLE
roller 8.23 allows Directory Traversal via a forged HTTP request.

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#868]
```yaml
{
    "id": 1,
    "title": "roller 8.23 allows Directory Traversal via a forged HTTP request.",
    "type": "bug",
    "description": "The remote admin webserver on FANUC Robotics Virtual Robot Controller 8.23 allows Directory Traversal via a forged HTTP request.",
    "cwe": "None",
    "cve": "CVE-2019-13584",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": "https://vulners.com/cve/CVE-2019-13584",
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-07-17",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
