### ISSUE TITLE
In all versions of ABB Power Generation Information Manager (PGIM

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#873]
```yaml
{
    "id": 1,
    "title": "In all versions of ABB Power Generation Information Manager (PGIM",
    "type": "vulnerability",
    "description": "In all versions of ABB Power Generation Information Manager (PGIM) and Plant Connect, the affected product is vulnerable to authentication bypass, which may allow an attacker to remotely bypass authentication and extract credentials from the affected device.",
    "cwe": "None",
    "cve": "CVE-2019-18250",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0.0,
        "cvss-vector": "CVSS:3.0/NONE"
    },
    "links": "https://vulners.com/cve/CVE-2019-18250",
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-11-26",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
