### ISSUE TITLE
In the ABB IDAL FTP server, an authenticated attacker can travers

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#876]
```yaml
{
    "id": 876,
    "title": "In the ABB IDAL FTP server, an authenticated attacker can travers",
    "type": "vulnerability",
    "description": "In the ABB IDAL FTP server, an authenticated attacker can traverse to arbitrary directories on the hard disk with \"CWD ../\" and then use the FTP server functionality to download and upload files. An unauthenticated attacker can take advantage of the hardcoded or default credential pair exor/exor to become an authenticated attacker.",
    "cwe": "None",
    "cve": "CVE-2019-7227",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 4.1,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:S/C:P/I:P/A:N"
    },
    "links": [
        "https://vulners.com/cve/CVE-2019-7227",
        "https://github.com/aliasrobotics/RVD/issues/876"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-27",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/876",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
