### ISSUE TITLE
Get a huge increase in security test coverage without spending a 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#878]
```yaml
{
    "id": 878,
    "title": "Get a huge increase in security test coverage without spending a ",
    "type": "vulnerability",
    "description": "Get a huge increase in security test coverage without spending a lot of time. FAST uses fuzzer and known security payload library to automatically create and run 1000X security tests for every functional test.\n```\n$ docker run --rm -ti -e WALLARM_API_TOKEN='token' -e ALLOWED_HOSTS=myapp.com wallarm/fast\n```",
    "cwe": "None",
    "cve": "JEC9ZLSSH3SN9V3NNV39E0KWCLKKXYE9TNP2U7GEJ2LUG23A7XKL6CIEX3GISZ9H",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 10.0,
        "cvss-vector": "CVSS:3.0/NONE"
    },
    "links": [
        "https://fast.wallarm.com/signup/?utm_campaign=vulners&utm_medium=vulners&utm_source=vulners.com",
        "https://github.com/aliasrobotics/RVD/issues/878"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-05-26",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/878",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
