### ISSUE TITLE
The ABB IDAL FTP server is vulnerable to a buffer overflow when a

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#879]
```yaml
{
    "id": 879,
    "title": "The ABB IDAL FTP server is vulnerable to a buffer overflow when a",
    "type": "vulnerability",
    "description": "The ABB IDAL FTP server is vulnerable to a buffer overflow when a long string is sent by an authenticated attacker. This overflow is handled, but terminates the process. An authenticated attacker can send a FTP command string of 472 bytes or more to overflow a buffer, causing an exception that terminates the server.",
    "cwe": "None",
    "cve": "CVE-2019-7231",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 2.7,
        "cvss-vector": "CVSS:3.0/AV:A/AC:L/Au:S/C:N/I:N/A:P"
    },
    "links": [
        "https://vulners.com/cve/CVE-2019-7231",
        "https://github.com/aliasrobotics/RVD/issues/879"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-24",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/879",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
