### ISSUE TITLE
The ABB CP635 HMI uses two different transmission methods to upgr

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#880]
```yaml
{
    "id": 880,
    "title": "The ABB CP635 HMI uses two different transmission methods to upgr",
    "type": "vulnerability",
    "description": "The ABB CP635 HMI uses two different transmission methods to upgrade its firmware and its software components: \"Utilization of USB/SD Card to flash the device\" and \"Remote provisioning process via ABB Panel Builder 600 over FTP.\" Neither of these transmission methods implements any form of encryption or authenticity checks against the new firmware HMI software binary files.",
    "cwe": "None",
    "cve": "CVE-2019-7229",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.4,
        "cvss-vector": "CVSS:3.0/AV:A/AC:M/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "https://vulners.com/cve/CVE-2019-7229",
        "https://github.com/aliasrobotics/RVD/issues/880"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-06-24",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/880",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
