### ISSUE TITLE
The TextEditor 2.0 in ABB CP400 Panel Builder versions 2.0.7.05 a

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#884]
```yaml
{
    "id": 884,
    "title": "The TextEditor 2.0 in ABB CP400 Panel Builder versions 2.0.7.05 a",
    "type": "vulnerability",
    "description": "The TextEditor 2.0 in ABB CP400 Panel Builder versions 2.0.7.05 and earlier contain a vulnerability in the file parser of the Text Editor wherein the application doesn't properly prevent the insertion of specially crafted files which could allow arbitrary code execution.",
    "cwe": "None",
    "cve": "CVE-2018-19008",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 6.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "https://vulners.com/cve/CVE-2018-19008",
        "https://github.com/aliasrobotics/RVD/issues/884"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-02-13",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/884",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
