### ISSUE TITLE
ABB Relion 630 devices 1.1 before 1.1.0.C0, 1.2 before 1.2.0.B3, 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#887]
```yaml
{
    "id": 887,
    "title": "ABB Relion 630 devices 1.1 before 1.1.0.C0, 1.2 before 1.2.0.B3, ",
    "type": "vulnerability",
    "description": "ABB Relion 630 devices 1.1 before 1.1.0.C0, 1.2 before 1.2.0.B3, and 1.3 before 1.3.0.A6 allow remote attackers to cause a denial of service (reboot) via a reboot command in an SPA message.",
    "cwe": "None",
    "cve": "CVE-2018-20720",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 7.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:N/I:N/A:C"
    },
    "links": [
        "https://vulners.com/cve/CVE-2018-20720",
        "https://github.com/aliasrobotics/RVD/issues/887"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-01-16",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/887",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
