### ISSUE TITLE
Pluto Safety PLC Gateway Ethernet devices ABB GATE-E1 and GATE-E2

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#889]
```yaml
{
    "id": 889,
    "title": "Pluto Safety PLC Gateway Ethernet devices ABB GATE-E1 and GATE-E2",
    "type": "vulnerability",
    "description": "Pluto Safety PLC Gateway Ethernet devices ABB GATE-E1 and GATE-E2 all versions do not allow authentication to be configured on administrative telnet or web interfaces, which could enable various effects vectors, including conducting device resets, reading or modifying registers, and changing configuration settings such as IP addresses.",
    "cwe": "None",
    "cve": "CVE-2018-18995",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "https://vulners.com/cve/CVE-2018-18995",
        "https://github.com/aliasrobotics/RVD/issues/889"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2019-01-03",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/889",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
