### ISSUE TITLE
ABB Panel Builder 800 all versions has an improper input validati

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#891]
```yaml
{
    "id": 891,
    "title": "ABB Panel Builder 800 all versions has an improper input validati",
    "type": "vulnerability",
    "description": "ABB Panel Builder 800 all versions has an improper input validation vulnerability which may allow an attacker to insert and run arbitrary code on a computer where the affected product is used.",
    "cwe": "None",
    "cve": "CVE-2018-10616",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 9.3,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "https://vulners.com/cve/CVE-2018-10616",
        "https://github.com/aliasrobotics/RVD/issues/891"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-07-18",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/891",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
