### ISSUE TITLE
In ABB IP GATEWAY 3.39 and prior, by accessing a specific uniform

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#892]
```yaml
{
    "id": 892,
    "title": "In ABB IP GATEWAY 3.39 and prior, by accessing a specific uniform",
    "type": "vulnerability",
    "description": "In ABB IP GATEWAY 3.39 and prior, by accessing a specific uniform resource locator (URL) on the web server, a malicious user is able to access the configuration files and application pages without authentication.",
    "cwe": "None",
    "cve": "CVE-2017-7931",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "https://vulners.com/cve/CVE-2017-7931",
        "https://github.com/aliasrobotics/RVD/issues/892"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-06-06",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/892",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
