### ISSUE TITLE
In ABB IP GATEWAY 3.39 and prior, the web server does not suffici

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#894]
```yaml
{
    "id": 894,
    "title": "In ABB IP GATEWAY 3.39 and prior, the web server does not suffici",
    "type": "vulnerability",
    "description": "In ABB IP GATEWAY 3.39 and prior, the web server does not sufficiently verify that a request was performed by the authenticated user, which may allow an attacker to launch a request impersonating that user.",
    "cwe": "None",
    "cve": "CVE-2017-7906",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 6.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:P/I:P/A:P"
    },
    "links": [
        "https://vulners.com/cve/CVE-2017-7906",
        "https://github.com/aliasrobotics/RVD/issues/894"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-06-06",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/894",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
