### ISSUE TITLE
An Information Exposure issue was discovered in ABB netCADOPS Web

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#897]
```yaml
{
    "id": 897,
    "title": "An Information Exposure issue was discovered in ABB netCADOPS Web",
    "type": "vulnerability",
    "description": "An Information Exposure issue was discovered in ABB netCADOPS Web Application Version 3.4 and prior, netCADOPS Web Application Version 7.1 and prior, netCADOPS Web Application Version 7.2x and prior, netCADOPS Web Application Version 8.0 and prior, and netCADOPS Web Application Version 8.1 and prior. A vulnerability exists in the password entry section of netCADOPS Web Application that may expose critical database information.",
    "cwe": "None",
    "cve": "CVE-2018-5477",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "https://vulners.com/cve/CVE-2018-5477",
        "https://github.com/aliasrobotics/RVD/issues/897"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-02-20",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/897",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
