### ISSUE TITLE
cgi-bin/write.cgi in Anti-Web through 3.8.7, as used on NetBiter 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#898]
```yaml
{
    "id": 1,
    "title": "cgi-bin/write.cgi in Anti-Web through 3.8.7, as used on NetBiter ",
    "type": "vulnerability",
    "description": "cgi-bin/write.cgi in Anti-Web through 3.8.7, as used on NetBiter / HMS, Ouman EH-net, Alliance System WS100 --> AWU 500, Sauter ERW100F001, Carlo Gavazzi SIU-DLG, AEDILIS SMART-1, SYXTHSENSE WebBiter, ABB SREA, and ASCON DY WebServer devices, allows remote authenticated users to execute arbitrary OS commands via crafted multipart/form-data content, a different vulnerability than CVE-2017-9097.",
    "cwe": "None",
    "cve": "CVE-2017-17888",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 9.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:S/C:C/I:C/A:C"
    },
    "links": "https://vulners.com/cve/CVE-2017-17888",
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2017-12-27",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
