### ISSUE TITLE
RVD#902: An Improper Authentication issue was discovered in ABB VSN300 WiF

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#902]
```yaml
{
    "id": 902,
    "title": "RVD#902: An Improper Authentication issue was discovered in ABB VSN300 WiF",
    "type": "vulnerability",
    "description": "An Improper Authentication issue was discovered in ABB VSN300 WiFi Logger Card versions 1.8.15 and prior, and VSN300 WiFi Logger Card for React versions 2.1.3 and prior. By accessing a specific uniform resource locator (URL) on the web server, a malicious user is able to access internal information about status and connected devices without authenticating.",
    "cwe": "None",
    "cve": "CVE-2017-7920",
    "keywords": "",
    "system": "",
    "vendor": " ABB",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 5.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "https://vulners.com/cve/CVE-2017-7920",
        "https://github.com/aliasrobotics/RVD/issues/902"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2017-08-07",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/902",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
