### ISSUE TITLE
A Permissions, Privileges, and Access Controls issue was discover

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#903]
```yaml
{
    "id": 903,
    "title": "A Permissions, Privileges, and Access Controls issue was discover",
    "type": "vulnerability",
    "description": "A Permissions, Privileges, and Access Controls issue was discovered in ABB VSN300 WiFi Logger Card versions 1.8.15 and prior, and VSN300 WiFi Logger Card for React versions 2.1.3 and prior. The web application does not properly restrict privileges of the Guest account. A malicious user may be able to gain access to configuration information that should be restricted.",
    "cwe": "None",
    "cve": "CVE-2017-7916",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 4.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:S/C:P/I:N/A:N"
    },
    "links": [
        "https://vulners.com/cve/CVE-2017-7916",
        "https://github.com/aliasrobotics/RVD/issues/903"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2017-08-07",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/903",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
