### ISSUE TITLE
ABB DataManagerPro 1.x before 1.7.1 allows local users to gain pr

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#904]
```yaml
{
    "id": 1,
    "title": "ABB DataManagerPro 1.x before 1.7.1 allows local users to gain pr",
    "type": "vulnerability",
    "description": "ABB DataManagerPro 1.x before 1.7.1 allows local users to gain privileges by replacing a DLL file in the package directory.",
    "cwe": "None",
    "cve": "CVE-2016-4526",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 6.9,
        "cvss-vector": "CVSS:3.0/AV:L/AC:M/Au:N/C:C/I:C/A:C"
    },
    "links": "https://vulners.com/cve/CVE-2016-4526",
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2016-09-19",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
