### ISSUE TITLE
ABB PCM600 before 2.7 improperly stores OPC Server IEC61850 passw

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#905]
```yaml
{
    "id": 905,
    "title": "ABB PCM600 before 2.7 improperly stores OPC Server IEC61850 passw",
    "type": "vulnerability",
    "description": "ABB PCM600 before 2.7 improperly stores OPC Server IEC61850 passwords in unspecified temporary circumstances, which allows local users to obtain sensitive information via unknown vectors.",
    "cwe": "None",
    "cve": "CVE-2016-4524",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 2.1,
        "cvss-vector": "CVSS:3.0/AV:L/AC:L/Au:N/C:P/I:N/A:N"
    },
    "links": [
        "https://vulners.com/cve/CVE-2016-4524",
        "https://github.com/aliasrobotics/RVD/issues/905"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2016-06-10",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/905",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
