### ISSUE TITLE
Untrusted search path vulnerability in ABB Panel Builder 800 5.1 

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#909]
```yaml
{
    "id": 909,
    "title": "Untrusted search path vulnerability in ABB Panel Builder 800 5.1 ",
    "type": "vulnerability",
    "description": "Untrusted search path vulnerability in ABB Panel Builder 800 5.1 allows local users to gain privileges via a Trojan horse DLL in the current working directory.",
    "cwe": "None",
    "cve": "CVE-2016-2281",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 6.0,
        "cvss-vector": "CVSS:3.0/AV:L/AC:H/Au:S/C:C/I:C/A:C"
    },
    "links": [
        "https://vulners.com/cve/CVE-2016-2281",
        "https://github.com/aliasrobotics/RVD/issues/909"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2016-03-18",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/909",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
