### ISSUE TITLE
Untrusted search path vulnerability in ABB RobotStudio 5.6x befor

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#910]
```yaml
{
    "id": 1,
    "title": "Untrusted search path vulnerability in ABB RobotStudio 5.6x befor",
    "type": "vulnerability",
    "description": "Untrusted search path vulnerability in ABB RobotStudio 5.6x before 5.61.02 and Test Signal Viewer 1.5 allows local users to gain privileges via a Trojan horse DLL that is accessed as a result of incorrect DLL configuration by an optional installation program.\n<a href=\"http://cwe.mitre.org/data/definitions/427.html\"> CWE-427: Uncontrolled Search Path Element </a>",
    "cwe": "None",
    "cve": "CVE-2014-5430",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 6.9,
        "cvss-vector": "CVSS:3.0/AV:L/AC:M/Au:N/C:C/I:C/A:C"
    },
    "links": "https://vulners.com/cve/CVE-2014-5430",
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2014-11-07",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
