### ISSUE TITLE
Multiple stack-based buffer overflows in RobNetScanHost.exe in AB

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#913]
```yaml
{
    "id": 913,
    "title": "Multiple stack-based buffer overflows in RobNetScanHost.exe in AB",
    "type": "vulnerability",
    "description": "Multiple stack-based buffer overflows in RobNetScanHost.exe in ABB Robot Communications Runtime before 5.14.02, as used in ABB Interlink Module, IRC5 OPC Server, PC SDK, PickMaster 3 and 5, RobView 5, RobotStudio, WebWare SDK, and WebWare Server, allow remote attackers to execute arbitrary code via a crafted (1) 0xA or (2) 0xE Netscan packet.",
    "cwe": "None",
    "cve": "CVE-2012-0245",
    "keywords": "",
    "system": "",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 10.0,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/Au:N/C:C/I:C/A:C"
    },
    "links": [
        "https://vulners.com/cve/CVE-2012-0245",
        "https://github.com/aliasrobotics/RVD/issues/913"
    ],
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2012-03-09",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "https://github.com/aliasrobotics/RVD/issues/913",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
