### ISSUE TITLE
RVD#918: buffer overflow allows attackers to cause a denial of service and possibly execute code

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#918]
```yaml
{
    "id": 918,
    "title": "RVD#918: buffer overflow allows attackers to cause a denial of service and possibly execute code",
    "type": "vulnerability",
    "description": "An issue was discovered in the ROS communications-related packages (aka ros_comm or ros-melodic-ros-comm) through 1.14.3. A buffer overflow allows attackers to cause a denial of service and possibly execute arbitrary code via an IP address with a long hostname.",
    "cwe": "None",
    "cve": "CVE-2019-13566",
    "keywords": "['robot component: ROS', 'package: ros_comm']",
    "system": "",
    "vendor": "N/A",
    "severity": {
        "rvss-score": "N/A",
        "rvss-vector": "\"\"",
        "severity-description": "",
        "cvss-score": "N/A",
        "cvss-vector": "\"\""
    },
    "links": [
        "['https://vulners.com/cve/CVE-2019-13566', 'https://nvd.nist.gov/vuln/detail/CVE-2019-13566', 'https://github.com/ros/ros_comm/issues/1735', 'https://github.com/ros/ros_comm/pull/1771/files']",
        "https://github.com/aliasrobotics/RVD/issues/918"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "N/A",
        "subsystem": "cognition:middleware:ros",
        "package": "ros_comm",
        "languages": "['Python', 'C++']",
        "date-detected": "2019-07-02",
        "detected-by": "Daniel Wang",
        "detected-by-method": "N/A",
        "date-reported": "2019-11-22",
        "reported-by": "",
        "reported-by-relationship": "security researcher",
        "issue": "https://github.com/aliasrobotics/RVD/issues/918",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "Specified sizeof and initialized the buffer, see PR below.",
        "pull-request": "https://github.com/ros/ros_comm/pull/1771/files",
        "date-mitigation": ""
    }
}
```
