### ISSUE TITLE
roslib-socketio vulnerable to MITM attacks

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#919]
```yaml
{
    "id": 1,
    "title": "roslib-socketio vulnerable to MITM attacks",
    "type": "vulnerability",
    "description": "roslib-socketio - The standard ROS Javascript Library fork for add support to socket.io roslib-socketio downloads binary resources over HTTP, which leaves it vulnerable to MITM attacks. It may be possible to cause remote code execution (RCE) by swapping out the requested resources with an attacker controlled copy if the attacker is on the network or positioned in between the user and the remote server.",
    "cwe": "CWE-310 (Cryptographic Issues)",
    "cve": "CVE-2016-10681",
    "keywords": "['robot component: ROS', 'package: roslib-socketio']",
    "system": "ROS",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 9.3,
        "cvss-vector": "CVSS:3.0/AV:N/AC:M/Au:N/C:C/I:C/A:C"
    },
    "links": "['https://vulners.com/cve/CVE-2016-10681', 'https://www.npmjs.com/advisories/292', 'https://nvd.nist.gov/vuln/detail/CVE-2016-10681']",
    "flaw": {
        "phase": "unknown",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "",
        "detected-by": "",
        "detected-by-method": "N/A",
        "date-reported": "2018-05-29",
        "reported-by": "",
        "reported-by-relationship": "N/A",
        "issue": "",
        "reproducibility": "",
        "trace": "",
        "reproduction": "",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": ""
    }
}
```
