### ISSUE TITLE
RVD#920: cppcheck - (error) syntax error, Universal_Robots_ROS_Driver/ur_calibration/test/calibration_test.cpp:37

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#920]
```yaml
{
    "id": 920,
    "title": "RVD#920: cppcheck - (error) syntax error, Universal_Robots_ROS_Driver/ur_calibration/test/calibration_test.cpp:37",
    "type": "bug",
    "description": "[src/Universal_Robots_ROS_Driver/ur_calibration/test/calibration_test.cpp:37]: (error) syntax error",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "cppcheck",
        "static analysis",
        "testing",
        "triage",
        "bug"
    ],
    "system": "src/Universal_Robots_ROS_Driver/ur_calibration/test/calibration_test.cpp",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/920",
        "https://github.com/UniversalRobots/Universal_Robots_ROS_Driver"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "Universal_Robots_ROS_Driver",
        "languages": "None",
        "date-detected": "2019-12-05 (09:33)",
        "detected-by": "Alias Robotics",
        "detected-by-method": "testing static",
        "date-reported": "2019-12-05 (09:33)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/920",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "See artifacts below (if available)",
        "reproduction-image": "gitlab.com/aliasrobotics/offensive/alurity/pipelines/pipeline_ur_ros_official_cppcheck/-/jobs/370181107/artifacts/download"
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": null
    }
}
```
