### ISSUE TITLE
OpenSSH remote DoS in CB

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#921]
```yaml
{
    "id": 0,
    "title": "OpenSSH remote DoS in CB",
    "type": "vulnerability",
    "description": "We found that the Universal Robots Controllers' file system based in Debian is subject to CVE-2016-6210 which allows attackers with networking connection to the robot to cause a Denial of Service (DoS). The auth_password function in auth-passwd.c in sshd in OpenSSH before 7.3 does not limit password lengths for password authentication, which allows remote attackers to cause a denial of service (crypt CPU consumption) via a long string.",
    "cwe": "CWE-20 (Improper Input Validation)",
    "cve": "CVE-2016-6515",
    "keywords": [
        "Universal Robots",
        "manipulation",
        "cobot",
        "CB 3.x"
    ],
    "system": "Universal Robots Robot Controllers CB 3.x",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 7.6,
        "rvss-vector": "RVSS:1.0/AV:AN/AC:L/PR:N/UI:N/Y:Z/S:U/C:N/I:N/A:H/H:E",
        "severity-description": "high",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-6515",
        "https://nvd.nist.gov/vuln/detail/CVE-2016-6515",
        "https://github.com/opsxcq/exploit-CVE-2016-6515",
        "https://www.cvedetails.com/cve/CVE-2016-6515/"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "general issue",
        "architectural-location": "third-party",
        "application": "manipulator, control box",
        "subsystem": "communication",
        "package": "openssh-server",
        "languages": "C",
        "date-detected": null,
        "detected-by": "V\u00edctor Mayoral Vilches, Lander Usategui San Juan (Alias Robotics), Bernhard Dieber (Joanneum Research)",
        "detected-by-method": "testing violation",
        "date-reported": null,
        "reported-by": "V\u00edctor Mayoral Vilches (Alias Robotics)",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "always",
        "trace": "Not disclosed",
        "reproduction": "Not disclosed",
        "reproduction-image": "Not disclosed"
    },
    "exploitation": {
        "description": "Not disclosed",
        "exploitation-image": "Not disclosed",
        "exploitation-vector": "Not disclosed"
    },
    "mitigation": {
        "description": "Not disclosed",
        "pull-request": "Not disclosed"
    }
}
```
