### ISSUE TITLE
SROS2 leaks node information

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#922]
```yaml
{
    "id": 0,
    "title": "SROS2 leaks node information",
    "type": "exposure",
    "description": "We found that SROS 2, the tools to generate and distribute keys for ROS 2 and use the underlying security plugins of DDS from ROS 2 leak node information due to a leaky default configuration as inidicated at https://github.com/ros2/sros2/blob/master/sros2/sros2/policy/defaults/dds/governance.xml#L13. This exposure was first raised in the Security Workshop of ROSCon 2019 (Nov. 2019). Further debugging the flaw indicates that there might be some additional underlying issues.",
    "cwe": "CWE-200 (Information Exposure)",
    "cve": "",
    "keywords": [
        "Robot Operating System 2",
        "ROS 2",
        "eloquent",
        "dashing"
    ],
    "system": "ros2",
    "vendor": "",
    "severity": {
        "rvss-score": 7.9,
        "rvss-vector": "RVSS:1.0/AV:AN/AC:L/PR:N/UI:N/Y:M/S:U/C:N/I:N/A:H/H:N",
        "severity-description": "high",
        "cvss-score": 7.5,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "links": [
        "https://ros-swg.github.io/ROSCon19_Security_Workshop/",
        "https://github.com/ros-swg/turtlebot3_demo",
        "https://github.com/ros2/sros2/blob/master/sros2/sros2/policy/defaults/dds/governance.xml#L13",
        "https://design.ros2.org/articles/ros2_dds_security.html",
        "https://asciinema.org/a/SSnSAMlOEoHfqhAuzC1R98STF"
    ],
    "flaw": {
        "phase": "runtime-operation",
        "specificity": "ROS-specific",
        "architectural-location": "platform code",
        "application": "any ROS 2 node communicating",
        "subsystem": "cognition:middleware",
        "package": "sros2",
        "languages": "Python",
        "date-detected": null,
        "detected-by": "V\u00edctor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "detected-by-method": "runtime detection",
        "date-reported": "2019-12-05",
        "reported-by": "V\u00edctor Mayoral Vilches and Lander Usategui San Juan (Alias Robotics)",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "always",
        "trace": "N/A",
        "reproduction": "https://asciinema.org/a/SSnSAMlOEoHfqhAuzC1R98STF",
        "reproduction-image": "Not available"
    },
    "exploitation": {
        "description": "A simple use of ros2cli allows to exploit this flaw. See https://asciinema.org/a/SSnSAMlOEoHfqhAuzC1R98STF for a walkthrough.",
        "exploitation-image": "Not available",
        "exploitation-vector": "Not available"
    },
    "mitigation": {
        "description": "Modify the policy and set rtps_protection_kind to ENCRYPT",
        "pull-request": ""
    }
}
```

**Comment by vmayoral** [comment]
Ticket updated, PR added.

**Comment by vmayoral** [comment]
<details><summary><code>alurity.yml</code> file to reproduce sros2 leak</summary>

```yaml
networks:
  - network:
    - driver: overlay
    - name: net1
    - encryption: false

containers:
  - container:
    - name: subject1
    - modules:
         - base: registry.gitlab.com/aliasrobotics/offensive/alurity/ros2/ros2:latest
         - network: net1
  - container:
    - name: subject2
    - modules:
         - base: registry.gitlab.com/aliasrobotics/offensive/alurity/ros2/ros2:latest
         - volume: registry.gitlab.com/aliasrobotics/offensive/alurity/deve_atom
         - network: net1
  - container:
    - name: attacker
    - modules:
         - base: registry.gitlab.com/aliasrobotics/offensive/alurity/ros2/ros2:latest
         - volume: registry.gitlab.com/aliasrobotics/offensive/alurity/reco_aztarna
         - network: net1

flow:
  - container:
    - name: subject1
    - window:
        - name: unsecure
        - commands:
          - command: "source /opt/ros2_ws/install/setup.bash"
          - command: "export ROS_DOMAIN_ID=0"
          - command: "ros2 run demo_nodes_cpp talker"
          - split: horizontal
          - command: "source /opt/ros2_ws/install/setup.bash"
          - command: "export ROS_DOMAIN_ID=0"
          - command: "env | grep ROS"  # this shows there's no security enabled at this point          
    - select: unsecure
  - container:
    - name: subject2
    - window:
        - name: secure
        - commands:
          - command: "source /opt/ros2_ws/install/setup.bash"
          - command: "export ROS_DOMAIN_ID=1"
          - command: "env | grep ROS"  # this shows there's no security enabled at this point
          - command: "ros2 run demo_nodes_cpp talker"
          - command: "export ROS_SECURITY_ENABLE=true"
          - command: "export ROS_SECURITY_STRATEGY=Enforce"
          - command: "export ROS_SECURITY_ROOT_DIRECTORY=/opt/ros2_ws/keystore"
          - command: "export ROS_SECURITY_LOOKUP_TYPE=MATCH_PREFIX"                    
          - command: "env | grep ROS"  # from this point on, there's security enabled
          - command: "ros2 run demo_nodes_cpp talker"
          - split: horizontal
          - command: "source /opt/ros2_ws/install/setup.bash"
          - command: "export ROS_DOMAIN_ID=1"
          - command: "cd /opt/ros2_ws/"          
          - command: "mkdir policy"
          # generate a security policy based on our current graph
          - command: "ros2 security generate_policy policy/my_policy.xml"
          - command: "cat policy/my_policy.xml"
          #  populated the keystore for all profiles
          - command: "ros2 security generate_artifacts -k keystore -p policy/my_policy.xml -n /_ros2cli"
          - command: "kill -9 $(pidof talker)"
    - select: secure
  - container:
    - name: attacker
    - window:
        - name: attacker_window
        - commands:
          - command: "source /opt/ros2_ws/install/setup.bash"
          - command: "aztarna -t ros2 -d 0 --daemon" 
          - split: horizontal
          - command: "source /opt/ros2_ws/install/setup.bash"
          - type: "aztarna -t ros2 -d 1 --daemon"          
    - select: attacker_window
  - attach: subject2

```
</details>
