### ISSUE TITLE
User enumeration in CB

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#923]
```yaml
{
    "id": 0,
    "title": "User enumeration in CB",
    "type": "vulnerability",
    "description": "We found that the Universal Robots Controllers' file system based in Debian is subject to CVE-2016-6210 which allows to perform user enumeration. The flaw affects OpenSSH which is exposed by default in port 22. Before 7.3, when SHA256 or SHA512 are used for user password hashing, uses BLOWFISH hashing on a static password when the username does not exist, which allows remote attackers to enumerate users by leveraging the timing difference between responses when a large password is provided.",
    "cwe": "CWE-200 (Information Exposure)",
    "cve": "CVE-2016-6210",
    "keywords": [
        "Universal Robots",
        "manipulation",
        "cobot",
        "CB 3.x"
    ],
    "system": "Universal Robots Robot Controllers CB 3.x",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 7.9,
        "rvss-vector": "RVSS:1.0/AV:AN/AC:L/PR:N/UI:N/Y:M/S:U/C:H/I:N/A:N/H:N",
        "severity-description": "medium",
        "cvss-score": 5.9,
        "cvss-vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N"
    },
    "links": [
        "https://www.debian.org/security/2016/dsa-3626",
        "https://tracker.debian.org/media/packages/o/openssh/changelog-1%3A6.0p1-4%2Bdeb7u6",
        "https://seclists.org/fulldisclosure/2016/Jul/51",
        "https://nvd.nist.gov/vuln/detail/CVE-2016-6210",
        "https://www.cvedetails.com/cve/CVE-2016-6210/?q=CVE-2016-6210#metasploit"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "general issue",
        "architectural-location": "third-party",
        "application": "manipulator, control box",
        "subsystem": "communication",
        "package": "N/A",
        "languages": "C",
        "date-detected": null,
        "detected-by": "V\u00edctor Mayoral Vilches, Lander Usategui San Juan (Alias Robotics), Bernhard Dieber (Joanneum Research)",
        "detected-by-method": "testing violation",
        "date-reported": "2019-12-05",
        "reported-by": "V\u00edctor Mayoral Vilches (Alias Robotics)",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "always",
        "trace": "Not disclosed",
        "reproduction": "Not disclosed",
        "reproduction-image": "Not disclosed"
    },
    "exploitation": {
        "description": "Not disclosed",
        "exploitation-image": "Not disclosed",
        "exploitation-vector": "Not disclosed"
    },
    "mitigation": {
        "description": "Not disclosed",
        "pull-request": "Not disclosed"
    }
}
```
