### ISSUE TITLE
Bash scripts (magic UR files) get launched automatically with root privileges and without validation or sanitizing

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#924]
```yaml
{
    "id": 0,
    "title": "Bash scripts (magic UR files) get launched automatically with root privileges and without validation or sanitizing",
    "type": "vulnerability",
    "description": "We found that the Universal Robots Controllers will automatically launch and execute certain magic files (bash scripts). The corresponding daemon is configured to run on every boot and presents apparently no filter except certain restrictions on the file name (so called magic UR files). Exemplary files can be found at https://www.universal-robots.com/download/?option=16449#section16447",
    "cwe": "CWE-20 (Improper Input Validation)",
    "cve": "requested",
    "keywords": [
        "Universal Robots",
        "manipulation",
        "cobot",
        "CB 3.1",
        "CB 3.4.5"
    ],
    "system": "Universal Robots Robot Controllers CB 3.1 3.4.5-100",
    "vendor": "Universal Robots",
    "severity": {
        "rvss-score": 10.0,
        "rvss-vector": "RVSS:1.0/AV:AN/AC:L/PR:N/UI:N/Y:Z/S:U/C:H/I:H/A:H/H:H",
        "severity-description": "critical",
        "cvss-score": 9.8,
        "cvss-vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "links": [
        "https://www.universal-robots.com/download/?option=16449#section16447"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "subject-specific",
        "architectural-location": "application-specific code",
        "application": "manipulator, control box",
        "subsystem": "cognition:manipulation",
        "package": "N/A",
        "languages": "shell",
        "date-detected": null,
        "detected-by": "Rub\u00e9n Campo Medina, Xabier Saez de C\u00e1mara, Lander Usategui San Juan, Unai Ayucar Carbajo (Alias Robotics)",
        "detected-by-method": "testing violation",
        "date-reported": "2019-12-05",
        "reported-by": "V\u00edctor Mayoral Vilches, Endika Gil Uriarte, Rub\u00e9n Campo Medina, Xabier Saez de C\u00e1mara, Lander Usategui San Juan, Unai Ayucar Carbajo (Alias Robotics)",
        "reported-by-relationship": "security researcher",
        "issue": null,
        "reproducibility": "always",
        "trace": "Not disclosed",
        "reproduction": "Not disclosed",
        "reproduction-image": "Not disclosed"
    },
    "exploitation": {
        "description": "Not disclosed",
        "exploitation-image": "Not disclosed",
        "exploitation-vector": "Not disclosed"
    },
    "mitigation": {
        "description": "Not disclosed",
        "pull-request": "Not disclosed"
    }
}
```
