### ISSUE TITLE
RVD#943: (warning) Member variable 'IKFastKinematicsPlugin

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#943]
```yaml
{
    "id": 943,
    "title": "RVD#943: (warning) Member variable 'IKFastKinematicsPlugin",
    "type": "bug",
    "description": "[src/fanuc/fanuc_m430ia_moveit_plugins/m430ia2p_kinematics/src/fanuc_m430ia2p_manipulator_ikfast_moveit_plugin.cpp:133]: (warning) Member variable 'IKFastKinematicsPlugin::num_joints_' is not initialized in the constructor.",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "cppcheck",
        "static analysis",
        "testing",
        "triage",
        "bug"
    ],
    "system": "src/fanuc/fanuc_m430ia_moveit_plugins/m430ia2p_kinematics/src/fanuc_m430ia2p_manipulator_ikfast_moveit_plugin.cpp",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/943"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2019-12-11 (08:39)",
        "detected-by": "Alias Robotics",
        "detected-by-method": "testing static",
        "date-reported": "2019-12-11 (08:39)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/943",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "See artifacts below (if available)",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": ""
    }
}
```
