### ISSUE TITLE
RVD#947: (warning) The class 'Finger' has 'copy constructor' but lack of 'operator='.

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#947]
```yaml
{
    "id": 947,
    "title": "RVD#947: (warning) The class 'Finger' has 'copy constructor' but lack of 'operator='.",
    "type": "bug",
    "description": "[src/robotiq/robotiq_3f_gripper_joint_state_publisher/src/robotiq_3f_gripper_joint_states.cpp:51]: (warning) The class 'Finger' has 'copy constructor' but lack of 'operator='.",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "cppcheck",
        "static analysis",
        "testing",
        "triage",
        "bug"
    ],
    "system": "src/robotiq/robotiq_3f_gripper_joint_state_publisher/src/robotiq_3f_gripper_joint_states.cpp",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/947"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2019-12-11 (11:03)",
        "detected-by": "Alias Robotics",
        "detected-by-method": "testing static",
        "date-reported": "2019-12-11 (11:03)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/947",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "See artifacts below (if available)",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": ""
    }
}
```
