### ISSUE TITLE
RVD#948: (warning) Return value of std

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#948]
```yaml
{
    "id": 948,
    "title": "RVD#948: (warning) Return value of std",
    "type": "bug",
    "description": "[src/industrial_core/industrial_robot_client/src/joint_trajectory_action.cpp:59]: (warning) Return value of std::remove() ignored. Elements remain in container.",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "cppcheck",
        "static analysis",
        "testing",
        "triage",
        "bug"
    ],
    "system": "src/industrial_core/industrial_robot_client/src/joint_trajectory_action.cpp",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/948"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2019-12-11 (11:20)",
        "detected-by": "Alias Robotics",
        "detected-by-method": "testing static",
        "date-reported": "2019-12-11 (11:20)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/948",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "See artifacts below (if available)",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": ""
    }
}
```
