### ISSUE TITLE
RVD#949: (warning) Using 'sizeof' on array given as function argument returns size of a pointer.

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#949]
```yaml
{
    "id": 949,
    "title": "RVD#949: (warning) Using 'sizeof' on array given as function argument returns size of a pointer.",
    "type": "bug",
    "description": "[src/motoman/motoman_driver/MotoPlus/CtrlGroup.c:457]: (warning) Using 'sizeof' on array given as function argument returns size of a pointer.",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "cppcheck",
        "static analysis",
        "testing",
        "triage",
        "bug"
    ],
    "system": "src/motoman/motoman_driver/MotoPlus/CtrlGroup.c",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/949"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2019-12-11 (11:37)",
        "detected-by": "Alias Robotics",
        "detected-by-method": "testing static",
        "date-reported": "2019-12-11 (11:37)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/949",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "See artifacts below (if available)",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": ""
    }
}
```
