### ISSUE TITLE
RVD#973: (error) Buffer is accessed out of bounds

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#973]
```yaml
{
    "id": 973,
    "title": "RVD#973: (error) Buffer is accessed out of bounds",
    "type": "bug",
    "description": "[src/industrial_calibration/industrial_extrinsic_cal/src/nodes/stereo_cal_srv.cpp:300]: (error) Buffer is accessed out of bounds: pose_scene_chars",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "cppcheck",
        "static analysis",
        "testing",
        "triage",
        "bug"
    ],
    "system": "src/industrial_calibration/industrial_extrinsic_cal/src/nodes/stereo_cal_srv.cpp",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/973"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "N/A",
        "languages": "None",
        "date-detected": "2019-12-11 (14:52)",
        "detected-by": "Alias Robotics",
        "detected-by-method": "testing static",
        "date-reported": "2019-12-11 (14:52)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/973",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "See artifacts below (if available)",
        "reproduction-image": ""
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": ""
    }
}
```
