### ISSUE TITLE
authenticated user privilege escalation via local access in Intel NUC

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#986]
```yaml
id: 986
title: "CB3.1 3.4.5-100 hard-coded public credentials for controller"
type: vulnerability
description: "Improper buffer restrictions in firmware for Intel(R) NUC(R) may allow an authenticated user to potentially enable escalation of privilege via local access."
cwe: "CWE-269 (Improper Privilege Management)"
cve: "CVE-2019-14608"
keywords: [
    "Intel",
    "Intel NUC",
]
system: "Intel NUC"
vendor: "Intel"
severity:
  rvss-score: 0
  rvss-vector: ""
  severity-description: "high"
  cvss-score: 7.8
  cvss-vector: "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:H/A:H"
links: [
    'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14608',
    'https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00323.html',
]
flaw:
  phase: 
  specificity: subject-specific
  architectural-location: application-specific code
  application: 
  subsystem: cognition
  package: N/A
  languages: N/A
  date-detected: 
  detected-by: 
  detected-by-method: 
  date-reported: 2019-08-03
  reported-by: unknown (at the time of filing this ticket)
  reported-by-relationship: 
  issue: https://github.com/aliasrobotics/RVD/issues/986
  reproducibility: 
  trace: N/A
  reproduction: Not disclosed
  reproduction-image: Not disclosed
exploitation:
  description: Not disclosed
  exploitation-image: Not disclosed
  exploitation-vector: Not disclosed
mitigation:
  description: Not disclosed
  pull-request: Not disclosed
  date-mitigation: 2019-12-10
```
