### ISSUE TITLE
RVD#987: (error) syntax error

### ISSUE THREAD

**Issue by vmayoral** [aliasrobotics/RVD#987]
```yaml
{
    "id": 987,
    "title": "RVD#987: (error) syntax error",
    "type": "bug",
    "description": "[src/Universal_Robots_ROS_Driver/ur_calibration/test/calibration_test.cpp:37]: (error) syntax error",
    "cwe": "None",
    "cve": "None",
    "keywords": [
        "cppcheck",
        "static analysis",
        "testing",
        "triage",
        "bug"
    ],
    "system": "src/Universal_Robots_ROS_Driver/ur_calibration/test/calibration_test.cpp",
    "vendor": null,
    "severity": {
        "rvss-score": 0,
        "rvss-vector": "",
        "severity-description": "",
        "cvss-score": 0,
        "cvss-vector": ""
    },
    "links": [
        "https://github.com/aliasrobotics/RVD/issues/987"
    ],
    "flaw": {
        "phase": "testing",
        "specificity": "N/A",
        "architectural-location": "N/A",
        "application": "N/A",
        "subsystem": "N/A",
        "package": "Universal_Robots_ROS_Driver",
        "languages": "None",
        "date-detected": "2020-01-09 (11:21)",
        "detected-by": "Alias Robotics",
        "detected-by-method": "testing static",
        "date-reported": "2020-01-09 (11:21)",
        "reported-by": "Alias Robotics",
        "reported-by-relationship": "automatic",
        "issue": "https://github.com/aliasrobotics/RVD/issues/987",
        "reproducibility": "always",
        "trace": "",
        "reproduction": "See artifacts below (if available)",
        "reproduction-image": "gitlab.com/aliasrobotics/offensive/alurity/pipelines/pipeline_ur_ros_official_cppcheck/-/jobs/397972070/artifacts/download"
    },
    "exploitation": {
        "description": "",
        "exploitation-image": "",
        "exploitation-vector": ""
    },
    "mitigation": {
        "description": "",
        "pull-request": "",
        "date-mitigation": ""
    }
}
```
